Repository molgenis/molgenis, pull requests merged in 2018-08, with the labels that each got.

#7641 [CHORE] Update App developer documentation
  docs/developer_documentation/app-development.md
Labels: master

#7643 [CHORE] Updated report documentation
  docs/data/advanced_data_example_v20171206.xlsx
  docs/images/reports/view-entityreport-specific-test_cities.png
  docs/user_documentation/finding-data/guide-explore.md
Labels: master

#7617 Fix #7615 Deleting all row-level secured data does not delete all data
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/AbstractRowLevelSecurityRepositoryDecorator.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecoratorTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/owned/RowLevelSecurityRepositoryDecoratorTest.java
Labels: master

#7609 Fix #7588 Entity report permissions
  molgenis-app/src/main/java/org/molgenis/app/WebAppPermissionRegistry.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/PermissionChecker.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/PermissionCheckingDecorator.java
  molgenis-data/src/test/java/org/molgenis/data/decorator/PermissionCheckingDecoratorTest.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/DataExplorerPermissionConfig.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/EntityTypeReportPermission.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerService.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerServiceImpl.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/Module.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/decorator/EntityReportDecoratorFactory.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/decorator/EntityReportPermissionChecker.java
  molgenis-dataexplorer/src/test/java/org/molgenis/dataexplorer/controller/DataExplorerServiceImplTest.java
  molgenis-dataexplorer/src/test/java/org/molgenis/dataexplorer/decorator/EntityReportPermissionCheckerTest.java
Labels: master

#7647 Fix #7588 Entity report permissions (NPE)
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerServiceImpl.java
  molgenis-dataexplorer/src/test/java/org/molgenis/dataexplorer/controller/DataExplorerServiceImplTest.java
Labels: master

#7646 Fix #7611 EMX import with tags fails when ignoring metadata
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxImportJob.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/ImportWriter.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/emx/ImportWriterTest.java
Labels: master

#7645 Fix #7629 Metadata manager scrolls through menu with top logo
  molgenis-core-ui/src/main/resources/js/bootstrap-4/menu/molgenis-menu.js
Labels: master

#7644 Upgrade Spring Cairo-SR2 to Cairo-SR3
  pom.xml
Labels: master

#7640 Fix compiler warnings
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/decorator/AppRepositoryDecoratorTest.java
  molgenis-beacon/src/test/java/org/molgenis/beacon/service/BeaconQueryServiceTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/PackageWizardPageTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/style/StyleServiceTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/style/StyleSheetRepositoryDecoratorTest.java
  molgenis-data-index/src/test/java/org/molgenis/data/index/IndexedRepositoryDecoratorTest.java
  molgenis-data-platform/src/main/java/org/molgenis/data/platform/decorators/SystemRepositoryDecoratorRegistryImpl.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/RowLevelSecurityRepositoryDecorator.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/meta/EntityTypeRepositorySecurityDecoratorTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecoratorTest.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/AttributeValidator.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorRegistryImpl.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/meta/DynamicDecoratorPopulator.java
  molgenis-data/src/test/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorRegistryImplTest.java
  molgenis-data/src/test/java/org/molgenis/data/decorator/meta/DynamicDecoratorPopulatorTest.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutor.java
  molgenis-ontology-core/src/test/java/org/molgenis/ontology/core/repository/OntologyRepositoryTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/config/SecurityITConfig.java
Labels: master

#7653 Update book.json: add MOLGENIS 7.0
  book.json
Labels: master

#7656 Fix #7655 Fix snapshot dependency in molgenis-data-row-edit module
  molgenis-data-row-edit/pom.xml
Labels: 7.0.0-RC

#7657 Fix #7655 Fix snapshot dependency in molgenis-data-row-edit module
  molgenis-data-row-edit/pom.xml
Labels: master

#7654 Bump version 7.0.0-SHAPSHOT --> 7.1.0-SHAPSHOT
  molgenis-amazon-bucket/pom.xml
  molgenis-api-tests/pom.xml
  molgenis-app-manager/pom.xml
  molgenis-app/pom.xml
  molgenis-beacon/pom.xml
  molgenis-bootstrap/pom.xml
  molgenis-core-ui/package.json
  molgenis-core-ui/pom.xml
  molgenis-core/pom.xml
  molgenis-data-cache/pom.xml
  molgenis-data-csv/pom.xml
  molgenis-data-elasticsearch/pom.xml
  molgenis-data-excel/pom.xml
  molgenis-data-file/pom.xml
  molgenis-data-i18n/pom.xml
  molgenis-data-import/pom.xml
  molgenis-data-index/pom.xml
  molgenis-data-migrate/pom.xml
  molgenis-data-platform/pom.xml
  molgenis-data-plugin/pom.xml
  molgenis-data-postgresql/pom.xml
  molgenis-data-rest-client/pom.xml
  molgenis-data-rest/pom.xml
  molgenis-data-row-edit/pom.xml
  molgenis-data-security/pom.xml
  molgenis-data-validation/pom.xml
  molgenis-data-vcf/pom.xml
  molgenis-data/pom.xml
  molgenis-dataexplorer/pom.xml
  molgenis-fair/pom.xml
  molgenis-file-ingester/pom.xml
  molgenis-genomebrowser/pom.xml
  molgenis-i18n/pom.xml
  molgenis-jobs/pom.xml
  molgenis-js/pom.xml
  molgenis-metadata-manager/pom.xml
  molgenis-navigator/pom.xml
  molgenis-one-click-importer/pom.xml
  molgenis-ontology-core/pom.xml
  molgenis-ontology/pom.xml
  molgenis-platform-integration-tests/pom.xml
  molgenis-python/pom.xml
  molgenis-questionnaires/pom.xml
  molgenis-r/pom.xml
  molgenis-scripts-core/pom.xml
  molgenis-scripts/pom.xml
  molgenis-searchall/pom.xml
  molgenis-security-core/pom.xml
  molgenis-security-ui/pom.xml
  molgenis-security/pom.xml
  molgenis-semantic-mapper/pom.xml
  molgenis-semantic-search/pom.xml
  molgenis-settings-ui/pom.xml
  molgenis-settings/pom.xml
  molgenis-swagger/pom.xml
  molgenis-test/pom.xml
  molgenis-util/pom.xml
  molgenis-web/pom.xml
  pom.xml
Labels: master

#7690 [CHORE] Added release flow to branch 7.0
  .gitignore
  .release/generate_release_properties.bash
  Jenkinsfile
  pom.xml
Labels: 7.0.0-RC

#7691 [FIX] merge with master sonar build
  Jenkinsfile
Labels: 7.0.0-RC, bug

#7694 [FIX] Artifact id name "molgenis-app" should be "molgenis"
  Jenkinsfile
Labels: 7.0.0-RC

#7699 [FIX] skip integration tests
  Jenkinsfile
Labels: 7.0.0-RC

#7689 Fix #7542 #7665 #7666 Python client, test and documentation fixes
  docs/developer_documentation/ref-python.md
  molgenis-python/src/main/resources/templates/molgenis.py.ftl
  molgenis-python/src/test/python/test-rest.py
Labels: 7.0.0-RC

#7696 [CHORE] updated app development documentation to match new templating strategy
  docs/developer_documentation/app-development.md
Labels: 7.0.0-RC

#7705 [FIX] Questionnaire PDF print styling issues
  molgenis-questionnaires/src/main/frontend/src/services/questionnaireService.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/services/questionnaireService.spec.js
Labels: 7.0.0-RC

#7703 Fix #7692 Consent question not shown when filling in questionnaire initially
  molgenis-questionnaires/src/main/frontend/src/store/actions.js
Labels: 7.0.0-RC

#7701 Fix #7658 #7661 Updated navigator from vue-bootstrap to bootstrap 4
  molgenis-navigator/src/main/frontend/index.html
  molgenis-navigator/src/main/frontend/src/components/Navigator.vue
Labels: 7.0.0-RC, bug

#7708 Fix #7684: PENDING index jobs aren't picked up after an application r…
  molgenis-data-index/src/main/java/org/molgenis/data/index/bootstrap/IndexBootstrapper.java
  molgenis-data-index/src/test/java/org/molgenis/data/index/bootstrap/IndexBootstrapperTest.java
Labels: 7.0.0-RC

#7715 chore (Jenkinsfile): Retrieve build secrets from vault, set environment variables in script
  Jenkinsfile
Labels: 7.0.0-RC

#7721 [FIX] Fix #7666 Python test script UploadZipAndDeleteList.py is broke…
  molgenis-python/src/main/resources/templates/molgenis.py.ftl
Labels: 7.0.0-RC

#7722 Fix 7714 Import zip file as manager in one click importer fails
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/impl/EntityServiceImpl.java
  molgenis-one-click-importer/src/test/java/org/molgenis/oneclickimporter/service/EntityServiceImplTest.java
Labels: 7.0.0-RC

#7723 [FIX] Reverted navigator changes
  molgenis-navigator/src/main/frontend/index.html
  molgenis-navigator/src/main/frontend/package.json
  molgenis-navigator/src/main/frontend/src/components/Navigator.vue
  molgenis-navigator/src/main/frontend/src/main.js
  molgenis-navigator/src/main/frontend/yarn.lock
Labels: 7.0.0-RC

#7726 Add module molgenis-validation
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/ImportWriter.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlExceptionTranslator.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlRepository.java
  molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/PostgreSqlRepositoryTest.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/RestController.java
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/v2/RestControllerV2Test.java
  molgenis-data-validation/pom.xml
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/DefaultValueReferenceValidatorImpl.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/EntityAttributesValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/MolgenisValidationException.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/QueryValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/RepositoryValidationDecorator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/AttributeValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/EntityTypeValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/PackageValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/TagValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/EntityAttributesValidatorTest.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/RepositoryValidationDecoratorTest.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/schedule/JobScheduler.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/schedule/ScheduledJobRepositoryDecorator.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/schedule/ScheduledJobRepositoryDecoratorFactory.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/schedule/ScheduledJobRepositoryDecoratorTest.java
  molgenis-validation/pom.xml
  molgenis-validation/src/main/java/org/molgenis/validation/ConstraintViolation.java
  molgenis-validation/src/main/java/org/molgenis/validation/InvalidJsonSchemaException.java
  molgenis-validation/src/main/java/org/molgenis/validation/JsonValidationException.java
  molgenis-validation/src/main/java/org/molgenis/validation/JsonValidator.java
  molgenis-validation/src/main/java/org/molgenis/validation/ValidationI18nConfig.java
  molgenis-validation/src/main/resources/l10n/validation_en.properties
  molgenis-validation/src/test/java/org/molgenis/validation/ConstraintViolationTest.java
  molgenis-validation/src/test/java/org/molgenis/validation/JsonValidatorTest.java
  pom.xml
Labels: master

#7730 Parameterized Dynamic Decorators
  .idea/fileTemplates/MolgenisDynamicDecorator.java
  .idea/fileTemplates/MolgenisException.java
  molgenis-data/pom.xml
  molgenis-data/src/main/java/org/molgenis/data/decorator/DecoratorParametersRepositoryDecorator.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/DecoratorParametersRepositoryDecoratorFactory.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorFactory.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorFactoryRegistrar.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorRegistryImpl.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/meta/DecoratorConfiguration.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/meta/DecoratorConfigurationMetadata.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/meta/DecoratorParameters.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/meta/DecoratorParametersFactory.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/meta/DecoratorParametersMetadata.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/meta/DynamicDecorator.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/meta/DynamicDecoratorMetadata.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/meta/DynamicDecoratorPopulator.java
  molgenis-data/src/test/java/org/molgenis/data/decorator/DecoratorParametersRepositoryDecoratorTest.java
  molgenis-data/src/test/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorRegistryImplTest.java
  molgenis-data/src/test/java/org/molgenis/data/decorator/meta/DynamicDecoratorPopulatorTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/config/JsonTestConfig.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/data/decorator/AddingRepositoryDecorator.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/data/decorator/AddingRepositoryDecoratorFactory.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/data/decorator/PostFixingRepositoryDecorator.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/data/decorator/PostFixingRepositoryDecoratorFactory.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/DynamicDecoratorIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java
Labels: master

#7735 Fix 7733 Cannot deploy molgenis app due to UnsatisfiedDependencyExcep…
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionConfig.java
Labels: master, mod:jobs

#7738 [CHORE] bump master version to 7.2.0-SNAPSHOT
  molgenis-amazon-bucket/pom.xml
  molgenis-api-tests/pom.xml
  molgenis-app-manager/pom.xml
  molgenis-app/pom.xml
  molgenis-beacon/pom.xml
  molgenis-bootstrap/pom.xml
  molgenis-core-ui/pom.xml
  molgenis-core/pom.xml
  molgenis-data-cache/pom.xml
  molgenis-data-csv/pom.xml
  molgenis-data-elasticsearch/pom.xml
  molgenis-data-excel/pom.xml
  molgenis-data-file/pom.xml
  molgenis-data-i18n/pom.xml
  molgenis-data-icd10/pom.xml
  molgenis-data-import/pom.xml
  molgenis-data-index/pom.xml
  molgenis-data-migrate/pom.xml
  molgenis-data-platform/pom.xml
  molgenis-data-plugin/pom.xml
  molgenis-data-postgresql/pom.xml
  molgenis-data-rest-client/pom.xml
  molgenis-data-rest/pom.xml
  molgenis-data-row-edit/pom.xml
  molgenis-data-security/pom.xml
  molgenis-data-validation/pom.xml
  molgenis-data-vcf/pom.xml
  molgenis-data/pom.xml
  molgenis-dataexplorer/pom.xml
  molgenis-fair/pom.xml
  molgenis-file-ingester/pom.xml
  molgenis-genomebrowser/pom.xml
  molgenis-i18n/pom.xml
  molgenis-jobs/pom.xml
  molgenis-js/pom.xml
  molgenis-metadata-manager/pom.xml
  molgenis-navigator/pom.xml
  molgenis-one-click-importer/pom.xml
  molgenis-ontology-core/pom.xml
  molgenis-ontology/pom.xml
  molgenis-platform-integration-tests/pom.xml
  molgenis-python/pom.xml
  molgenis-questionnaires/pom.xml
  molgenis-r/pom.xml
  molgenis-scripts-core/pom.xml
  molgenis-scripts/pom.xml
  molgenis-searchall/pom.xml
  molgenis-security-core/pom.xml
  molgenis-security-ui/pom.xml
  molgenis-security/pom.xml
  molgenis-semantic-mapper/pom.xml
  molgenis-semantic-search/pom.xml
  molgenis-settings-ui/pom.xml
  molgenis-settings/pom.xml
  molgenis-swagger/pom.xml
  molgenis-test/pom.xml
  molgenis-util/pom.xml
  molgenis-validation/pom.xml
  molgenis-web/pom.xml
  pom.xml
Labels: master
