Repository molgenis/molgenis, pull requests merged in 2018-07, with the labels that each got.

#7490 Fix #7415 My generated algorithm in mapping service starts with tabs
  molgenis-semantic-mapper/src/main/resources/templates/view-attribute-mapping.ftl
Labels: master

#7491 Partial fix #7437: Some questionnaire widgets do not get translated
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/AttributeResponseV2.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/CategoricalUtils.java
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/v2/RestControllerV2Test.java
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourceCollectionResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourceCollectionResponseIncludingCategories.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourceCollectionResponseUnknownEntityType.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourcePartialAttributeInCompoundInCompoundResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourcePartialAttributeInCompoundResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourcePartialAttributeResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourcePartialAttributesResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourcePartialSubAttributeResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourcePartialSubAttributesResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourcePartialSubSubAttributesResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourceResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourceResponseIncludingCategories.json
  molgenis-data-security/src/main/resources/l10n/data-security_nl.properties
  molgenis-data/src/main/resources/l10n/data_nl.properties
Labels: master

#7500 Fix #7488 Cannot map to existing entity in mapping service
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/MappingServiceImpl.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/MappingServiceImplTest.java
Labels: master

#7507 Fix #7417 Mapping service plugin table alignment issue
  molgenis-semantic-mapper/src/main/resources/css/mapping-service.css
  molgenis-semantic-mapper/src/main/resources/js/single-mapping-project.js
  molgenis-semantic-mapper/src/main/resources/templates/view-single-mapping-project.ftl
Labels: master

#7506 Fix #7416 Large text indexing results in exception
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/client/MappingContentBuilder.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/client/MappingContentBuilderTest.java
Labels: master

#7508 Fix #7496 Mapping service attribute search results incorrect count/results
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/MappingServiceControllerTest.java
Labels: master

#7511 Fix #7502: When I reload questionnaire page, the answers are gone
  molgenis-questionnaires/src/main/frontend/src/main.js
  molgenis-questionnaires/src/main/frontend/src/store/getters.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/getters.spec.js
  molgenis-questionnaires/src/test/resources/emx-questionnaire.xls
Labels: master

#7510 M5965: As user with viewer role i can only see the package/data in my group
  molgenis-data-security/src/main/java/org/molgenis/data/security/PackagePermission.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/exception/ParentPackagePermissionDeniedException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/EntityTypeRepositorySecurityDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/permission/DataPermissionConfig.java
  molgenis-data-security/src/main/resources/l10n/data-security_en.properties
  molgenis-data-security/src/test/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecoratorTest.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/model/PackageRepositoryDecoratorFactory.java
Labels: master

#7499 Metadata service code improvements
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetaDataParser.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/ImportWriter.java
  molgenis-data/src/main/java/org/molgenis/data/RepositoryCreationException.java
  molgenis-data/src/main/java/org/molgenis/data/meta/MetaDataService.java
  molgenis-data/src/main/java/org/molgenis/data/meta/MetaDataServiceImpl.java
  molgenis-data/src/main/java/org/molgenis/data/support/DataServiceImpl.java
  molgenis-data/src/main/resources/l10n/data_en.properties
  molgenis-data/src/main/resources/l10n/data_nl.properties
  molgenis-data/src/test/java/org/molgenis/data/DataServiceImplTest.java
  molgenis-data/src/test/java/org/molgenis/data/RepositoryCreationExceptionTest.java
  molgenis-data/src/test/java/org/molgenis/data/meta/MetaDataServiceImplTest.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/service/MetadataManagerServiceImpl.java
  molgenis-metadata-manager/src/test/java/org/molgenis/metadata/manager/service/MetadataManagerServiceTest.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/importer/OntologyImportService.java
Labels: master

#7518 Fix squid:S2229 Methods should not call same-class @Transactional methods
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/RestController.java
Labels: master

#7516 Fix #7478 Row-level secured repository throws acl exceptions
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/PluginSecurityRepositoryDecorator.java
  molgenis-data-plugin/src/test/java/org/molgenis/data/plugin/model/PluginSecurityRepositoryDecoratorTest.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/EntityTypeRepositorySecurityDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/RowLevelSecurityRepositoryDecorator.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecoratorTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/owned/RowLevelSecurityRepositoryDecoratorTest.java
  molgenis-data/src/main/java/org/molgenis/data/DataAlreadyExistsException.java
  molgenis-data/src/main/java/org/molgenis/data/EntityAlreadyExistsException.java
  molgenis-data/src/main/resources/l10n/data_en.properties
  molgenis-data/src/main/resources/l10n/data_nl.properties
  molgenis-data/src/test/java/org/molgenis/data/EntityAlreadyExistsExceptionTest.java
  molgenis-web/src/main/java/org/molgenis/web/exception/GlobalControllerExceptionHandler.java
Labels: master

#7519 Replace LinkedHashMap collectors with MapCollectors.toLinkedMap
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/client/ClientFacade.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlRepositoryCollection.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/EntityTypeValidator.java
  molgenis-data/src/main/java/org/molgenis/data/meta/EntityTypeRepositoryDecorator.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/EntityType.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/AttributeMapper.java
  molgenis-util/src/test/java/org/molgenis/util/stream/MapCollectorsTest.java
Labels: master

#7517 Fix #7498 Mappings between molgenis 6 and 7 not compatible
  docs/user_documentation/ref-expressions.md
  molgenis-js/src/main/resources/js/script-evaluator.js
  molgenis-js/src/test/java/org/molgenis/js/JsMagmaScriptEvaluatorTest.java
Labels: master

#7495 Refactor SemanticSearchService to allow BiobankUniverse-based algorithm
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/repository/OntologyRepository.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/service/OntologyService.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/service/impl/OntologyServiceImpl.java
  molgenis-ontology-core/src/test/java/org/molgenis/ontology/core/repository/OntologyRepositoryTest.java
  molgenis-ontology-core/src/test/java/org/molgenis/ontology/core/service/impl/OntologyServiceImplTest.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/algorithmgenerator/service/AlgorithmGeneratorService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/algorithmgenerator/service/impl/AlgorithmGeneratorServiceImpl.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/config/MappingConfig.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/TagWizardController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/AlgorithmService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImpl.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/AlgorithmTemplateService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/AlgorithmTemplateServiceImpl.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/algorithmgenerator/service/impl/AlgorithmGeneratorServiceImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/MappingServiceControllerTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplIT.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmTemplateServiceImplTest.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/config/SemanticSearchConfig.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/explain/bean/AttributeSearchResults.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/explain/bean/EntityTypeSearchResults.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/explain/bean/ExplainedAttribute.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/explain/bean/ExplainedAttributeDto.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/semantic/Hits.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/service/SemanticSearchService.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/service/impl/SemanticSearchServiceImpl.java
  molgenis-semantic-search/src/test/java/org/molgenis/semanticsearch/service/impl/SemanticSearchServiceHelperTest.java
  molgenis-semantic-search/src/test/java/org/molgenis/semanticsearch/service/impl/SemanticSearchServiceImplTest.java
Labels: master

#7532 Fix #7530 FDP entity reports broken
  molgenis-app/src/main/java/org/molgenis/app/WebAppSecurityConfig.java
  molgenis-fair/src/main/java/org/molgenis/fair/controller/FairController.java
  molgenis-fair/src/main/resources/templates/view-entityreport-specific-fdp_Catalog.ftl
  molgenis-fair/src/main/resources/templates/view-entityreport-specific-fdp_Dataset.ftl
  molgenis-fair/src/main/resources/templates/view-entityreport-specific-fdp_Distribution.ftl
  molgenis-fair/src/main/resources/templates/view-entityreport-specific-fdp_Metadata.ftl
Labels: master

#7537 Fix #7528: As non-su I cannot import data
  molgenis-data/src/main/java/org/molgenis/data/meta/MetaUtils.java
Labels: master

#7548 Fix #7520 Footer below Vue plugin: link to MOLGENIS website broken
  molgenis-core-ui/src/main/resources/js/bootstrap-4/footer/molgenis-footer.js
Labels: master

#7538 Fix squid:S3305: Factory method injection @Configuration
  molgenis-data-i18n/src/main/java/org/molgenis/data/i18n/LocalizationConfig.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/ImporterConfiguration.java
  molgenis-data-index/src/main/java/org/molgenis/data/index/IndexConfig.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/DatabaseConfig.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlConfiguration.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionConfig.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/SortaConfig.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/config/MappingConfig.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/config/SemanticSearchConfig.java
Labels: master

#7540 Refactor remove duplicate isSystemPackage implementation from EntityU…
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/utils/EntityHydration.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/AggregateUtils.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/ElasticsearchService.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/AggregationGenerator.java
  molgenis-data-i18n/src/main/java/org/molgenis/data/i18n/SystemEntityTypeI18nInitializer.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetaDataParser.java
  molgenis-data-platform/src/main/java/org/molgenis/data/meta/system/SystemEntityTypePersister.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlQueryGenerator.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlQueryUtils.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlRepository.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlRepositoryCollection.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/identifier/EntityTypeRegistryImpl.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/AttributeFilterToFetchConverter.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/AttributeResponseV2.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/EntityAggregatesResponse.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/EntityTypeResponseV2.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/RestControllerV2.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/PackagePermissionUtils.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/Group.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/GroupMetadata.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/Role.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMetadata.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/DefaultValueReferenceValidatorImpl.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/RepositoryValidationDecorator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/AttributeValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/EntityTypeValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/PackageValidator.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/utils/VcfWriterUtils.java
  molgenis-data/src/main/java/org/molgenis/data/CascadeDeleteRepositoryDecorator.java
  molgenis-data/src/main/java/org/molgenis/data/EntityManagerImpl.java
  molgenis-data/src/main/java/org/molgenis/data/meta/MetaDataServiceImpl.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/Attribute.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/AttributeMetadata.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/EntityType.java
  molgenis-data/src/main/java/org/molgenis/data/populate/DefaultValuePopulator.java
  molgenis-data/src/main/java/org/molgenis/data/support/DynamicEntity.java
  molgenis-data/src/main/java/org/molgenis/data/support/EntityReference.java
  molgenis-data/src/main/java/org/molgenis/data/support/LazyEntity.java
  molgenis-data/src/main/java/org/molgenis/data/util/AttributeUtils.java
  molgenis-data/src/main/java/org/molgenis/data/util/EntityTypeUtils.java
  molgenis-data/src/main/java/org/molgenis/data/util/EntityUtils.java
  molgenis-data/src/main/java/org/molgenis/data/util/MetaUtils.java
  molgenis-data/src/test/java/org/molgenis/data/meta/MetaDataServiceImplTest.java
  molgenis-data/src/test/java/org/molgenis/data/meta/MetaUtilsTest.java
  molgenis-data/src/test/java/org/molgenis/data/support/AttributeUtilsTest.java
  molgenis-data/src/test/java/org/molgenis/data/support/EntityTypeUtilsTest.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/NegotiatorController.java
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/AttributeMapper.java
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/EntityTypeMapper.java
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/service/MetadataManagerServiceImpl.java
  molgenis-metadata-manager/src/test/java/org/molgenis/metadata/manager/mapper/AttributeMapperTest.java
  molgenis-metadata-manager/src/test/java/org/molgenis/metadata/manager/mapper/EntityTypeMapperTest.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/impl/EntityServiceImpl.java
  molgenis-searchall/src/main/java/org/molgenis/searchall/service/SearchAllService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/algorithmgenerator/generator/AbstractCategoryAlgorithmGenerator.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/mapping/model/MappingTarget.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/MappingServiceImpl.java
Labels: master

#7555 Fix #7545: SearchAll does not show thrown exceptions
  molgenis-searchall/src/main/frontend/src/components/SearchAll.vue
  molgenis-searchall/src/main/frontend/src/store/actions.js
  molgenis-searchall/src/main/frontend/src/store/mutations.js
  molgenis-searchall/src/main/frontend/src/store/state.js
  molgenis-searchall/src/main/frontend/test/unit/specs/actions.spec.js
Labels: master

#7503 [CHORE] Use Jenkins on Kubernetes to evaluate Sonar quality check
  Jenkinsfile
  molgenis-app/DOCKER.md
  molgenis-app/Dockerfile
  molgenis-app/docker-compose.yml
  molgenis-app/pom.xml
Labels: master

#7562 [FEATURE] Data explorer delete button for those who have the proper permission
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-dataexplorer/src/main/resources/js/dataexplorer.js
  molgenis-dataexplorer/src/main/resources/templates/view-dataexplorer.ftl
Labels: master

#7552 [FEATURE] Add READMETA PermissionSet
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerIT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v2/RestControllerV2IT.java
  molgenis-app/src/main/java/org/molgenis/app/WebAppPermissionRegistry.java
  molgenis-app/src/test/java/org/molgenis/app/WebAppPermissionRegistryTest.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/permission/DataPermissionConfig.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/PermissionSet.java
  molgenis-security/src/main/resources/js/permissionmanager.js
  molgenis-security/src/main/resources/templates/view-permissionmanager-entity-class.ftl
  molgenis-security/src/main/resources/templates/view-permissionmanager-package.ftl
Labels: master

#7564 Fix #7558: Test Questionnaire EMX file is not properly localized
  molgenis-questionnaires/src/test/resources/emx-questionnaire.xls
Labels: master

#7563 Fix #7536 Cannot select label in compound
  molgenis-core-ui/src/main/javascript/modules/react-components/EntitySelectBox.js
  molgenis-dataexplorer/src/main/resources/js/dataexplorer-data.js
Labels: master

#7565 Fix Sonar blocker: Remove session attribute from UserManagerController
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/usermanager/UserManagerController.java
Labels: master

#7544 Feature/questionnaire logo and intro
  docs/user_documentation/guide-questionnaire.md
  molgenis-questionnaires/src/main/frontend/src/flow.types.js
  molgenis-questionnaires/src/main/frontend/src/main.js
  molgenis-questionnaires/src/main/frontend/src/pages/QuestionnaireOverview.vue
  molgenis-questionnaires/src/main/frontend/src/services/questionnaireService.js
  molgenis-questionnaires/src/main/frontend/src/store/actions.js
  molgenis-questionnaires/src/main/frontend/src/store/index.js
  molgenis-questionnaires/src/main/frontend/src/store/mutations.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/components/QuestionnaireOverview.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/services/questionnaireService.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/actions.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/mutations.spec.js
Labels: master

#7569 Revert "Fix #7528: As non-su I cannot import data"
  molgenis-data/src/main/java/org/molgenis/data/util/MetaUtils.java
Labels: master

#7567 Superuser-only usage of mapping service
  molgenis-app/src/main/java/org/molgenis/app/WebAppPermissionRegistry.java
  molgenis-app/src/test/java/org/molgenis/app/WebAppPermissionRegistryTest.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/MappingServiceImpl.java
Labels: master

#7570 Fix #7543 Vue style plugins are broken when using a 'top' logo
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/settings/AppDbSettings.java
  molgenis-core-ui/src/main/resources/css/bootstrap-4/menu/fixed-top-menu.css
  molgenis-core-ui/src/main/resources/js/bootstrap-4/menu/molgenis-menu.js
  molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl
  molgenis-platform-integration-tests/src/main/java/org/molgenis/integrationtest/data/TestAppSettings.java
  molgenis-settings/src/main/java/org/molgenis/settings/AppSettings.java
Labels: master

#7574 Fix #7543 Vue style plugins are broken when using a 'top' logo II
  molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl
Labels: master

#7573 Fix es-lint warnings about missing spaces
  molgenis-searchall/src/main/frontend/src/components/SearchAll.vue
  molgenis-searchall/src/main/frontend/src/store/mutations.js
Labels: 7.0.0-RC, master, mod:searchall

#7576 Fix #7575 Questionnaire form style broken
  molgenis-questionnaires/src/main/frontend/src/components/ChapterForm.vue
Labels: master, mod:questionnaires

#7578 Redirect to login page from Vue menu
  molgenis-core-ui/src/main/resources/js/bootstrap-4/menu/molgenis-menu.js
Labels: master

#7579 Fix #7571 Job overview won't work for editor
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/jobs/JobsController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/jobs/JobsControllerTest.java
Labels: master

#7572 Add page number to questionnaire overview report
  molgenis-questionnaires/src/main/frontend/src/services/questionnaireService.js
  molgenis-questionnaires/src/test/resources/emx-questionnaire.xls
Labels: 7.0.0-RC, master, mod:questionnaires

#7580 Superuser-only usage of mapping service II
  molgenis-app/src/main/java/org/molgenis/app/WebAppPermissionRegistry.java
  molgenis-app/src/test/java/org/molgenis/app/WebAppPermissionRegistryTest.java
Labels: master

#7593 Fix default permission allocations
  molgenis-app/src/main/java/org/molgenis/app/WebAppPermissionRegistry.java
  molgenis-app/src/test/java/org/molgenis/app/WebAppPermissionRegistryTest.java
Labels: master

#7596 Fix #7584 Data explorer copy button enabled for editor/viewer
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-dataexplorer/src/test/java/org/molgenis/dataexplorer/DataExplorerControllerTest.java
Labels: master

#7590 [DOC] Update import wizard documentation
  docs/images/upload/packages-screen.png
  docs/user_documentation/import-data/guide-upload.md
Labels: master

#7597 Make SORTA a superuser plugin by default
  docs/user_documentation/admin-features/guide-ref-security.md
  molgenis-app/src/main/java/org/molgenis/app/WebAppPermissionRegistry.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/MappingServiceImpl.java
Labels: master

#7594 Fix #7581 Editor can retrieve jobs for all users
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/oneclickimporter/OneClickImporterControllerAPIIT.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobConfig.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionConfig.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionUpdaterImpl.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutor.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutorTokenService.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutorTokenServiceImpl.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/JobExecutorTest.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/JobExecutorTokenServiceImplTest.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/model/hello/HelloWorldTest.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/job/OneClickImportJobExecutionMetadata.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/config/SecurityCoreITConfig.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
Labels: master

#7602 Fix #7582 Editor cannot update EMX data through import
  docs/images/upload/options-screen.png
  docs/user_documentation/import-data/guide-upload.md
  molgenis-amazon-bucket/src/main/java/org/molgenis/amazon/bucket/AmazonBucketIngester.java
  molgenis-amazon-bucket/src/test/java/org/molgenis/amazon/bucket/AmazonBucketIngesterTest.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ImportWizard.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardUtil.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPage.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/PackageWizardPage.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/UploadWizardPage.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ValidationResultWizardPage.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardControllerTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardUtilTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPageTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/PackageWizardPageTest.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/DataPersister.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportJob.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportService.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/MetadataAction.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxImportJob.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxImportService.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/ImportWriter.java
  molgenis-data-import/src/main/resources/templates/OptionsWizardPage.ftl
  molgenis-data-security/src/main/java/org/molgenis/data/security/PackagePermissionUtils.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/importer/VcfImporterService.java
  molgenis-data-vcf/src/test/java/org/molgenis/data/vcf/importer/VcfImporterServiceTest.java
  molgenis-data/src/main/java/org/molgenis/data/DataAction.java
  molgenis-file-ingester/src/main/java/org/molgenis/file/ingest/execution/FileIngester.java
  molgenis-file-ingester/src/test/java/org/molgenis/file/ingest/FileIngesterTest.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/importer/OntologyImportService.java
  molgenis-ontology/src/test/java/org/molgenis/ontology/importer/OntologyImportServiceTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/EmxImportServiceIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/OntologyImportServiceIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/VcfImportServiceIT.java
Labels: master

#7606 Fix #7601 Manager cannot delete data & metadata uploaded by self
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/AbstractRowLevelSecurityRepositoryDecorator.java
Labels: master

#7612 Fix delete button showing twice
  molgenis-dataexplorer/src/main/resources/js/dataexplorer.js
  molgenis-dataexplorer/src/main/resources/templates/view-dataexplorer.ftl
Labels: master

#7614 Add documentation for attribute field: visible
  docs/user_documentation/import-data/ref-emx.md
Labels: master

#7620 Fix #7616 Poor performance adding to row-level secured entity type
  molgenis-security/src/main/java/org/molgenis/security/acl/TransactionalJdbcMutableAclService.java
Labels: master
