Repository molgenis/molgenis, pull requests merged in 2018-11, with the labels that each got.

#7930 Fix #7929 Questionnaire tries range value if missing max or min prop …
  molgenis-questionnaires/src/main/frontend/src/store/getters.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/getters.spec.js
Labels: 7.2, mod:questionnaires

#7927 [FIX] Styling of questionnaire
  molgenis-questionnaires/src/main/frontend/src/components/ChapterForm.vue
  molgenis-questionnaires/src/main/frontend/src/components/QuestionnaireOverviewEntry.vue
  molgenis-questionnaires/src/main/frontend/src/pages/QuestionnaireChapter.vue
  molgenis-questionnaires/src/main/frontend/src/services/questionnaireService.js
Labels: 7.2, mod:questionnaires

#7926 Fix #7922: Python executor errors on windows
  molgenis-app/src/test/java/org/molgenis/python/PythonScriptExecutorTest.java
  molgenis-python/src/main/java/org/molgenis/python/PythonScriptExecutor.java
Labels: master, mod:python

#7939 Fix GitBook rendering of double curly braces in 'template expression'
  docs/user_documentation/import-data/ref-emx.md
Labels: master

#7938 Upgrade Spring Cairo-SR4 to Cairo-SR5
  pom.xml
Labels: master

#7943 [Fix] Make request body optional when updating entity.attribute via rest api
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerV1APIIT.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/RestController.java
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/RestControllerTest.java
Labels: 7.2

#7952 fix: Disable chapter navigation while validation is pending
  molgenis-questionnaires/src/main/frontend/src/components/ChapterNavigation.vue
Labels: 7.2, mod:questionnaires

#7911 chore(metrics): Relocate test classes to metrics module
  molgenis-metrics/pom.xml
  molgenis-metrics/src/test/java/org/molgenis/metrics/MetricsControllerTest.java
  molgenis-metrics/src/test/java/org/molgenis/metrics/MolgenisTimedAspectTest.java
Labels: master

#7957 Fix #7956 Job exceptions not logged
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutor.java
Labels: master

#7964 feat: Upgrade forms dependency for questionnaires
  molgenis-questionnaires/src/main/frontend/package.json
  molgenis-questionnaires/src/main/frontend/yarn.lock
Labels: 7.2

#7961 Fix #7960 SecurityUtils.getCurrentUsername refers to unknown User
  molgenis-app/src/main/java/org/molgenis/app/WebAppPermissionRegistry.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/MolgenisVersionService.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/Step35UpdateAclSystemSid.java
  molgenis-data-migrate/src/main/resources/step35-aclSystemSid.sql
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/RowLevelSecurityRepositoryDecorator.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/meta/AttributeRepositorySecurityDecoratorTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/config/SecurityCoreITConfig.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/MultipleAnnotationIT.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/SidUtils.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/runas/RunAsSystemAspect.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/runas/SystemSecurityToken.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/utils/SecurityUtils.java
  molgenis-security-core/src/test/java/org/molgenis/security/core/SidUtilsTest.java
  molgenis-security-core/src/test/java/org/molgenis/security/core/runas/RunAsSystemAspectTest.java
  molgenis-security-core/src/test/java/org/molgenis/security/core/runas/SystemSecurityTokenTest.java
  molgenis-security-core/src/test/java/org/molgenis/security/core/utils/SecurityUtilsTest.java
  molgenis-security/src/main/java/org/molgenis/security/acl/TransactionalJdbcMutableAclService.java
  molgenis-security/src/main/java/org/molgenis/security/permission/PermissionSystemServiceImpl.java
Labels: master

#7966 Refactoring: remove MetaDataUtils, move methods to EntityTypeUtils and PackageUtils
  molgenis-data-platform/src/main/java/org/molgenis/data/meta/system/SystemEntityTypePersister.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlRepositoryCollection.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/PackagePermissionUtils.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/EntityTypeValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/PackageValidator.java
  molgenis-data/src/main/java/org/molgenis/data/meta/MetaDataServiceImpl.java
  molgenis-data/src/main/java/org/molgenis/data/meta/PackageRepositoryDecorator.java
  molgenis-data/src/main/java/org/molgenis/data/util/EntityTypeUtils.java
  molgenis-data/src/main/java/org/molgenis/data/util/MetaUtils.java
  molgenis-data/src/main/java/org/molgenis/data/util/PackageUtils.java
  molgenis-data/src/test/java/org/molgenis/data/meta/MetaDataServiceImplTest.java
  molgenis-data/src/test/java/org/molgenis/data/meta/MetaUtilsTest.java
  molgenis-data/src/test/java/org/molgenis/data/support/EntityTypeUtilsTest.java
  molgenis-data/src/test/java/org/molgenis/data/util/PackageUtilsTest.java
  molgenis-searchall/src/main/java/org/molgenis/searchall/service/SearchAllService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
Labels: master

#7924 Merge 7.2 changes to master
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerV1APIIT.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/RestController.java
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/RestControllerTest.java
  molgenis-questionnaires/src/main/frontend/package.json
  molgenis-questionnaires/src/main/frontend/src/components/ChapterForm.vue
  molgenis-questionnaires/src/main/frontend/src/components/ChapterNavigation.vue
  molgenis-questionnaires/src/main/frontend/src/components/QuestionnaireOverviewEntry.vue
  molgenis-questionnaires/src/main/frontend/src/pages/QuestionnaireChapter.vue
  molgenis-questionnaires/src/main/frontend/src/services/questionnaireService.js
  molgenis-questionnaires/src/main/frontend/src/store/actions.js
  molgenis-questionnaires/src/main/frontend/src/store/getters.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/actions.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/getters.spec.js
  molgenis-questionnaires/src/main/frontend/yarn.lock
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/data/request/MappingServiceRequest.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/mapping/model/MappingProject.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/meta/MappingProjectMetaData.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/repository/impl/MappingProjectRepositoryImpl.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/AlgorithmService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/MappingService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImpl.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/MappingServiceImpl.java
  molgenis-semantic-mapper/src/main/resources/js/attribute-mapping.js
  molgenis-semantic-mapper/src/main/resources/templates/view-attribute-mapping.ftl
  molgenis-semantic-mapper/src/main/resources/templates/view-mapping-projects.ftl
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/MappingServiceControllerTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/repository/impl/MappingProjectRepositoryImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplIT.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/MappingServiceImplTest.java
Labels: master

#7950 Fix #7948 Job failure progress messages not coded
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppConfig.java
  molgenis-data-index/src/main/java/org/molgenis/data/index/job/IndexJobSchedulerImpl.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/user/UnknownUserException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/user/UserService.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/user/UserServiceImpl.java
  molgenis-data-security/src/main/resources/l10n/data-security_en.properties
  molgenis-data-security/src/main/resources/l10n/data-security_nl.properties
  molgenis-data-security/src/test/java/org/molgenis/data/security/user/UnknownUserExceptionTest.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobConfig.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionConfig.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionContext.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionContextFactory.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionContextFactoryImpl.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionHolder.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionTemplate.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionUpdaterImpl.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutor.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutorLocaleService.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutorLocaleServiceImpl.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutorTokenServiceImpl.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/NontransactionalJob.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/Progress.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/ProgressImpl.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/TransactionalJob.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/model/JobExecution.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/model/JobExecutionLogAppender.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/model/JobExecutionMetaData.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/model/ScheduledJob.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/JobExecutionTemplateTest.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/JobExecutorLocaleServiceImplTest.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/JobExecutorTest.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/JobExecutorTokenServiceImplTest.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/JobTest.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/ProgressImplTest.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/model/hello/HelloWorldConfig.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/model/hello/HelloWorldTest.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/controller/OneClickImporterController.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/SortaConfig.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/sorta/controller/SortaController.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/sorta/job/SortaJobFactory.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/sorta/job/SortaJobImpl.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/sorta/job/SortaJobProcessor.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptRunnerController.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/MappingServiceControllerTest.java
  molgenis-web/src/main/java/org/molgenis/web/i18n/FallbackLocaleSupplier.java
  molgenis-web/src/main/java/org/molgenis/web/i18n/FallbackLocaleSupplierImpl.java
  molgenis-web/src/main/java/org/molgenis/web/i18n/HttpLocaleResolver.java
  molgenis-web/src/main/java/org/molgenis/web/i18n/MolgenisLocaleResolver.java
  molgenis-web/src/main/java/org/molgenis/web/i18n/UserLocaleResolver.java
  molgenis-web/src/main/java/org/molgenis/web/i18n/UserLocaleResolverImpl.java
  molgenis-web/src/test/java/org/molgenis/web/i18n/FallbackLocaleSupplierImplTest.java
  molgenis-web/src/test/java/org/molgenis/web/i18n/HttpLocaleResolverTest.java
  molgenis-web/src/test/java/org/molgenis/web/i18n/MolgenisLocaleResolverTest.java
  molgenis-web/src/test/java/org/molgenis/web/i18n/UserLocaleResolverImplTest.java
Labels: master

#7970 Introduce ContextMessageSource
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportRunService.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/ImportRunServiceTest.java
  molgenis-i18n/src/main/java/org/molgenis/i18n/ContextMessageSource.java
  molgenis-i18n/src/main/java/org/molgenis/i18n/ContextMessageSourceImpl.java
  molgenis-i18n/src/test/java/org/molgenis/i18n/ContextMessageSourceImplTest.java
Labels: master

#7954 Refix #7922: Python executor errors on windows
  molgenis-python/src/main/java/org/molgenis/python/PythonScriptExecutor.java
  molgenis-python/src/test/python/PythonScriptExecutorTest.java
Labels: master

#7932 M6129: Add functions to submit mapping and script jobs and return the…
  docs/user_documentation/scripts/guide-scripts.md
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/jobs/JobsController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/jobs/JobsControllerTest.java
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptRunnerController.java
  molgenis-scripts/src/test/java/org/molgenis/script/ScriptRunnerControllerTest.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/MappingServiceControllerTest.java
Labels: master

#7974 M6254 Fix Sonar code smells
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/populate/SystemEntityPopulator.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/menu/json/MenuItem.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/StyleSheetRepositoryDecorator.java
  molgenis-data-i18n/src/main/java/org/molgenis/data/i18n/LanguageModificationException.java
  molgenis-data-i18n/src/main/java/org/molgenis/data/i18n/LanguageRepositoryDecorator.java
  molgenis-data-i18n/src/test/java/org/molgenis/data/i18n/LanguageRepositoryDecoratorTest.java
  molgenis-data-icd10/src/main/java/org/molgenis/data/icd10/CollectionsQueryTransformerImpl.java
  molgenis-data-icd10/src/main/java/org/molgenis/data/icd10/Icd10ExpanderDecoratorFactory.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/MolgenisUpgradeServiceImpl.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/Step35UpdateAclSystemSid.java
  molgenis-data-platform/src/main/java/org/molgenis/data/meta/system/SystemEntityTypePersister.java
  molgenis-data-rest-client/.gitignore
  molgenis-data-rest-client/README.md
  molgenis-data-rest-client/pom.xml
  molgenis-data-rest-client/src/main/java/org/molgenis/data/rest/client/MolgenisClient.java
  molgenis-data-rest-client/src/main/java/org/molgenis/data/rest/client/bean/LoginRequest.java
  molgenis-data-rest-client/src/main/java/org/molgenis/data/rest/client/bean/LoginResponse.java
  molgenis-data-rest-client/src/main/java/org/molgenis/data/rest/client/bean/MetaDataRequest.java
  molgenis-data-rest-client/src/main/java/org/molgenis/data/rest/client/bean/MetaDataResponse.java
  molgenis-data-rest-client/src/main/java/org/molgenis/data/rest/client/bean/QueryResponse.java
  molgenis-data-rest-client/src/test/java/org/molgenis/data/rest/client/MolgenisClientTest.java
  molgenis-data-rest-client/src/test/resources/logback-test.xml
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/importer/VcfImporterService.java
  molgenis-data/src/main/java/org/molgenis/data/EntityManagerImpl.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/settings/DataExplorerSettings.java
  molgenis-fair/src/main/java/org/molgenis/fair/controller/EntityModelWriter.java
  molgenis-file-ingester/src/main/java/org/molgenis/file/ingest/execution/FileIngestConfig.java
  molgenis-genomebrowser/src/main/java/org/molgenis/genomebrowser/meta/GenomeBrowserSettings.java
  molgenis-js/src/main/java/org/molgenis/js/magma/JsMagmaScriptExecutor.java
  molgenis-js/src/test/java/org/molgenis/js/magma/JsMagmaScriptExecutorTest.java
  molgenis-r/src/main/java/org/molgenis/r/RScriptExecutor.java
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptJobExecution.java
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptJobExecutionMetadata.java
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptPluginController.java
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptRunnerController.java
  molgenis-scripts/src/test/java/org/molgenis/script/ScriptRunnerControllerTest.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/runas/RunAsSystemAspect.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/config/MappingConfig.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/repository/impl/EntityMappingRepositoryImpl.java
  molgenis-settings/src/main/java/org/molgenis/settings/PropertyType.java
  molgenis-test/src/main/java/org/molgenis/test/AbstractMockitoTest.java
  molgenis-web/src/test/java/org/molgenis/web/bootstrap/PluginPopulatorTest.java
  molgenis-web/src/test/java/org/molgenis/web/rsql/MolgenisRSQLTest.java
  pom.xml
Labels: master

#7984 Refactor Integration test framework to support i18n and progress tests
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/populate/RepositoryPopulator.java
  molgenis-data-i18n/src/main/java/org/molgenis/data/i18n/I18nPopulator.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/DynamicDecoratorIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformBootstrapper.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/utils/TestProgress.java
Labels: feature/M6167_M6168_M6169-navigatorControls

#7987 Fix #7985 EntityType.newInstance doesn't copy indexing depth
  molgenis-data/src/main/java/org/molgenis/data/meta/model/EntityType.java
  molgenis-data/src/test/java/org/molgenis/data/meta/model/EntityTypeTest.java
Labels: master

#7986 Set Jenkins build stage thread count=4
  Jenkinsfile
Labels: master

#7975 Fix #7621 Plugin delete doesn't remove remove menu entries
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/service/impl/AppManagerServiceImpl.java
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/PluginRepositoryDecorator.java
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/PluginRepositoryDecoratorFactory.java
  molgenis-data-plugin/src/test/java/org/molgenis/data/plugin/model/PluginRepositoryDecoratorTest.java
Labels: master

#7996 Fix Sonar badge URL
  README.md
Labels: feature/M6167_M6168_M6169-navigatorControls

#7991 Add migration step for Updating AclSystemSid to MolgenisUpgradeBootst…
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/bootstrap/MolgenisUpgradeBootstrapper.java
Labels: master

#7998 Jenkinsfile: fix Sonar on feature branches (feature/....)
  Jenkinsfile
Labels: feature/M6167_M6168_M6169-navigatorControls

#8004 Fix #7956 again Job exceptions not logged
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutor.java
Labels: master

#8001 Fix README gitbook URL: https instead of http
  README.md
Labels: feature/M6167_M6168_M6169-navigatorControls

#8002 M6254 Fix Sonar code smells (IV)
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/browserdetection/BrowserDetectionFilter.java
  molgenis-core/src/main/java/org/molgenis/core/util/SchemaLoader.java
  molgenis-data/src/main/java/org/molgenis/data/mem/InMemoryRepository.java
  molgenis-platform-integration-tests/src/main/java/org/molgenis/integrationtest/data/TestAppSettings.java
  molgenis-security/src/main/java/org/molgenis/security/captcha/ReCaptchaHttpPostFactory.java
Labels: master
