Repository molgenis/molgenis, pull requests merged in 2018-02, with the labels that each got.

#7135 Upgrade apache poi to 3.17
  molgenis-data-excel/pom.xml
Labels: master

#7159 Fix errorcode / environment parameter order for fallback exceptionhandler
  molgenis-web/src/main/java/org/molgenis/web/exception/FallbackExceptionHandler.java
Labels: master

#7176 Refactor ImportWizardController test to resolve molgenis-report issue
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardControllerTest.java
Labels: master

#7172 Use transactional version of JdbcMutableAclService
  molgenis-security/src/main/java/org/molgenis/security/acl/TransactionalJdbcMutableAclService.java
  molgenis-security/src/main/java/org/springframework/security/acls/jdbc/AclConfig.java
Labels: master

#7174 Pom.xml fixes: duplicates and relocations
  molgenis-core-ui/pom.xml
  molgenis-data-rest/pom.xml
  molgenis-data-validation/pom.xml
  molgenis-dataexplorer/pom.xml
  molgenis-security/pom.xml
  molgenis-semantic-mapper/pom.xml
  molgenis-test/pom.xml
  molgenis-web/pom.xml
  pom.xml
Labels: master

#7168 M5634 Security: use default AnonymousAuthenticationFilter
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisAnonymousAuthenticationFilter.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-security/src/main/java/org/molgenis/security/acl/SidUtils.java
  molgenis-security/src/test/java/org/molgenis/security/MolgenisAnonymousAuthenticationFilterTest.java
  molgenis-security/src/test/java/org/molgenis/security/acl/SidUtilsTest.java
Labels: master

#7171 Bump version 6.1.0-SNAPSHOT to 7.0.0-SNAPSHOT
  molgenis-amazon-bucket/pom.xml
  molgenis-api-tests/pom.xml
  molgenis-app/pom.xml
  molgenis-apps/pom.xml
  molgenis-beacon/pom.xml
  molgenis-bootstrap/pom.xml
  molgenis-core-ui/package.json
  molgenis-core-ui/pom.xml
  molgenis-core/pom.xml
  molgenis-data-annotators/pom.xml
  molgenis-data-cache/pom.xml
  molgenis-data-csv/pom.xml
  molgenis-data-elasticsearch/pom.xml
  molgenis-data-excel/pom.xml
  molgenis-data-file/pom.xml
  molgenis-data-i18n/pom.xml
  molgenis-data-import/pom.xml
  molgenis-data-index/pom.xml
  molgenis-data-migrate/pom.xml
  molgenis-data-platform/pom.xml
  molgenis-data-plugin/pom.xml
  molgenis-data-postgresql/pom.xml
  molgenis-data-rest-client/pom.xml
  molgenis-data-rest/pom.xml
  molgenis-data-security/pom.xml
  molgenis-data-validation/pom.xml
  molgenis-data-vcf/pom.xml
  molgenis-data/pom.xml
  molgenis-dataexplorer/pom.xml
  molgenis-fair/pom.xml
  molgenis-file-ingester/pom.xml
  molgenis-gavin/pom.xml
  molgenis-genomebrowser/pom.xml
  molgenis-i18n/pom.xml
  molgenis-jobs/pom.xml
  molgenis-js/pom.xml
  molgenis-metadata-manager/pom.xml
  molgenis-navigator/pom.xml
  molgenis-one-click-importer/pom.xml
  molgenis-ontology-core/pom.xml
  molgenis-ontology/pom.xml
  molgenis-platform-integration-tests/pom.xml
  molgenis-python/pom.xml
  molgenis-questionnaires/pom.xml
  molgenis-r/pom.xml
  molgenis-scripts-core/pom.xml
  molgenis-scripts/pom.xml
  molgenis-searchall/pom.xml
  molgenis-security-core/pom.xml
  molgenis-security/pom.xml
  molgenis-semantic-mapper/pom.xml
  molgenis-semantic-search/pom.xml
  molgenis-settings-ui/pom.xml
  molgenis-settings/pom.xml
  molgenis-swagger/pom.xml
  molgenis-test/pom.xml
  molgenis-util/pom.xml
  molgenis-web/pom.xml
  pom.xml
Labels: master

#7179 Remove plugin permissions: writemeta, write, count
  molgenis-app/src/main/java/org/molgenis/app/WebAppPermissionRegistry.java
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/populate/PermissionRegistryImpl.java
  molgenis-bootstrap/src/test/java/org/molgenis/bootstrap/populate/PermissionRegistryImplTest.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/controller/StaticContentServiceImpl.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/permission/PermissionManagerControllerTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/controller/StaticContentServiceImplTest.java
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/PluginPermission.java
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/PluginPermissionUtils.java
  molgenis-security/src/main/java/org/molgenis/security/freemarker/PermissionDirective.java
  molgenis-security/src/main/java/org/molgenis/security/permission/Permissions.java
  molgenis-security/src/main/resources/js/permissionmanager.js
  molgenis-security/src/main/resources/templates/view-permissionmanager-plugin.ftl
  molgenis-security/src/test/java/org/molgenis/security/permission/UserPermissionEvaluatorImplTest.java
Labels: master

#7180 Resolve Mockito strictness warnings
  molgenis-data/src/test/java/org/molgenis/data/EntityReferenceResolverDecoratorTest.java
  molgenis-data/src/test/java/org/molgenis/data/meta/EntityTypeRepositoryDecoratorTest.java
  molgenis-data/src/test/java/org/molgenis/data/meta/MetaDataServiceImplTest.java
Labels: master

#7181 M5642: As Data manager I want package level repository permissions so that I can quickly assign multiple permissions
  docs/user_documentation/guide-admin.md
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/permission/PermissionManagerControllerTest.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/EntityTypeResponse.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/EntityTypeResponseV2.java
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/RestControllerTest.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/PackageIdentity.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/EntityTypeRepositorySecurityDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecorator.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecoratorTest.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/model/PackageRepositoryDecoratorFactory.java
  molgenis-data/src/test/java/org/molgenis/data/meta/MetaDataServiceImplTest.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/UserPermissionEvaluator.java
  molgenis-security/src/main/resources/js/permissionmanager.js
  molgenis-security/src/main/resources/templates/view-permissionmanager-package.ftl
  molgenis-security/src/main/resources/templates/view-permissionmanager.ftl
Labels: master

#7189 M5608 Row level security framework
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/MolgenisBootstrapper.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/permission/PermissionManagerControllerTest.java
  molgenis-data-platform/src/main/java/org/molgenis/data/platform/decorators/MolgenisRepositoryDecoratorFactory.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/EntityIdentity.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/acl/SidUtils.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/RowLevelSecuredFactory.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/RowLevelSecuredMetadata.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/RowLevelSecurityConfiguration.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/SecurityMetadataPackage.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/RowLevelSecurityConfigurationEntityDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/RowLevelSecurityRepositoryDecorator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/model/RowLevelSecurityRepositoryDecoratorFactory.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorRegistryImpl.java
  molgenis-data/src/main/java/org/molgenis/data/event/BootstrappingEvent.java
  molgenis-data/src/main/java/org/molgenis/data/event/BootstrappingEventPublisher.java
  molgenis-data/src/test/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorRegistryImplTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java
  molgenis-security/src/main/resources/js/permissionmanager.js
  molgenis-security/src/main/resources/templates/view-permissionmanager-entity.ftl
  molgenis-security/src/main/resources/templates/view-permissionmanager.ftl
Labels: feature/row-level-security, work in progress

#7190 M5608 Row level security framework: small refactorings
  molgenis-data-platform/src/main/java/org/molgenis/data/platform/decorators/MolgenisRepositoryDecoratorFactory.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/RowLevelSecurityRepositoryDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/RowLevelSecurityRepositoryDecoratorFactory.java
Labels: feature/row-level-security

#7197 M5608 Row-level security: remove for abstract entity types
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/EntityTypeRlsRequest.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/EntityTypeRlsResponse.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-questionnaires/src/main/java/org/molgenis/questionnaires/QuestionnaireMetaData.java
Labels: feature/row-level-security

#7198 M5608 Row-level security: Fix class visibility issues
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/EntityTypeRlsRequest.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/EntityTypeRlsResponse.java
Labels: feature/row-level-security

#7200 M5608 Row-level security: revert bootstrapping changes
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/MolgenisBootstrapper.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorRegistryImpl.java
  molgenis-data/src/main/java/org/molgenis/data/event/BootstrappingEvent.java
  molgenis-data/src/main/java/org/molgenis/data/event/BootstrappingEventPublisher.java
  molgenis-data/src/test/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorRegistryImplTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java
Labels: feature/row-level-security

#7201 M5608 Row-level security: replace owner check with ACE
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/EntityIdentity.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/acl/SidUtils.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/SecurityMetadataPackage.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/RowLevelSecurityRepositoryDecorator.java
  molgenis-security/src/main/java/org/molgenis/security/permission/UserPermissionEvaluatorImpl.java
  molgenis-security/src/test/java/org/molgenis/security/permission/UserPermissionEvaluatorImplTest.java
Labels: feature/row-level-security

#7202 M5608 Row-level security: disallow system entity type RLS modification
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/EntityTypeRlsResponse.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/permission/PermissionManagerControllerTest.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/EntityIdentity.java
  molgenis-security/src/main/resources/templates/view-permissionmanager-entity.ftl
Labels: feature/row-level-security

#7203 Use ObjectIdentityPrimaryKeyQuery with cast to resolve integer identifier issue
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/permission/PermissionManagerControllerTest.java
  molgenis-security/src/main/java/org/springframework/security/acls/jdbc/AclConfig.java
Labels: feature/row-level-security
