Repository molgenis/molgenis, pull requests merged in 2018-12, with the labels that each got.

#7940 Resource Copy Service
  molgenis-data-rest/pom.xml
  molgenis-data/src/main/java/org/molgenis/data/AbstractEntityDecorator.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/EntityType.java
  molgenis-data/src/test/java/org/molgenis/data/AbstractEntityDecoratorTest.java
  molgenis-data/src/test/java/org/molgenis/data/EntityTestHarness.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/CopyResourceRequest.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/exception/CopyFailedException.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/exception/RecursiveCopyException.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/exception/UnknownCopyFailedException.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/job/ResourceCopyJobConfig.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/job/ResourceCopyJobExecution.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/job/ResourceCopyJobExecutionFactory.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/job/ResourceCopyJobExecutionMetadata.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/CopyService.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/CopyServiceImpl.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/CopyState.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/EntityTypeCopier.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/EntityTypeMetadataCopier.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/LabelGenerator.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/PackageCopier.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/PretendingEntity.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/RelationTransformer.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/util/ResourceCollector.java
  molgenis-navigator/src/main/resources/l10n/navigator_en.properties
  molgenis-navigator/src/main/resources/l10n/navigator_nl.properties
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/exception/RecursiveCopyExceptionTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/exception/UnknownCopyExceptionTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/job/ResourceCopyJobExecutionTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/service/CopyServiceImplTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/service/CopyTestUtils.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/service/EntityTypeCopierTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/service/EntityTypeMetadataCopierTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/service/LabelGeneratorTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/service/PackageCopierTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/service/PretendingEntityTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/service/RelationTransformerTest.java
  molgenis-platform-integration-tests/pom.xml
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/CopyServiceIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/OneToManyIT.java
Labels: feature/M6167_M6168_M6169-navigatorControls

#8010 chore(Jenkinsfile): Run sonar analysis on feature branches
  Jenkinsfile
Labels: feature/M6167_M6168_M6169-navigatorControls

#8011 chore(Jenkinsfile): Run sonar analysis on release branches
  Jenkinsfile
Labels: 7.3.0

#8015 [FIX] #7956 Job exceptions not logged
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutor.java
Labels: 7.3.0

#8020 [CHORE] upgrade preview server using rancher client instead of helm
  Jenkinsfile
Labels: 7.3

#8024 [CHORE] added chart version to Jenkinsfile
  Jenkinsfile
Labels: 7.3

#8027 [CHORE] use production profile for release builds
  Jenkinsfile
Labels: 7.3

#8025 [CHORE] Stash rancher config file so molgenis-it pod can …
  Jenkinsfile
Labels: 7.3

#8030 chore(metrics): Remove duplicate dependency
  molgenis-metrics/pom.xml
Labels: master

#8031 chore: No longer run findbugs analysis
  .travis.yml
  molgenis-data-cache/pom.xml
  molgenis-data-icd10/pom.xml
  molgenis-data/pom.xml
  molgenis-data/src/main/java/org/molgenis/data/DataConverter.java
  molgenis-i18n/pom.xml
  molgenis-util/pom.xml
  molgenis-util/src/main/java/org/molgenis/util/ApplicationContextProvider.java
  molgenis-validation/pom.xml
  molgenis-validation/src/main/java/org/molgenis/validation/JsonValidationException.java
  pom.xml
Labels: master

#8034 Document download
  docs/images/navigator/navigator-download.png
  docs/user_documentation/finding-data/guide-navigator.md
Labels: feature/M6167_M6168_M6169-navigatorControls

#8038 Add copy documentation
  docs/images/navigator/navigator-copy-diagram.png
  docs/images/navigator/navigator-copy.png
  docs/user_documentation/finding-data/guide-navigator.md
Labels: feature/M6167_M6168_M6169-navigatorControls

#8040 Permission population of introduced permissions
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/MolgenisBootstrapper.java
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/populate/PermissionPopulator.java
  molgenis-bootstrap/src/test/java/org/molgenis/bootstrap/MolgenisBootstrapperTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/RunAsSystemPermissionService.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/PermissionService.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/PermissionServiceImpl.java
  molgenis-security-core/src/test/java/org/molgenis/security/core/PermissionServiceImplTest.java
Labels: master

#8021 Fix EntityTypeMapper: Empty values should be null rather than empty String
  molgenis-data-import/src/main/java/org/molgenis/data/export/mapper/EntityTypeMapper.java
  molgenis-data-import/src/test/java/org/molgenis/data/export/EntityTypeMapperTest.java
Labels: feature/M6167_M6168_M6169-navigatorControls

#8045 Fix read-only resource selection issue
  molgenis-navigator/src/main/frontend/src/components/NavigatorActionsCreateEdit.vue
Labels: feature/M6167_M6168_M6169-navigatorControls

#8042 Fix #8041 PostgreSql translated exceptions can be too vague
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlExceptionTranslator.java
  molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/PostgreSqlExceptionTranslatorTest.java
Labels: master

#8036 Fix #8028 Computed values should not be validated
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/EntityAttributesValidator.java
Labels: master

#8049 Navigator controls: fix package and entity type deduplication
  molgenis-data-import/src/main/java/org/molgenis/data/export/EmxExportServiceImpl.java
  molgenis-data-import/src/test/java/org/molgenis/data/export/EmxExportServiceImplTest.java
Labels: feature/M6167_M6168_M6169-navigatorControls

#8050 Navigator controls: add entity type deduplication when copying
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/EntityTypeCopier.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/service/EntityTypeCopierTest.java
Labels: feature/M6167_M6168_M6169-navigatorControls

#8026 M6254 Fix Sonar code smells (V)
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/XmlMolgenisUiLoader.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/StyleController.java
  molgenis-data-csv/src/main/java/org/molgenis/data/csv/CsvIterator.java
  molgenis-data-csv/src/main/java/org/molgenis/data/csv/CsvRepositoryCollection.java
  molgenis-data-csv/src/test/java/org/molgenis/data/csv/CsvRepositoryCollectionTest.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/FileStore.java
  molgenis-web/src/main/java/org/molgenis/web/converter/CsvHttpMessageConverter.java
  molgenis-web/src/test/java/org/molgenis/web/converter/CsvHttpMessageConverterTest.java
Labels: master

#8048 Fix: Packages that do not have a FQN name should not be downloaded as EMX
  molgenis-data-import/src/main/java/org/molgenis/data/export/EmxExportServiceImpl.java
  molgenis-data-import/src/main/java/org/molgenis/data/export/exception/InvalidEmxIdentifierException.java
  molgenis-data-import/src/main/resources/l10n/data-import_en.properties
  molgenis-data-import/src/main/resources/l10n/data-import_nl.properties
  molgenis-data-import/src/test/java/org/molgenis/data/export/EmxExportServiceImplTest.java
  molgenis-data-import/src/test/java/org/molgenis/data/export/exception/InvalidEmxIdentifierExceptionTest.java
Labels: feature/M6167_M6168_M6169-navigatorControls

#8056 M6256 Navigator delete action performed in job
  molgenis-app/src/main/java/org/molgenis/app/WebAppPermissionRegistry.java
  molgenis-navigator/src/main/frontend/src/flow.types.js
  molgenis-navigator/src/main/frontend/src/store/actions.js
  molgenis-navigator/src/main/frontend/src/utils/api.js
  molgenis-navigator/src/main/frontend/test/unit/specs/store/actions.spec.js
  molgenis-navigator/src/main/frontend/test/unit/specs/utils/api.spec.js
  molgenis-navigator/src/main/java/org/molgenis/navigator/DeleteResourcesRequest.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/NavigatorController.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/NavigatorService.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/NavigatorServiceImpl.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/job/ResourceCopyJobConfig.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/delete/ResourceDeleteService.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/delete/ResourceDeleteServiceImpl.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/delete/job/ResourceDeleteJobExecution.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/delete/job/ResourceDeleteJobExecutionFactory.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/delete/job/ResourceDeleteJobExecutionJobFactory.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/delete/job/ResourceDeleteJobExecutionMetadata.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/download/job/ResourceDownloadConfig.java
  molgenis-navigator/src/main/resources/l10n/navigator_en.properties
  molgenis-navigator/src/main/resources/l10n/navigator_nl.properties
  molgenis-navigator/src/test/java/org/molgenis/navigator/NavigatorServiceImplTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/delete/ResourceDeleteServiceImplTest.java
Labels: master

#8059 Add Navigator docs to table of contents
  docs/SUMMARY.md
Labels: master

#8055 Upgrade Spring Cairo-SR5 to Cairo-SR6
  pom.xml
Labels: 7.4

#8057 Fix #7908 StackOverflowError when moving a package to its child
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/PackageValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/meta/PackageValidatorTest.java
Labels: 7.4

#8061 book.json: add 7.3 and 7.4
  book.json
Labels: master

#8063 Update pom.xml: 7.4.0-SNAPSHOT to 7.5.0-SNAPSHOT
  molgenis-amazon-bucket/pom.xml
  molgenis-api-tests/pom.xml
  molgenis-app-manager/pom.xml
  molgenis-app/pom.xml
  molgenis-beacon/pom.xml
  molgenis-bootstrap/pom.xml
  molgenis-core-ui/pom.xml
  molgenis-core/pom.xml
  molgenis-data-cache/pom.xml
  molgenis-data-csv/pom.xml
  molgenis-data-elasticsearch/pom.xml
  molgenis-data-excel/pom.xml
  molgenis-data-file/pom.xml
  molgenis-data-i18n/pom.xml
  molgenis-data-icd10/pom.xml
  molgenis-data-import/pom.xml
  molgenis-data-index/pom.xml
  molgenis-data-migrate/pom.xml
  molgenis-data-platform/pom.xml
  molgenis-data-plugin/pom.xml
  molgenis-data-postgresql/pom.xml
  molgenis-data-rest/pom.xml
  molgenis-data-row-edit/pom.xml
  molgenis-data-security/pom.xml
  molgenis-data-validation/pom.xml
  molgenis-data-vcf/pom.xml
  molgenis-data/pom.xml
  molgenis-dataexplorer/pom.xml
  molgenis-fair/pom.xml
  molgenis-file-ingester/pom.xml
  molgenis-genomebrowser/pom.xml
  molgenis-i18n/pom.xml
  molgenis-jobs/pom.xml
  molgenis-js/pom.xml
  molgenis-metadata-manager/pom.xml
  molgenis-metrics/pom.xml
  molgenis-navigator/pom.xml
  molgenis-one-click-importer/pom.xml
  molgenis-ontology-core/pom.xml
  molgenis-ontology/pom.xml
  molgenis-platform-integration-tests/pom.xml
  molgenis-python/pom.xml
  molgenis-questionnaires/pom.xml
  molgenis-r/pom.xml
  molgenis-scripts-core/pom.xml
  molgenis-scripts/pom.xml
  molgenis-searchall/pom.xml
  molgenis-security-core/pom.xml
  molgenis-security-ui/pom.xml
  molgenis-security/pom.xml
  molgenis-semantic-mapper/pom.xml
  molgenis-semantic-search/pom.xml
  molgenis-settings-ui/pom.xml
  molgenis-settings/pom.xml
  molgenis-swagger/pom.xml
  molgenis-test/pom.xml
  molgenis-util/pom.xml
  molgenis-validation/pom.xml
  molgenis-web/pom.xml
  pom.xml
Labels: master

#8008 Add sentry java client lib, sentry-logback lib
  molgenis-app/pom.xml
  molgenis-app/src/main/resources/logback.xml
  pom.xml
Labels: master

#8066 chore(merge back): all changes from master and 7.3 back to 7.4
  Jenkinsfile
  molgenis-app/pom.xml
  molgenis-app/src/main/resources/logback.xml
  molgenis-ontology/src/main/java/org/molgenis/ontology/utils/SortaServiceUtil.java
  molgenis-ontology/src/test/java/org/molgenis/ontology/utils/SortaServiceUtilTest.java
  pom.xml
Labels: 7.4

#8067 M6314: Add FeatureInfoPlugin to GenomeBrowser config and make "genome…
  docs/user_documentation/finding-data/guide-explore.md
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-genomebrowser/src/main/java/org/molgenis/genomebrowser/GenomeBrowserTrack.java
  molgenis-genomebrowser/src/main/java/org/molgenis/genomebrowser/meta/GenomeBrowserSettings.java
  molgenis-genomebrowser/src/main/java/org/molgenis/genomebrowser/meta/GenomeBrowserSettingsMetadata.java
  molgenis-genomebrowser/src/main/java/org/molgenis/genomebrowser/service/GenomeBrowserService.java
  molgenis-genomebrowser/src/test/java/org/molgenis/genomebrowser/GenomeBrowserTrackTest.java
  molgenis-genomebrowser/src/test/java/org/molgenis/genomebrowser/service/GenomeBrowserServiceTest.java
Labels: 7.4

#8069 Add minimal application config for Sentry
  molgenis-app/src/main/resources/sentry.properties
Labels: 7.4

#8075 Fix #8051 #8053 Mapping project add source 500 error
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/repository/AttributeMappingRepository.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/repository/impl/AttributeMappingRepositoryImpl.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/repository/impl/AttributeMappingRepositoryImplTest.java
Labels: master

#8065 Fix #8058 CSV header value mismatch (values > headers)
  molgenis-data-csv/src/main/java/org/molgenis/data/csv/CsvIterator.java
  molgenis-data-csv/src/test/java/org/molgenis/data/csv/CsvIteratorTest.java
  molgenis-data-csv/src/test/resources/testdatamissingvalue3.csv
Labels: master

#8077 Fix #7886 JobExecution entity delete allowed for running job
  molgenis-data-platform/src/main/java/org/molgenis/data/platform/decorators/SystemRepositoryDecoratorRegistryImpl.java
  molgenis-data-platform/src/test/java/org/molgenis/data/platform/decorators/SystemRepositoryDecoratorRegistryImplTest.java
  molgenis-jobs/pom.xml
  molgenis-jobs/src/main/java/org/molgenis/jobs/ActiveJobExecutionDeleteForbiddenException.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobsL10nConfig.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/model/JobExecutionRepositoryDecorator.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/model/JobExecutionRepositoryDecoratorFactory.java
  molgenis-jobs/src/main/resources/l10n/jobs_en.properties
  molgenis-jobs/src/main/resources/l10n/jobs_nl.properties
  molgenis-jobs/src/test/java/org/molgenis/jobs/ActiveJobExecutionDeleteForbiddenExceptionTest.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/model/JobExecutionRepositoryDecoratorTest.java
Labels: master

#8081 Remove meterbinders wiring, just start with empty list
  molgenis-metrics/src/main/java/org/molgenis/metrics/MetricsConfig.java
Labels: master

#8082 File store error handling improvements
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/controller/AppController.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/service/impl/AppManagerServiceImpl.java
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/controller/AppControllerTest.java
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/service/impl/AppManagerServiceImplTest.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/LogoController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/file/FileDownloadController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/StyleServiceImpl.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/style/StyleServiceTest.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/FileStore.java
  molgenis-data-file/src/test/java/org/molgenis/data/file/FileStoreTest.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/download/job/ResourceDownloadService.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/download/job/DownloadServiceTest.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/job/OneClickImportJob.java
  molgenis-one-click-importer/src/test/java/org/molgenis/oneclickimporter/job/OneClickImportJobTest.java
  molgenis-scripts/src/main/java/org/molgenis/script/SavedScriptRunner.java
Labels: master

#8091 Remove and disallow duplicate beans
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppConfig.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppInitializer.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxImportService.java
  molgenis-data-index/src/main/java/org/molgenis/data/index/job/IndexJobService.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/DatabaseConfig.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionConfig.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobsL10nConfig.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/SortaConfig.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/AlgorithmTemplateServiceImpl.java
Labels: master

#8090 Fix #8088 Data or jobs exception messages not localized
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobsL10nConfig.java
Labels: master

#8094 Fix #8093 Navigator localized dutch string encoding issue
  molgenis-navigator/src/main/resources/l10n/navigator_nl.properties
Labels: master
