Repository molgenis/molgenis, pull requests merged in 2018-06, with the labels that each got.

#7397 Fix #6489 Unable to proxy interface log warnings
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppConfig.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/converter/RdfConverter.java
Labels: master

#7400 Fix #7199 Mapping service: do not map to target expressed attribute
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/algorithmgenerator/service/impl/AlgorithmGeneratorServiceImpl.java
  molgenis-semantic-mapper/src/main/resources/templates/view-single-mapping-project.ftl
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/algorithmgenerator/service/impl/AlgorithmGeneratorServiceImplTest.java
Labels: master

#7363 Update documentation for User and Permission manager
  docs/images/permission_manager.png
  docs/images/user_manager.png
  docs/user_documentation/guide-admin.md
Labels: feature/group-model

#7403 Fix #7335 Metadata manager: error creating file attribute
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerAttributeEditForm.vue
Labels: master

#7410 Remove unused code: EntityValidator & DefaultEntityValidator
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/DefaultEntityValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/EntityAttributesValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/EntityValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/AttributeValidator.java
Labels: master

#7407 Fix sonar warnings in recently touched code
  README.md
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/controller/AppManagerController.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/service/AppManagerService.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/service/impl/AppManagerServiceImpl.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/AppDataRootInitializer.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/MolgenisVersionService.java
  molgenis-data-migrate/src/test/java/org/molgenis/data/migrate/version/MolgenisVersionServiceTest.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/User.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/UserMetaData.java
  molgenis-security/src/main/java/org/molgenis/security/account/AccountController.java
  molgenis-util/src/main/java/org/molgenis/util/AppDataRootProvider.java
  pom.xml
Labels: master

#7421 Test App entity getters and setters
  molgenis-app-manager/pom.xml
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/meta/AppTest.java
Labels: master

#7420 Add findbugs analysis
  .travis.yml
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ValidationResultWizardPage.java
  pom.xml
Labels: master

#7428 Update version numbers of required tools
  docs/quickstart/guide-tomcat.md
Labels: master

#7433 Explain that ImportPublicDataIT should not be run locally
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/importpublicdata/ImportPublicDataIT.java
Labels: master

#7404 Fix #7402 Upgrade jQuery and Moment.js
  molgenis-core-ui/package.json
  molgenis-core-ui/src/main/javascript/modules/react-components/Popover.js
  molgenis-core-ui/src/main/javascript/molgenis-vendor-webpack.js
  molgenis-core-ui/src/main/resources/js/logmanager.js
  molgenis-core-ui/src/main/resources/js/molgenis-form-list.js
  molgenis-core-ui/src/main/resources/js/moment-with-locales.min.js
  molgenis-security/src/main/resources/templates/view-2fa-imports.ftl
  molgenis-semantic-mapper/src/main/resources/js/attribute-mapping.js
Labels: master

#7422 Remove dependency on zip4j
  molgenis-app-manager/pom.xml
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/controller/AppController.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/controller/AppManagerController.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/exception/InvalidAppArchiveException.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/service/AppManagerService.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/service/impl/AppManagerServiceImpl.java
  molgenis-app-manager/src/main/resources/l10n/app-manager_en.properties
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/service/AppManagerServiceTest.java
  molgenis-app-manager/src/test/resources/flip.zip
  molgenis-data-file/pom.xml
  molgenis-data-file/src/main/java/org/molgenis/data/file/CodedUnzipException.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/FileConfig.java
  molgenis-data-file/src/main/resources/l10n/file_en.properties
  molgenis-data-file/src/test/java/org/molgenis/data/file/CodedUnzipExceptionTest.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/job/OneClickImportJob.java
  molgenis-ontology-core/pom.xml
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/importer/repository/OntologyRepositoryCollection.java
  molgenis-util/pom.xml
  molgenis-util/src/main/java/org/molgenis/util/file/UnzipException.java
  molgenis-util/src/main/java/org/molgenis/util/file/ZipFileUtil.java
  molgenis-util/src/test/java/org/molgenis/util/file/ZipFileUtilTest.java
  molgenis-util/src/test/resources/org/molgenis/util/file/emx-csv.zip
  molgenis-util/src/test/resources/org/molgenis/util/file/flip.zip
  molgenis-util/src/test/resources/org/molgenis/util/file/test.zip
  pom.xml
Labels: master

#7444 Suppress false positive sonar warning.
  molgenis-settings/src/main/java/org/molgenis/settings/mail/MailSettingsImpl.java
Labels: master

#7413 M5843 Import package selection
  molgenis-amazon-bucket/src/main/java/org/molgenis/amazon/bucket/AmazonBucketIngester.java
  molgenis-amazon-bucket/src/test/java/org/molgenis/amazon/bucket/AmazonBucketIngesterTest.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/oneclickimporter/OneClickImporterControllerAPIIT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerV1APIIT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v2/RestControllerV2IT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/utils/RestTestUtils.java
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/populate/PermissionRegistryImpl.java
  molgenis-bootstrap/src/test/java/org/molgenis/bootstrap/populate/PermissionRegistryImplTest.java
  molgenis-core-ui/pom.xml
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ImportWizard.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardUtil.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPage.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardControllerTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardUtilTest.java
  molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/core/entity/impl/gavin/GavinAnnotator.java
  molgenis-data-annotators/src/main/java/org/molgenis/data/annotation/core/resources/impl/emx/InMemoryRepositoryFactory.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportService.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/MetaDataParser.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxDataProvider.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxImportJob.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxImportService.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetaDataParser.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/ImporterConfiguration.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/IntermediateParseResults.java
  molgenis-data-import/src/main/resources/templates/PackageWizardPage.ftl
  molgenis-data-import/src/test/java/org/molgenis/data/importer/emx/EmxDataProviderTest.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/emx/IntermediateParseResultsTest.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/NoWritablePackageException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/PackagePermissionUtils.java
  molgenis-data-security/src/main/resources/l10n/data-security_en.properties
  molgenis-data-security/src/test/java/org/molgenis/data/security/PackagePermissionUtilsTest.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/importer/VcfImporterService.java
  molgenis-data-vcf/src/test/java/org/molgenis/data/vcf/importer/VcfImporterServiceTest.java
  molgenis-data/src/main/java/org/molgenis/data/meta/DefaultPackage.java
  molgenis-data/src/main/java/org/molgenis/data/meta/UploadPackage.java
  molgenis-data/src/test/java/org/molgenis/data/support/EntityTypeUtilsTest.java
  molgenis-file-ingester/src/main/java/org/molgenis/file/ingest/execution/FileIngester.java
  molgenis-file-ingester/src/test/java/org/molgenis/file/ingest/FileIngesterTest.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/impl/EntityServiceImpl.java
  molgenis-one-click-importer/src/test/java/org/molgenis/oneclickimporter/service/EntityServiceImplTest.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/importer/OntologyImportService.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/config/MetaTestConfig.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/EmxImportServiceIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/OntologyImportServiceIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/importservice/VcfImportServiceIT.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/config/MappingConfig.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/MappingServiceImpl.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/repository/impl/AttributeMappingRepositoryImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/repository/impl/EntityMappingRepositoryImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/repository/impl/MappingTargetRepositoryImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/MappingServiceImplTest.java
Labels: master

#7442 Fix #7438: 2FA pincode entry does not acquire focus
  molgenis-security/src/main/resources/templates/view-2fa-activation-modal.ftl
  molgenis-security/src/main/resources/templates/view-2fa-configured-modal.ftl
Labels: master

#7446 Fix #3507 Fix #5571 Fix #7435 Remove ontology manager plugin
  molgenis-app/src/main/resources/molgenis_ui.xml
  molgenis-ontology/pom.xml
  molgenis-ontology/src/main/java/org/molgenis/ontology/controller/OntologyManagerController.java
  molgenis-ontology/src/main/resources/css/ontology-indexer.css
  molgenis-ontology/src/main/resources/js/ontology-manager.js
  molgenis-ontology/src/main/resources/templates/ontology-manager-view.ftl
Labels: master

#7450 Remove disease matcher icon
  molgenis-dataexplorer/src/main/resources/img/diseasematcher-icon.png
Labels: master

#7424 Fix #6418 #7248 #7360 Label attribute fixes
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/utils/RestTestUtils.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportRunMetaData.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetaDataParser.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/IntermediateParseResults.java
  molgenis-data-index/src/main/java/org/molgenis/data/index/meta/IndexActionMetaData.java
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/v2/RestControllerV2Test.java
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourceCollectionResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourceCollectionResponseIncludingCategories.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourcePartialSubAttributeResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourcePartialSubAttributesResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourcePartialSubSubAttributesResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourceResponse.json
  molgenis-data-rest/src/test/resources/org/molgenis/data/rest/v2/resourceResponseIncludingCategories.json
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/MembershipInvitationMetadata.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMembershipMetadata.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/RepositoryValidationDecorator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/EntityTypeValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/meta/EntityTypeValidatorTest.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/format/VcfToEntity.java
  molgenis-data-vcf/src/test/java/org/molgenis/data/vcf/format/VcfToEntityTest.java
  molgenis-data/src/main/java/org/molgenis/data/decorator/meta/DecoratorConfigurationMetadata.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/Attribute.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/EntityType.java
  molgenis-data/src/test/java/org/molgenis/data/meta/model/AttributeTest.java
  molgenis-data/src/test/java/org/molgenis/data/meta/model/EntityTypeTest.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/model/ScheduledJobTypeMetadata.java
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerEntityEditForm.vue
  molgenis-metadata-manager/src/main/frontend/src/store/getters.js
  molgenis-metadata-manager/src/main/frontend/src/store/mutations.js
  molgenis-metadata-manager/src/main/frontend/test/unit/specs/mutations.spec.js
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/EntityTypeMapper.java
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_en.properties
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_nl.properties
  molgenis-metadata-manager/src/test/java/org/molgenis/metadata/manager/mapper/AttributeMapperTest.java
  molgenis-metadata-manager/src/test/java/org/molgenis/metadata/manager/mapper/EntityTypeMapperTest.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/sorta/repo/SortaCsvRepository.java
  molgenis-security/src/main/java/org/molgenis/security/twofactor/model/RecoveryCodeMetadata.java
  molgenis-security/src/main/java/org/molgenis/security/twofactor/model/UserSecretMetaData.java
Labels: master

#7451 Fix #7448 Can not upload bio-bank data model
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPage.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPageTest.java
Labels: master

#7453 Fix Sonar Warnings
  molgenis-data-excel/src/main/java/org/molgenis/data/excel/ExcelRepositoryCollection.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/VcfReaderFactory.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/VcfReaderFactoryImpl.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/VcfRepository.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/importer/VcfImporterService.java
  molgenis-data-vcf/src/test/java/org/molgenis/data/vcf/VcfRepositoryTest.java
Labels: master

#7445 Feature/questionnaire pdf
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/controller/VuePluginController.java
  molgenis-questionnaires/src/main/frontend/config/dev-responses/localized-messages.js
  molgenis-questionnaires/src/main/frontend/config/dev-responses/questionnaire-list.js
  molgenis-questionnaires/src/main/frontend/config/index.js
  molgenis-questionnaires/src/main/frontend/package.json
  molgenis-questionnaires/src/main/frontend/src/flow.types.js
  molgenis-questionnaires/src/main/frontend/src/pages/QuestionnaireOverview.vue
  molgenis-questionnaires/src/main/frontend/src/pages/QuestionnaireStart.vue
  molgenis-questionnaires/src/main/frontend/src/services/questionnaireService.js
  molgenis-questionnaires/src/main/frontend/src/store/actions.js
  molgenis-questionnaires/src/main/frontend/src/store/getters.js
  molgenis-questionnaires/src/main/frontend/src/store/mutations.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/components/QuestionnaireOverview.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/components/QuestionnaireStart.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/services/questionnaireService.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/actions.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/getters.spec.js
  molgenis-questionnaires/src/main/frontend/yarn.lock
  molgenis-questionnaires/src/main/java/org/molgenis/questionnaires/controller/QuestionnaireController.java
  molgenis-questionnaires/src/main/java/org/molgenis/questionnaires/service/QuestionnaireService.java
  molgenis-questionnaires/src/main/java/org/molgenis/questionnaires/service/impl/QuestionnaireServiceImpl.java
  molgenis-questionnaires/src/main/resources/l10n/questionnaire_en.properties
  molgenis-questionnaires/src/test/java/org/molgenis/questionnaires/controller/QuestionnaireControllerTest.java
  molgenis-questionnaires/src/test/java/org/molgenis/questionnaires/service/QuestionnaireServiceTest.java
Labels: mod:questionnaires, work in progress

#7464 Sonar: String literals should not be duplicated
  molgenis-beacon/src/main/java/org/molgenis/beacon/config/BeaconMetadata.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/controller/AbstractStaticContentController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/controller/FeedbackController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/converter/RDFMediaType.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/system/core/FreemarkerTemplateMetaData.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/StyleSheetMetadata.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/wizard/Wizard.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryGenerator.java
  molgenis-data-i18n/src/main/java/org/molgenis/data/i18n/model/LanguageMetadata.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetaDataParser.java
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/PluginMetadata.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlExceptionTranslator.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlUtils.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/TokenMetaData.java
  molgenis-data/src/main/java/org/molgenis/data/QueryRule.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/AttributeMetadata.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/PackageMetadata.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/meta/OntologyMetaData.java
  molgenis-scripts-core/src/main/java/org/molgenis/script/core/ScriptMetaData.java
Labels: master

#7460 Upgrade Spring Cairo-SR1 to Cairo-SR2
  pom.xml
Labels: master

#7473 Fix #7463 Questionnaire permission error message not internationalized
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/QueryValidator.java
Labels: master

#7475 Fix #7474 Metadata manager one-to-many attribute creation not possible
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerAttributeEditForm.vue
Labels: master

#7470 Fix #7468: One click importer cannot import data
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/impl/EntityServiceImpl.java
Labels: master

#7477 Fix #7434 Test resource concurrency issues
  molgenis-data-csv/src/test/java/org/molgenis/data/csv/CsvIteratorTest.java
  molgenis-data-csv/src/test/java/org/molgenis/data/csv/CsvRepositorySourceTest.java
  molgenis-data-csv/src/test/java/org/molgenis/data/csv/CsvRepositoryTest.java
  molgenis-data-csv/src/test/resources/testdatamissingvalue.csv
  molgenis-data-csv/src/test/resources/testdatamissingvalue2.csv
  molgenis-data-vcf/src/test/java/org/molgenis/data/vcf/VcfRepositoryTest.java
Labels: master

#7483 Fix #7431: Leftover plugin when deleting active app
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/controller/AppManagerController.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/decorator/AppRepositoryDecorator.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/decorator/AppsRepositoryDecoratorFactory.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/service/AppManagerService.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/service/impl/AppManagerServiceImpl.java
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/controller/AppManagerControllerTest.java
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/decorator/AppRepositoryDecoratorTest.java
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/service/AppManagerServiceTest.java
Labels: master

#7485 Fix #7406: IE11 input wizard file select broken
  molgenis-core/src/main/java/org/molgenis/core/util/FileUploadUtils.java
  molgenis-core/src/test/java/org/molgenis/core/util/FileUploadUtilsTest.java
Labels: master

#7458 Add standard roles
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerIT.java
  molgenis-app/src/main/java/org/molgenis/app/WebAppPermissionRegistry.java
  molgenis-app/src/main/java/org/molgenis/app/WebAppSecurityConfig.java
  molgenis-app/src/test/java/org/molgenis/app/WebAppPermissionRegistryTest.java
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/populate/PermissionRegistryImpl.java
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/populate/UsersRolesPopulatorImpl.java
  molgenis-bootstrap/src/test/java/org/molgenis/bootstrap/populate/PermissionRegistryImplTest.java
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/PluginIdentity.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/DataserviceRoleHierarchy.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/EntityTypeIdentity.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/PackageIdentity.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/GroupService.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/Role.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMetadata.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/DataserviceRoleHierarchyTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/GroupServiceTest.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/NegotiatorController.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/config/NegotiatorPackage.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/job/OneClickImportJobExecutionMetadata.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/SidUtils.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisRoleHierarchy.java
  molgenis-security/src/main/java/org/molgenis/security/account/AccountService.java
  molgenis-security/src/test/java/org/molgenis/security/MolgenisRoleHierarchyTest.java
  molgenis-security/src/test/java/org/molgenis/security/account/AccountServiceImplTest.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/job/MappingJobExecutionMetadata.java
Labels: master

#7454 Add endpoint to retrieve PermissionSets.
  molgenis-core-ui/pom.xml
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionResponse.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionSetResponse.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/permission/PermissionManagerControllerTest.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/PermissionRegistry.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/PermissionSet.java
  molgenis-security-core/src/test/java/org/molgenis/security/core/PermissionRegistryTest.java
Labels: master

#7486 Fix #7480: Can not open the downloaded questionnaire directly from br…
  molgenis-questionnaires/src/main/frontend/src/services/questionnaireService.js
Labels: master

#7484 Fix #7432 #7429 App manager fixes
  docs/developer_documentation/app-development.md
  docs/user_documentation/guide-app-manager.md
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/controller/AppController.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/controller/AppManagerController.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/exception/IllegalAppNameException.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/meta/App.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/meta/AppMetadata.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/model/AppConfig.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/model/AppResponse.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/service/AppManagerService.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/service/impl/AppManagerServiceImpl.java
  molgenis-app-manager/src/main/resources/l10n/app-manager_en.properties
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/controller/AppControllerTest.java
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/controller/AppManagerControllerTest.java
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/meta/AppTest.java
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/service/AppManagerServiceTest.java
  molgenis-app-manager/src/test/resources/config.json
  molgenis-app-manager/src/test/resources/missing-index.zip
  molgenis-app-manager/src/test/resources/valid-app.zip
  molgenis-app-manager/src/test/resources/valid-no-runtime-app.zip
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisMenuController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/MolgenisMenuControllerTest.java
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/Plugin.java
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/PluginMetadata.java
  molgenis-data/src/main/java/org/molgenis/data/UnknownDataException.java
  molgenis-data/src/main/java/org/molgenis/data/UnknownPluginException.java
  molgenis-data/src/main/resources/l10n/data_en.properties
  molgenis-data/src/main/resources/l10n/data_nl.properties
  molgenis-web/src/main/java/org/molgenis/web/PluginController.java
  molgenis-web/src/main/java/org/molgenis/web/bootstrap/PluginPopulator.java
  molgenis-web/src/test/java/org/molgenis/web/bootstrap/PluginPopulatorTest.java
Labels: master
