Repository molgenis/molgenis, pull requests merged in 2018-09, with the labels that each got.

#7744 [CHORE] Update package.json version
  molgenis-core-ui/package.json
Labels: master

#7737 Fix/7728 set to initial state on empty query
  molgenis-navigator/src/main/frontend/index.html
  molgenis-navigator/src/main/frontend/package.json
  molgenis-navigator/src/main/frontend/src/components/Navigator.vue
  molgenis-navigator/src/main/frontend/src/store/actions.js
  molgenis-navigator/src/main/frontend/test/unit/specs/components/Navigator.spec.js
  molgenis-navigator/src/main/frontend/test/unit/specs/store/actions.spec.js
  molgenis-navigator/src/main/frontend/yarn.lock
Labels: master, mod:navigator

#7754 M6050 Navigator: delete selected items
  molgenis-navigator/src/main/frontend/config/index.js
  molgenis-navigator/src/main/frontend/src/components/Navigator.vue
  molgenis-navigator/src/main/frontend/src/flow.types.js
  molgenis-navigator/src/main/frontend/src/store/actions.js
  molgenis-navigator/src/main/frontend/src/store/mutations.js
  molgenis-navigator/src/main/frontend/src/store/state.js
  molgenis-navigator/src/main/frontend/test/unit/specs/components/Navigator.spec.js
  molgenis-navigator/src/main/frontend/test/unit/specs/store/actions.spec.js
  molgenis-navigator/src/main/frontend/test/unit/specs/store/mutations.spec.js
  molgenis-navigator/src/main/java/org/molgenis/navigator/DeleteItemsRequest.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/NavigatorController.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/NavigatorService.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/NavigatorServiceImpl.java
  molgenis-navigator/src/main/resources/l10n/navigator_en.properties
  molgenis-navigator/src/main/resources/l10n/navigator_nl.properties
  molgenis-navigator/src/test/java/org/molgenis/navigator/NavigatorControllerTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/NavigatorServiceImplTest.java
Labels: master

#7760 Add 7.1 to book.json
  book.json
Labels: master

#7757 Fix #7752 Computed MREF attribute display error in entity report
  molgenis-data/src/main/java/org/molgenis/data/DataConverter.java
  molgenis-data/src/test/java/org/molgenis/data/DataConverterTest.java
Labels: master

#7761 Fix #7755 Group manager can't handle usernames-with-dot
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppConfig.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/file/FileDownloadController.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/RestController.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/RestControllerV2.java
Labels: master

#7764 Fix #7734 Data explorer anonymous issue (revert)
  molgenis-data/src/main/java/org/molgenis/data/util/MetaUtils.java
Labels: master

#7767 Fix #7766 Metadata manager nullable expression update unsupported
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerAttributeEditForm.vue
  molgenis-metadata-manager/src/main/frontend/src/flow.types.js
  molgenis-metadata-manager/src/main/frontend/src/store/actions.js
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/AttributeMapper.java
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_en.properties
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_nl.properties
  molgenis-metadata-manager/src/test/java/org/molgenis/metadata/manager/mapper/AttributeMapperTest.java
Labels: master

#7781 Fix #7663 Sign up impossible because captcha isn't showing
  molgenis-security/src/main/resources/templates/register-modal.ftl
Labels: master

#7784 Fix #6553 Inactive user can reset and change password
  molgenis-security/src/main/java/org/molgenis/security/account/AccountServiceImpl.java
  molgenis-security/src/test/java/org/molgenis/security/account/AccountServiceImplTest.java
Labels: master

#7779 Fix #7412 Data explorer entered-data lost on click outside of modal
  molgenis-core-ui/src/main/javascript/modules/react-components/Modal.js
Labels: master

#7772 Fix #7771 Metadata manager doesn't allow default value update
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerAttributeEditForm.vue
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_en.properties
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_nl.properties
Labels: master

#7778 Fix #7687 EMX documentation: file datatype broken link
  docs/user_documentation/import-data/ref-emx.md
Labels: master

#7763 Fix #7739 Import fails on EMX update with one-to-many attributes
  molgenis-data-import/src/main/java/org/molgenis/data/importer/DataPersisterImpl.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportI18nConfig.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportRunService.java
  molgenis-data-import/src/main/resources/l10n/data-import_en.properties
  molgenis-data-import/src/main/resources/l10n/data-import_nl.properties
  molgenis-data-import/src/test/java/org/molgenis/data/importer/DataPersisterImplTest.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/ImportRunServiceTest.java
Labels: master

#7777 Fix #7713 One-to-many attribute readonly update fails
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlRepositoryCollection.java
  molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/PostgreSqlRepositoryCollectionTest.java
Labels: master

#7769 Fix #6869 Metadata manager attribute tree render issue
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerAttributeEditForm.vue
Labels: master

#7789 Fix 7.1 documentation link
  book.json
Labels: 7.1

#7795 Fix/7793 update example emx example date fix
  docs/data/simple_data_example_v20160915.xlsx
  docs/data/simple_data_example_v20180912.xlsx
  docs/user_documentation/import-data/ref-emx.md
Labels: documentation, master

#7776 Fix #7630 Metadata manager cascade delete support
  molgenis-data/src/main/java/org/molgenis/data/util/EntityUtils.java
  molgenis-data/src/test/java/org/molgenis/data/util/EntityUtilsTest.java
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerAttributeEditForm.vue
  molgenis-metadata-manager/src/main/frontend/src/flow.types.js
  molgenis-metadata-manager/src/main/frontend/src/store/actions.js
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/AttributeMapper.java
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/model/EditorAttribute.java
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_en.properties
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_nl.properties
  molgenis-metadata-manager/src/test/java/org/molgenis/metadata/manager/controller/MetadataManagerControllerTest.java
  molgenis-metadata-manager/src/test/java/org/molgenis/metadata/manager/mapper/AttributeMapperTest.java
Labels: master

#7774 Fix #7676 Metadata manager undo-all-changes option
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerContainer.vue
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerEntityEditForm.vue
  molgenis-metadata-manager/src/main/frontend/src/store/actions.js
  molgenis-metadata-manager/src/main/frontend/src/store/mutations.js
  molgenis-metadata-manager/src/main/frontend/test/unit/specs/actions.spec.js
  molgenis-metadata-manager/src/main/frontend/test/unit/specs/mutations.spec.js
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_en.properties
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_nl.properties
Labels: master

#7799 Use generateForm create/update mode
  molgenis-data-row-edit/src/main/frontend/package.json
  molgenis-data-row-edit/src/main/frontend/src/components/DataRowEdit.vue
  molgenis-data-row-edit/src/main/frontend/test/unit/specs/components/DataRowEdit.spec.js
  molgenis-data-row-edit/src/main/frontend/yarn.lock
Labels: master, mod:data-row-edit

#7770 Fix #6928 Attribute.idAttribute update shouldn't be allowed
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/AttributeValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/meta/AttributeValidatorTest.java
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerEntityEditForm.vue
Labels: master

#7786 Refactor: various code improvements
  molgenis-app/src/main/java/org/molgenis/app/WebAppSecurityConfig.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/DataPersisterImpl.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/DataPersisterImplTest.java
  molgenis-data-platform/src/main/java/org/molgenis/data/platform/config/PlatformConfig.java
  molgenis-data/src/main/java/org/molgenis/data/DataConverter.java
  molgenis-data/src/main/java/org/molgenis/data/config/DataConfig.java
  molgenis-data/src/main/java/org/molgenis/data/meta/EntityTypeWithoutMappedByAttributes.java
  molgenis-data/src/main/java/org/molgenis/data/meta/MetaDataServiceImpl.java
  molgenis-data/src/main/java/org/molgenis/data/meta/package-info.java
  molgenis-data/src/test/java/org/molgenis/data/DataConverterTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/config/MetaTestConfig.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformIT.java
  molgenis-security/src/test/java/org/molgenis/security/twofactor/service/RecoveryServiceImplTest.java
  molgenis-security/src/test/java/org/molgenis/security/twofactor/service/TwoFactorAuthenticationServiceImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/repository/impl/EntityMappingRepositoryImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/repository/impl/MappingTargetRepositoryImplTest.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/repository/TagRepository.java
Labels: master

#7787 Refactor: replace deprecated with coded exceptions
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/RestController.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/RestControllerV2.java
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/v2/RestControllerV2Test.java
  molgenis-data/src/main/java/org/molgenis/data/DuplicateEntityException.java
  molgenis-data/src/main/java/org/molgenis/data/MolgenisReferencedEntityException.java
  molgenis-data/src/main/java/org/molgenis/data/MolgenisRepositoryCapabilitiesException.java
  molgenis-data/src/main/java/org/molgenis/data/RepositoryAlreadyExistsException.java
  molgenis-data/src/main/java/org/molgenis/data/RepositoryNotCapableException.java
  molgenis-data/src/main/resources/l10n/data_en.properties
  molgenis-data/src/main/resources/l10n/data_nl.properties
  molgenis-data/src/test/java/org/molgenis/data/RepositoryAlreadyExistsExceptionTest.java
  molgenis-data/src/test/java/org/molgenis/data/RepositoryNotCapableExceptionTest.java
Labels: master

#7803 Fix #7789 EntityUtils.equals doesn't compare i18n labels/descriptions
  molgenis-data/src/main/java/org/molgenis/data/util/EntityUtils.java
  molgenis-data/src/test/java/org/molgenis/data/util/EntityUtilsTest.java
Labels: master

#7805 Upgrade Spring Cairo-SR3 to Cairo-SR4
  pom.xml
Labels: master

#7806 Fix #7766 Metadata manager nullable expression en-placeholder
  molgenis-metadata-manager/src/main/resources/l10n/metadata-manager_en.properties
Labels: master

#7807 M6050 Fix: I18n delete confirmation dialog button texts
  molgenis-navigator/src/main/frontend/src/components/Navigator.vue
  molgenis-navigator/src/main/resources/l10n/navigator_en.properties
  molgenis-navigator/src/main/resources/l10n/navigator_nl.properties
Labels: master

#7802 Fix #7792 Metadata manager cannot add/update localized fields
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerAttributeEditForm.vue
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerEntityEditForm.vue
  molgenis-metadata-manager/src/main/frontend/src/flow.types.js
  molgenis-metadata-manager/src/main/frontend/src/store/actions.js
  molgenis-metadata-manager/src/main/frontend/src/store/mutations.js
  molgenis-metadata-manager/src/main/frontend/src/store/state.js
  molgenis-metadata-manager/src/main/frontend/test/unit/specs/actions.spec.js
  molgenis-metadata-manager/src/main/frontend/test/unit/specs/mutations.spec.js
Labels: master

#7794 MetadataService NPE improvements
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardController.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxImportService.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetaDataParser.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/ImportWriter.java
  molgenis-data-index/src/test/java/org/molgenis/data/index/job/IndexJobServiceTest.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/importer/VcfImporterService.java
  molgenis-data-vcf/src/test/java/org/molgenis/data/vcf/importer/VcfImporterServiceTest.java
  molgenis-data/src/main/java/org/molgenis/data/meta/MetaDataService.java
  molgenis-data/src/main/java/org/molgenis/data/meta/MetaDataServiceImpl.java
  molgenis-data/src/main/java/org/molgenis/data/support/DataServiceImpl.java
  molgenis-data/src/test/java/org/molgenis/data/meta/MetaDataServiceImplTest.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/service/MetadataManagerServiceImpl.java
  molgenis-metadata-manager/src/test/java/org/molgenis/metadata/manager/service/MetadataManagerServiceTest.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/impl/EntityServiceImpl.java
  molgenis-one-click-importer/src/test/java/org/molgenis/oneclickimporter/service/EntityServiceImplTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/IndexMetadataCUDOperationsPlatformIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/MetaDataServiceIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformIT.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/MappingServiceImpl.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/MappingServiceControllerTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/MappingServiceImplTest.java
Labels: master

#7753 M6042: As DM / Chr6 we need a feature to assign existing questionnaires to the users
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/OwnershipDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/owned/OwnershipDecoratorFactory.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/owned/OwnershipDecoratorTest.java
Labels: master

#7810 Fix 7809 Disable vuex strict node in production
  molgenis-app-manager/src/main/frontend/src/store/index.js
  molgenis-metadata-manager/src/main/frontend/src/store/index.js
  molgenis-navigator/src/main/frontend/src/store/index.js
  molgenis-one-click-importer/src/main/frontend/src/store/index.js
  molgenis-questionnaires/src/main/frontend/src/store/index.js
  molgenis-security-ui/src/main/frontend/src/store/index.js
Labels: master, vue, vuex

#7817 M6119: As Manager I want to be able to manage users without having th…
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/usermanager/UserManagerServiceImpl.java
Labels: master

#7819 [DOC] Fix instructions for running in docker on windows
  molgenis-app/DOCKER.md
Labels: master

#7816 M6114 OpenID connect authentication, runtime configurable
  docs/images/security/authentication/authentication_settings_oidc.png
  docs/images/security/authentication/signin_dialog_oidc.png
  docs/user_documentation/admin-features/security/guide-authentication.md
  molgenis-app/src/main/java/org/molgenis/app/WebAppSecurityConfig.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisInterceptor.java
  molgenis-core-ui/src/main/resources/css/molgenis.css
  molgenis-core-ui/src/main/resources/js/bootstrap-4/menu/molgenis-menu.js
  molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl
  molgenis-data-security/src/main/java/org/molgenis/data/security/DataserviceRoleHierarchy.java
  molgenis-data/src/main/java/org/molgenis/data/listeners/EntityListenersService.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/MappedAuthenticatedPrincipal.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/utils/SecurityUtils.java
  molgenis-security/pom.xml
  molgenis-security/src/main/java/org/molgenis/security/MolgenisChangePasswordFilter.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-security/src/main/java/org/molgenis/security/google/GoogleAuthenticationProcessingFilter.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/DataServiceClientRegistrationRepository.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/MappedOidcUser.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/MappedOidcUserService.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/OidcUserEmailVerificationException.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/OidcUserMapper.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/OidcUserMapperImpl.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/OidcUserMissingEmailException.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/ResettableOAuth2AuthorizedClientService.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/model/OidcClient.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/model/OidcClientFactory.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/model/OidcClientMetadata.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/model/OidcClientRepositoryDecorator.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/model/OidcClientRepositoryDecoratorFactory.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/model/OidcPackage.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/model/OidcUserMapping.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/model/OidcUserMappingFactory.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/model/OidcUserMappingMetadata.java
  molgenis-security/src/main/java/org/molgenis/security/settings/AuthenticationSettings.java
  molgenis-security/src/main/java/org/molgenis/security/settings/AuthenticationSettingsImpl.java
  molgenis-security/src/main/resources/templates/login-modal.ftl
  molgenis-security/src/main/resources/templates/view-login.ftl
  molgenis-security/src/test/java/org/molgenis/security/google/GoogleAuthenticationProcessingFilterTest.java
  molgenis-security/src/test/java/org/molgenis/security/oidc/DataServiceClientRegistrationRepositoryTest.java
  molgenis-security/src/test/java/org/molgenis/security/oidc/MappedOidcUserServiceTest.java
  molgenis-security/src/test/java/org/molgenis/security/oidc/OidcUserEmailVerificationExceptionTest.java
  molgenis-security/src/test/java/org/molgenis/security/oidc/OidcUserMapperImplTest.java
  molgenis-security/src/test/java/org/molgenis/security/oidc/OidcUserMissingEmailExceptionTest.java
  molgenis-security/src/test/java/org/molgenis/security/oidc/ResettableOAuth2AuthorizedClientServiceTest.java
  molgenis-security/src/test/java/org/molgenis/security/oidc/model/OidcClientRepositoryDecoratorTest.java
  molgenis-security/src/test/java/org/molgenis/security/settings/AuthenticationSettingsImplTest.java
  molgenis-settings/src/main/java/org/molgenis/settings/DefaultSettingsEntity.java
  molgenis-web/src/main/java/org/molgenis/web/PluginAttributes.java
Labels: master

#7823 Fix #7820 Updating readonly attribute type fails
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlRepositoryCollection.java
  molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/PostgreSqlRepositoryCollectionTest.java
Labels: master

#7827 doc (intellij.md): Fix link to style xml
  docs/developer_documentation/intellij.md
Labels: master

#7818 Fix #5252 Logging out removes query parameters in URL
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisMenuController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/MolgenisMenuControllerTest.java
Labels: master

#7825 Fix #7814 Metadata manager reference to no-reference type update
  molgenis-metadata-manager/src/main/frontend/src/store/mutations.js
  molgenis-metadata-manager/src/main/frontend/test/unit/specs/mutations.spec.js
Labels: master

#7826 Fix #6516 Mail settings username/password are required
  molgenis-util/src/main/java/org/molgenis/util/mail/JavaMailSenderFactory.java
  molgenis-util/src/test/java/org/molgenis/util/mail/JavaMailSenderFactoryTest.java
Labels: master

#7822 Fix #7821 show non visible attributes in data row edit
  molgenis-data-row-edit/src/main/frontend/package.json
  molgenis-data-row-edit/src/main/frontend/src/components/DataRowEdit.vue
  molgenis-data-row-edit/src/main/frontend/yarn.lock
Labels: master, mod:data-row-edit, mod:forms

#7830 [CHORE] Update helm chart image keys to match the new chart version
  Jenkinsfile
Labels: master

#7833 [CHORE] Update helm repo to point at new chart
  Jenkinsfile
Labels: master

#7838 [STYLE] Fix eslint issues logged at build time
  molgenis-metadata-manager/src/main/frontend/src/store/actions.js
  molgenis-metadata-manager/src/main/frontend/src/store/mutations.js
  molgenis-metadata-manager/src/main/frontend/test/unit/specs/actions.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/services/questionnaireService.spec.js
Labels: master

#7841 [CHORE] Upgrade testdouble in modules that warn about it at build time
  molgenis-app-manager/src/main/frontend/package.json
  molgenis-app-manager/src/main/frontend/yarn.lock
  molgenis-data-row-edit/src/main/frontend/package.json
  molgenis-data-row-edit/src/main/frontend/yarn.lock
  molgenis-questionnaires/src/main/frontend/package.json
  molgenis-questionnaires/src/main/frontend/yarn.lock
Labels: master

#7836 chore(Jenkinsfile): Update helm repo
  Jenkinsfile
Labels: master, work in progress

#7832 Fix #7831 Mapping service plugin broken when project is broken
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/repository/AttributeMappingRepository.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/repository/impl/AttributeMappingRepositoryImpl.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/repository/impl/EntityMappingRepositoryImpl.java
  molgenis-semantic-mapper/src/main/resources/templates/view-mapping-projects.ftl
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/repository/impl/AttributeMappingRepositoryImplTest.java
Labels: master

#7834 [CHORE] Implement new flow for the jenkins pipeline
  .release/generate_release_properties.bash
  Jenkinsfile
  molgenis-app/pom.xml
Labels: master

#7856 Fix #7849 #7853 Button styling issues
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerAttributeEditForm.vue
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerEntityEditForm.vue
  molgenis-navigator/src/main/frontend/src/components/Navigator.vue
  molgenis-security-ui/src/main/frontend/src/components/GroupDetail.vue
Labels: master
