Repository molgenis/molgenis, pull requests merged in 2018-05, with the labels that each got.

#7342 Fix #2691 Infinite EMX import for EMX with deep nested formulas
  molgenis-data-excel/src/main/java/org/molgenis/data/excel/ExcelUtils.java
Labels: master

#7323 Speed up javascript and magmascript evaluation
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/ExpressionValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/ExpressionValidatorTest.java
  molgenis-js/pom.xml
  molgenis-js/src/main/java/org/molgenis/js/magma/JsMagmaScriptEvaluator.java
  molgenis-js/src/main/java/org/molgenis/js/nashorn/NashornScriptEngine.java
  molgenis-js/src/main/resources/js/script-evaluator.js
  molgenis-js/src/test/java/org/molgenis/js/JsMagmaScriptEvaluatorTest.java
  molgenis-js/src/test/java/org/molgenis/js/nashorn/NashornScriptEngineTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplIT.java
Labels: master

#7328 Backport M5472 Specify how reference attributes are mapped
  docs/user_documentation/ref-expressions.md
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/ExpressionValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/NameValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/ExpressionValidatorTest.java
  molgenis-js/pom.xml
  molgenis-js/src/main/java/org/molgenis/js/magma/JsMagmaScriptEvaluator.java
  molgenis-js/src/main/java/org/molgenis/js/nashorn/NashornScriptEngine.java
  molgenis-js/src/main/resources/js/script-evaluator.js
  molgenis-js/src/test/java/org/molgenis/js/JsMagmaScriptEvaluatorTest.java
  molgenis-js/src/test/java/org/molgenis/js/nashorn/NashornScriptEngineTest.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/repository/impl/AttributeMappingRepositoryImpl.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImpl.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/repository/impl/AttributeMappingRepositoryImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplIT.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplTest.java
Labels: 6.1

#7345 Upgrade guava to 25.0
  pom.xml
Labels: master

#7348 Feature/action permissions
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-core-ui/src/main/javascript/modules/react-components/Table.js
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/EntityTypeResponse.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/EntityTypeResponseV2.java
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/RestControllerTest.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/exception/EntityPermissionDeniedException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/exception/EntityTypePermissionDeniedException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/exception/PackagePermissionDeniedException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/EntityTypeRepositorySecurityDecorator.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/PermissionRegistry.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/UserPermissionEvaluator.java
  molgenis-security/src/main/java/org/molgenis/security/freemarker/PermissionDirective.java
  molgenis-security/src/main/java/org/molgenis/security/meta/Action.java
  molgenis-security/src/main/java/org/molgenis/security/meta/ActionFactory.java
  molgenis-security/src/main/java/org/molgenis/security/meta/ActionMetadata.java
  molgenis-security/src/main/java/org/molgenis/security/meta/ActionPermissionMapping.java
  molgenis-security/src/main/java/org/molgenis/security/meta/ActionPermissionMappingFactory.java
  molgenis-security/src/main/java/org/molgenis/security/meta/ActionPermissionMappingMetadata.java
  molgenis-security/src/main/java/org/molgenis/security/meta/Permission.java
  molgenis-security/src/main/java/org/molgenis/security/meta/PermissionFactory.java
  molgenis-security/src/main/java/org/molgenis/security/meta/PermissionMetadata.java
  molgenis-security/src/main/java/org/molgenis/security/permission/MolgenisPermissionController.java
  molgenis-security/src/main/java/org/molgenis/security/permission/PermissionSystemServiceImpl.java
  molgenis-security/src/main/java/org/molgenis/security/permission/UserPermissionEvaluatorImpl.java
  molgenis-security/src/test/java/org/molgenis/security/freemarker/HasPermissionDirectiveTest.java
  molgenis-security/src/test/java/org/molgenis/security/permission/MolgenisPermissionControllerTest.java
  molgenis-security/src/test/java/org/molgenis/security/permission/UserPermissionEvaluatorImplTest.java
Labels: feature/actionPermissions

#7355 Fix "null" in stacktrace for PackagePermissionDeniedException
  molgenis-data-security/src/main/java/org/molgenis/data/security/exception/PackagePermissionDeniedException.java
Labels: feature/actionPermissions

#7358 Upgrade platform-bom from Cairo-RELEASE to Cairo-SR1
  pom.xml
Labels: master

#7367 Use label instead of id's
  molgenis-questionnaires/src/main/frontend/src/components/ChapterNavigation.vue
  molgenis-questionnaires/src/main/frontend/src/flow.types.js
  molgenis-questionnaires/src/main/frontend/src/pages/QuestionnaireChapter.vue
  molgenis-questionnaires/src/main/frontend/src/store/getters.js
  molgenis-questionnaires/src/main/frontend/src/store/index.js
  molgenis-questionnaires/src/main/frontend/src/store/mutations.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/components/ChapterNavigation.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/components/QuestionnaireChapter.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/getters.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/mutations.spec.js
Labels: mod:questionnaires

#7352 [FIX] Questionnaire autosave validation
  molgenis-questionnaires/src/main/frontend/src/components/ChapterForm.vue
  molgenis-questionnaires/src/main/frontend/src/store/actions.js
  molgenis-questionnaires/src/main/frontend/test/e2e/specs/questionnaire-walkthrough.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/components/ChapterForm.spec.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/actions.spec.js
Labels: 7.0.0-RC, mod:questionnaires

#7362 Exclude compile scope annotation dependencies from guava
  pom.xml
Labels: master

#7364 EMX metadata parser: validate that compound parent is not itself
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetaDataParser.java
Labels: master

#7376 Resolve Findbugs false-positive: use Java 8 stream
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/security/MolgenisUiMenuPermissionDecorator.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/security/MolgenisUiMenuPermissionDecoratorTest.java
Labels: master

#7371 Add null check for compiled expression (should never be null)
  molgenis-js/src/main/java/org/molgenis/js/nashorn/NashornScriptEngine.java
Labels: master

#7375 Fix magma script issues.
  docs/user_documentation/ref-expressions.md
  molgenis-js/src/main/resources/js/math.min.js
  molgenis-js/src/main/resources/js/script-evaluator.js
  molgenis-js/src/test/java/org/molgenis/js/JsMagmaScriptEvaluatorTest.java
Labels: master

#7384 Move MagmaScript.js to its own npm module
  molgenis-js/pom.xml
  molgenis-js/src/main/java/org/molgenis/js/magma/JsMagmaScriptEvaluator.java
  molgenis-js/src/main/resources/js/math.min.js
  molgenis-js/src/main/resources/js/script-evaluator.js
  molgenis-js/src/test/java/org/molgenis/js/JsMagmaScriptEvaluatorTest.java
Labels: master

#7383 Backport 'value() function shouldn't look up idValue' to 6.1
  docs/user_documentation/ref-expressions.md
  molgenis-js/src/main/resources/js/script-evaluator.js
  molgenis-js/src/test/java/org/molgenis/js/JsMagmaScriptEvaluatorTest.java
Labels: 6.1

#7391 Add PluginPermissionDeniedException
  molgenis-data-plugin/pom.xml
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/PluginPermissionConfig.java
  molgenis-data-plugin/src/main/java/org/molgenis/data/plugin/model/PluginPermissionDeniedException.java
  molgenis-data-plugin/src/main/resources/l10n/data-plugin_en.properties
  molgenis-data-plugin/src/test/java/org/molgenis/data/plugin/model/PluginPermissionDeniedExceptionTest.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/exception/PermissionDeniedException.java
Labels: master
