Repository molgenis/molgenis, pull requests merged in 2018-10, with the labels that each got.

#7865 Fix #7447: If i click "enable 2fa" but do not finish the form I'm stuck on "/2fa/activation"
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/user/UserAccountController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/user/UserAccountControllerTest.java
  molgenis-security/src/main/java/org/molgenis/security/twofactor/TwoFactorAuthenticationController.java
  molgenis-security/src/test/java/org/molgenis/security/twofactor/TwoFactorAuthenticationControllerTest.java
Labels: master

#7868 chore: Backport pipeline changes
  .release/generate_release_properties.bash
  Jenkinsfile
  molgenis-app/pom.xml
Labels: 7.2

#7869 [CHORE] Fix integration test during x.x build
  Jenkinsfile
  molgenis-core-ui/gulpfile.js
  molgenis-core-ui/package.json
  molgenis-core-ui/pom.xml
Labels: 7.2

#7863 Fix #7862 Ontology-deletion non-practical
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/bootstrap/MolgenisUpgradeBootstrapper.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/MolgenisVersionService.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/Step33UpdateForeignKeyDeferred.java
  molgenis-data-migrate/src/main/resources/2582.sql
  molgenis-data-migrate/src/main/resources/step33-deferredForeignKeys.sql
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlQueryGenerator.java
  molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/PostgreSqlQueryGeneratorTest.java
  molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/PostgreSqlRepositoryCollectionTest.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/meta/OntologyMetaData.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/meta/OntologyTermMetaData.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformBootstrapper.java
Labels: master

#7872 fix (app): Use correct war file name to include in the docker image.
  Jenkinsfile
  molgenis-app/pom.xml
Labels: 7.2

#7876 Fix Sonar warnings
  molgenis-ontology/src/main/java/org/molgenis/ontology/roc/InformationContentService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/UnitResolverImpl.java
Labels: master

#7879 [FIX] Fix #7877 Console.log in metadata manager code
  molgenis-metadata-manager/src/main/frontend/src/components/MetadataManagerEntityEditForm.vue
Labels: master

#7884 Fix Sonar warnings
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryGenerator.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetaDataParser.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlQueryGenerator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/aggregation/AnonymizedAggregateResult.java
  molgenis-python/src/main/java/org/molgenis/python/PythonScriptExecutor.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/explain/service/ElasticSearchExplainServiceImpl.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/explain/service/ExplainServiceHelper.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/service/impl/SemanticSearchServiceImpl.java
Labels: master

#7887 [FIX] trailing slash to serve apps
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisMenuController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/MolgenisMenuControllerTest.java
Labels: 7.2

#7888 [CHORE] Fix [x.x] release flow
  Jenkinsfile
  pom.xml
Labels: 7.2

#7891 [CHORE] Backport x.x build fixes from 7.2 to master
  Jenkinsfile
  molgenis-app/pom.xml
  molgenis-core-ui/gulpfile.js
  molgenis-core-ui/package.json
  molgenis-core-ui/pom.xml
  pom.xml
Labels: master

#7890 Sonar: "null" should not be used with "Optional"
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l1/L1Cache.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l1/L1CacheRepositoryDecorator.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/utils/CacheHit.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/utils/CombinedEntityCache.java
  molgenis-data-cache/src/test/java/org/molgenis/data/cache/l1/L1CacheRepositoryDecoratorTest.java
  molgenis-data-cache/src/test/java/org/molgenis/data/cache/l1/L1CacheTest.java
  molgenis-data-cache/src/test/java/org/molgenis/data/cache/utils/CombinedEntityCacheTest.java
Labels: master

#7894 Sonar: Null pointers should not be dereferenced
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryGenerator.java
Labels: master

#7896 Sonar: "@NonNull" values should not be set to null
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/menu/MenuItem.java
Labels: master

#7885 Fix IntelliJ warnings and typos
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPage.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l1/L1Cache.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/MetadataParser.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxImportService.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetadataParser.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/ImporterConfiguration.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/IntermediateParseResults.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/aggregation/AnonymizedAggregateResult.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/service/OntologyService.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/service/impl/OntologyServiceImpl.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/UnitResolverImpl.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/UnitResolverImplTest.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/explain/service/ExplainServiceHelper.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/service/impl/SemanticSearchServiceImpl.java
Labels: master

#7900 [CHORE] Explicitly specify git commit for pull requests.
  Jenkinsfile
Labels: master

#7899 [FEAT] Make depth configurable in mapping project
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/data/request/MappingServiceRequest.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/mapping/model/MappingProject.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/meta/MappingProjectMetaData.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/repository/impl/MappingProjectRepositoryImpl.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/AlgorithmService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/MappingService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImpl.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/MappingServiceImpl.java
  molgenis-semantic-mapper/src/main/resources/js/attribute-mapping.js
  molgenis-semantic-mapper/src/main/resources/templates/view-attribute-mapping.ftl
  molgenis-semantic-mapper/src/main/resources/templates/view-mapping-projects.ftl
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/MappingServiceControllerTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/repository/impl/MappingProjectRepositoryImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplIT.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/MappingServiceImplTest.java
Labels: 7.2

#7840 fix/7837-data-row-edit-file-bug
  molgenis-data-row-edit/src/main/frontend/package.json
  molgenis-data-row-edit/src/main/frontend/src/components/DataRowEdit.vue
  molgenis-data-row-edit/src/main/frontend/src/repository/dataRowRepository.js
  molgenis-data-row-edit/src/main/frontend/test/unit/specs/components/DataRowEdit.spec.js
  molgenis-data-row-edit/src/main/frontend/test/unit/specs/repository/dataRowRepository.spec.js
  molgenis-data-row-edit/src/main/frontend/yarn.lock
Labels: master, mod:data-row-edit

#7867 [FEAT] Add metrics for prometheus
  molgenis-app/pom.xml
  molgenis-bootstrap/pom.xml
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/MolgenisBootstrapper.java
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/populate/UsersRolesPopulatorImpl.java
  molgenis-bootstrap/src/test/java/org/molgenis/metrics/MetricsControllerTest.java
  molgenis-bootstrap/src/test/java/org/molgenis/metrics/MolgenisTimedAspectTest.java
  molgenis-data-cache/pom.xml
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l2/L2Cache.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l3/L3Cache.java
  molgenis-data-cache/src/test/java/org/molgenis/data/cache/l2/L2CacheTest.java
  molgenis-data-cache/src/test/java/org/molgenis/data/cache/l3/L3CacheTest.java
  molgenis-data-import/pom.xml
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportService.java
  molgenis-data-index/src/main/java/org/molgenis/data/index/job/IndexJobService.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/bootstrap/MolgenisUpgradeBootstrapper.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/MolgenisVersionService.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/Step34AddRoleMetrics.java
  molgenis-data-migrate/src/main/resources/step34-roleMetrics.sql
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/RestController.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/RestControllerV2.java
  molgenis-metrics/pom.xml
  molgenis-metrics/src/main/java/org/molgenis/metrics/MeterBindersConfiguration.java
  molgenis-metrics/src/main/java/org/molgenis/metrics/MetricsConfig.java
  molgenis-metrics/src/main/java/org/molgenis/metrics/MetricsController.java
  molgenis-metrics/src/main/java/org/molgenis/metrics/MolgenisTimedAspect.java
  molgenis-platform-integration-tests/pom.xml
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java
  molgenis-security/pom.xml
  molgenis-security/src/main/java/org/molgenis/security/metrics/SessionMetrics.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/MappingService.java
  molgenis-swagger/src/main/resources/templates/view-swagger-ui.ftl
  pom.xml
Labels: master

#7906 Notify user then fields are invalid on trying to save row.
  molgenis-data-row-edit/src/main/frontend/src/components/DataRowEdit.vue
  molgenis-data-row-edit/src/main/frontend/test/unit/specs/components/DataRowEdit.spec.js
  molgenis-data-row-edit/src/main/resources/l10n/data-row-edit_en.properties
  molgenis-data-row-edit/src/main/resources/l10n/data-row-edit_nl.properties
Labels: master, mod:data-row-edit

#7920 Fix #7914: When I start my questionnaire and go back to start and then start again, my questionnaire does not start
  molgenis-questionnaires/src/main/frontend/src/store/actions.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/actions.spec.js
Labels: 7.2, mod:questionnaires

#7919 Fix #7915 When I fill in an out of range number in questionnaire, I can proceed and submit
  molgenis-questionnaires/src/main/frontend/src/store/getters.js
  molgenis-questionnaires/src/main/frontend/test/unit/specs/store/getters.spec.js
Labels: 7.2, mod:questionnaires
