Repository molgenis/molgenis, pull requests merged in 2019-03, with the labels that each got.

#8249 Fix #8243 Docs: remove 'xref as label attr' expression example
  docs/user_documentation/import-data/ref-emx.md
Labels: master

#8252 Update spring-boot-starter-parent 2.1.2 -> 2.1.3
  pom.xml
Labels: master

#8272 Fix Sonar issues IX
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/controller/AppManagerController.java
  molgenis-beacon/src/main/java/org/molgenis/beacon/service/impl/BeaconInfoServiceImpl.java
  molgenis-beacon/src/test/java/org/molgenis/beacon/service/BeaconInfoServiceImplTest.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/usermanager/UserManagerServiceImpl.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/controller/FeedbackController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/usermanager/UserManagerServiceImplTest.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l2/L2Cache.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l3/L3Cache.java
  molgenis-data-csv/src/main/java/org/molgenis/data/csv/CsvIterator.java
  molgenis-data-excel/src/main/java/org/molgenis/data/excel/xlsx/XlsxWriter.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/FileStore.java
  molgenis-data-file/src/test/java/org/molgenis/data/file/FileStoreTest.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportRunService.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/ImportRunServiceTest.java
  molgenis-data-index/src/main/java/org/molgenis/data/index/IndexDependencyModel.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/service/RestService.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/GroupRepositoryDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/exception/ParentPackagePermissionDeniedException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/EntityTypeRepositorySecurityDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecorator.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/GroupRepositoryDecoratorTest.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/AttributeValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/EntityTypeValidator.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobBootstrapper.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/RelationTransformer.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/impl/AttributeTypeServiceImpl.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/repository/OntologyTermRepository.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/sorta/controller/SortaController.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/sorta/service/impl/SortaServiceImpl.java
  molgenis-searchall/src/main/java/org/molgenis/searchall/service/SearchAllService.java
  molgenis-security/src/main/java/org/molgenis/security/user/UserAccountServiceImpl.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/service/impl/UntypedTagService.java
  pom.xml
Labels: master

#8280 Fix Sonar issues X
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/EntityTypeValidator.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/sorta/controller/SortaController.java
Labels: master

#8247 M6440 Files API with Minio blob storage
  .ci/jobs/api-tests.sh
  .ci/jobs/integration-tests.sh
  .ci/services/install-minio-6.sh
  .ci/services/install-postgres-11.sh
  .travis.yml
  docs/SUMMARY.md
  docs/developer_documentation/ref-api-files.md
  docs/quickstart/guide-tomcat.md
  molgenis-api-files/pom.xml
  molgenis-api-files/src/main/java/org/molgenis/api/files/FilesApiNamespace.java
  molgenis-api-files/src/main/java/org/molgenis/api/files/FilesService.java
  molgenis-api-files/src/main/java/org/molgenis/api/files/FilesServiceImpl.java
  molgenis-api-files/src/main/java/org/molgenis/api/files/v1/FileResponse.java
  molgenis-api-files/src/main/java/org/molgenis/api/files/v1/FilesController.java
  molgenis-api-files/src/test/java/org/molgenis/api/files/FilesServiceImplTest.java
  molgenis-api-files/src/test/java/org/molgenis/api/files/v1/FilesControllerTest.java
  molgenis-api/pom.xml
  molgenis-api/src/test/java/org/molgenis/api/ApiControllerTest.java
  molgenis-app/pom.xml
  molgenis-app/rpm/postinstall.bash
  molgenis-app/rpm/templates/molgenis-server.properties
  molgenis-bootstrap/pom.xml
  molgenis-bootstrap/src/test/java/org/molgenis/bootstrap/RegistryBootstrapperTest.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppConfig.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l1/L1Cache.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l2/L2Cache.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l3/L3Cache.java
  molgenis-data-file/pom.xml
  molgenis-data-file/src/main/java/org/molgenis/data/file/BlobMetadata.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/BlobStore.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/BlobStoreDecorator.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/FileMetaRepositoryDecorator.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/FileMetaRepositoryDecoratorFactory.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/FileStore.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/TransactionalBlobStoreDecorator.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/minio/MinioBlobStore.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/minio/MinioClientFacade.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/minio/MinioClientFactory.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/minio/MinioClientFactoryImpl.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/minio/MinioStoreConfig.java
  molgenis-data-file/src/test/java/org/molgenis/data/file/FileMetaRepositoryDecoratorTest.java
  molgenis-data-file/src/test/java/org/molgenis/data/file/TransactionalBlobStoreDecoratorTest.java
  molgenis-data-file/src/test/java/org/molgenis/data/file/minio/MinioBlobStoreTest.java
  molgenis-data-file/src/test/java/org/molgenis/data/file/minio/MinioClientFacadeTest.java
  molgenis-data-file/src/test/java/org/molgenis/data/file/minio/MinioClientFactoryImplTest.java
  molgenis-data-index/src/main/java/org/molgenis/data/index/transaction/IndexTransactionListener.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/identifier/EntityTypeRegistryImpl.java
  molgenis-data/src/main/java/org/molgenis/data/transaction/TransactionListener.java
  molgenis-security/src/main/java/org/molgenis/security/acl/AclCacheTransactionListener.java
  molgenis-swagger/src/main/resources/templates/view-swagger-ui.ftl
  pom.xml
Labels: master

#8282 Replace jquery settings plugin with vue ( forms based ) settings
  molgenis-app/src/main/resources/molgenis_ui.json
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/settingsmanager/SettingsManagerController.java
  molgenis-core-ui/src/main/resources/js/settingsmanager.js
  molgenis-core-ui/src/main/resources/templates/view-settingsmanager.ftl
  molgenis-frontend/package.json
  molgenis-web/src/test/resources/molgenis_ui.json
Labels: 8.0.0-SNAPSHOT, mod:settings-ui

#8294 Fix #8192 Link to privacy settings pdf is broken
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/settings/AppDbSettings.java
Labels: master

#8290 M6440 Files API doc update & small enhancements
  docs/developer_documentation/ref-api-files.md
  docs/quickstart/guide-tomcat.md
  molgenis-api-files/src/main/java/org/molgenis/api/files/v1/FilesController.java
  molgenis-api-files/src/test/java/org/molgenis/api/files/v1/FilesControllerTest.java
Labels: master

#8301 Fix #7835 Login redirect incorrect when 403 on logo
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
Labels: master

#8256 feat: Updated scripts plugin
  docs/user_documentation/scripts/guide-scripts.md
  molgenis-core-ui/src/main/resources/img/cancel.png
  molgenis-core-ui/src/main/resources/img/delete.png
  molgenis-frontend/package.json
  molgenis-frontend/pom.xml
  molgenis-scripts/pom.xml
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptPluginController.java
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptsI18nConfig.java
  molgenis-scripts/src/main/resources/css/.gitignore
  molgenis-scripts/src/main/resources/js/scripts.js
  molgenis-scripts/src/main/resources/l10n/scripts_en.properties
  molgenis-scripts/src/main/resources/l10n/scripts_nl.properties
  molgenis-scripts/src/main/resources/templates/view-scripts.ftl
Labels: master, mod:scripts

#8311 Fix #8288 Docker-compose Minio
  molgenis-app/docker-compose.yml
Labels: master

#8315 Remove check on unused ROLE_PLUGIN_READ_indexmanager role
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/index/admin/IndexManagerServiceImpl.java
Labels: master

#8298 Fix #3154 Error 500 when exceeding the maximum file upload size
  molgenis-web/src/main/java/org/molgenis/web/exception/SpringExceptionHandler.java
  molgenis-web/src/test/java/org/molgenis/web/exception/SpringExceptionHandlerTest.java
Labels: master

#8309 Fix #8283 Improved importer error message when entity id=null
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/EntityAttributesValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/EntityAttributesValidatorTest.java
Labels: master

#8312 Fix #8234 Multiple AnonymousAuthenticationFilter in filter chain
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
Labels: master

#8284 Fix #8270 Scheduled job cronexpression link broken
  molgenis-jobs/src/main/java/org/molgenis/jobs/model/ScheduledJobMetadata.java
Labels: master

#8320 Default static content for home plugin
  molgenis-app/src/main/java/org/molgenis/app/WebAppSystemEntityRegistry.java
Labels: master

#8314 Fix #8286 Log PostgreSqlExceptionTranslator exceptions of unexpected class
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlExceptionTranslator.java
Labels: master
