Repository molgenis/molgenis, pull requests merged in 2019-07, with the labels that each got.

#8562 Selection parser/converter & API test stubs
  molgenis-api-data/pom.xml
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/BaseEntityRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DataApiV3Config.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DataServiceV3.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DataServiceV3Impl.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DeleteEntityRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityController.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityManagerV3.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityManagerV3Impl.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/Selection.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/SelectionConverter.java
  molgenis-api-data/src/main/resources/SelectionParser.jj
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/ApiIT.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/DataServiceV3ImplTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityControllerTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityManagerV3ImplTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/SelectionParserTest.java
  pom.xml
Labels: branch:dataApiV3

#8567 Data API v3 API tests
  molgenis-api-data/pom.xml
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/BaseEntityRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DataApiV3Config.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DataServiceV3.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DataServiceV3Impl.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityController.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityManagerV3Impl.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityMapper.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityMapperImpl.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/AbstractApiTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/DataServiceV3ImplTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityControllerIT.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityControllerTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityMapperImplTest.java
  molgenis-api-data/src/test/resources/org/molgenis/api/data/v3/data_api_v3_emx.xlsx
  molgenis-api-data/src/test/resources/org/molgenis/api/data/v3/retrieveResource.json
  molgenis-api-data/src/test/resources/org/molgenis/api/data/v3/updateResource.json
  molgenis-api/src/main/java/org/molgenis/api/convert/SelectionConverter.java
  molgenis-api/src/main/java/org/molgenis/api/model/Selection.java
  molgenis-api/src/main/resources/SelectionParser.jj
  molgenis-api/src/test/java/org/molgenis/api/convert/SelectionParserTest.java
  molgenis-test/pom.xml
  molgenis-test/src/main/java/org/molgenis/test/IsEqualJson.java
Labels: branch:dataApiV3, work in progress

#8566 IsEqualJson matcher test util
  molgenis-test/pom.xml
  molgenis-test/src/main/java/org/molgenis/test/IsEqualJson.java
Labels: master

#8572 Global exception handling: add RFC 7807 Problem responses
  molgenis-api-data/src/test/java/org/molgenis/api/data/v1/RestControllerTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v2/RestControllerV2Test.java
  molgenis-api-identities/src/test/java/org/molgenis/api/identities/GroupRestControllerTest.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerIT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v2/RestControllerV2IT.java
  molgenis-api/pom.xml
  molgenis-api/src/test/java/org/molgenis/api/RootApiControllerTest.java
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/controller/AppControllerTest.java
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/RegistryBootstrapper.java
  molgenis-bootstrap/src/test/java/org/molgenis/bootstrap/RegistryBootstrapperTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/user/UserAccountControllerMockMvcTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/controller/UiContextControllerTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/CopyServiceIT.java
  molgenis-web/pom.xml
  molgenis-web/src/main/java/org/molgenis/web/exception/ErrorMessagesResponseGenerator.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionHandlerFacade.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionHandlerFacadeImpl.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionHandlerUtils.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionResponseGenerator.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionResponseGeneratorRegistrar.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionResponseGeneratorRegistry.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionResponseGeneratorRegistryImpl.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionResponseType.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionUtils.java
  molgenis-web/src/main/java/org/molgenis/web/exception/FallbackExceptionHandler.java
  molgenis-web/src/main/java/org/molgenis/web/exception/GlobalControllerExceptionHandler.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ModelAndViewExceptionResponseGenerator.java
  molgenis-web/src/main/java/org/molgenis/web/exception/Problem.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ProblemExceptionResponseGenerator.java
  molgenis-web/src/main/java/org/molgenis/web/exception/SpringExceptionHandler.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionHandlerFacadeImplTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionHandlerUtilsTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionResponseGeneratorRegistrarTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionResponseGeneratorRegistryImplTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionUtilsTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/FallbackExceptionHandlerTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/GlobalControllerExceptionHandlerTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ProblemExceptionResponseGeneratorTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/SpringExceptionHandlerTest.java
  pom.xml
Labels: master

#8577 Introduce TestResourceUtils for templated expected values
  molgenis-test/pom.xml
  molgenis-test/src/main/java/org/molgenis/test/TestResourceUtils.java
Labels: master

#8573 API query parser & Data API v3 findResources/deleteResources endpoints
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DataApiV3Config.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DataServiceV3.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DataServiceV3Impl.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/Entities.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityController.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityMapper.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityMapperImpl.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/QueryV3Mapper.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/model/AbstractEntityTypeRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/model/AbstractReadRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/model/DeleteEntitiesRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/model/DeleteEntityRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/model/EntitiesResponse.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/model/EntityResponse.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/model/ReadEntitiesRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/model/ReadEntityRequest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/ApiIT.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/DataServiceV3ImplTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityControllerIT.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityControllerTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityMapperImplTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/QueryV3MapperTest.java
  molgenis-api-data/src/test/resources/org/molgenis/api/data/v3/deleteResourceCollection.json
  molgenis-api-data/src/test/resources/org/molgenis/api/data/v3/deleteResourceCollectionQuery.json
  molgenis-api-data/src/test/resources/org/molgenis/api/data/v3/retrieveResourceCollection.json
  molgenis-api-data/src/test/resources/org/molgenis/api/data/v3/retrieveResourceCollectionSortQuery.json
  molgenis-api/pom.xml
  molgenis-api/src/main/java/org/molgenis/api/ApiConfig.java
  molgenis-api/src/main/java/org/molgenis/api/RootApiController.java
  molgenis-api/src/main/java/org/molgenis/api/convert/QueryConverter.java
  molgenis-api/src/main/java/org/molgenis/api/convert/QueryRsqlVisitor.java
  molgenis-api/src/main/java/org/molgenis/api/model/Query.java
  molgenis-api/src/main/java/org/molgenis/api/model/Sort.java
  molgenis-api/src/main/java/org/molgenis/api/model/response/AppVersionResponse.java
  molgenis-api/src/main/java/org/molgenis/api/model/response/OptionsResponse.java
  molgenis-api/src/test/java/org/molgenis/api/convert/QueryConverterTest.java
  molgenis-api/src/test/java/org/molgenis/api/convert/QueryRsqlVisitorTest.java
  molgenis-api/src/test/java/org/molgenis/api/convert/SelectionConverterTest.java
  molgenis-api/src/test/java/org/molgenis/api/convert/SortConverterTest.java
Labels: branch:dataApiV3

#8578 Merge with molgenis/master & IT cross-host fix
  Jenkinsfile
  molgenis-api-data/src/test/java/org/molgenis/api/data/v1/RestControllerTest.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v2/RestControllerV2Test.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityControllerIT.java
  molgenis-api-identities/src/test/java/org/molgenis/api/identities/GroupRestControllerTest.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerIT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v2/RestControllerV2IT.java
  molgenis-api/pom.xml
  molgenis-api/src/test/java/org/molgenis/api/RootApiControllerTest.java
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/controller/AppControllerTest.java
  molgenis-app/pom.xml
  molgenis-app/rpm/postinstall.bash
  molgenis-app/rpm/preinstall.bash
  molgenis-app/rpm/templates/molgenis-server.properties
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/RegistryBootstrapper.java
  molgenis-bootstrap/src/test/java/org/molgenis/bootstrap/RegistryBootstrapperTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/user/UserAccountControllerMockMvcTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/controller/UiContextControllerTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/CopyServiceIT.java
  molgenis-security/src/main/java/org/molgenis/security/AjaxAwareInvalidSessionStrategy.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-security/src/main/java/org/molgenis/security/login/MolgenisLoginController.java
  molgenis-security/src/test/java/org/molgenis/security/AjaxAwareInvalidSessionStrategyTest.java
  molgenis-security/src/test/java/org/molgenis/security/login/MolgenisLoginControllerTest.java
  molgenis-test/pom.xml
  molgenis-test/src/main/java/org/molgenis/test/TestResourceUtils.java
  molgenis-web/pom.xml
  molgenis-web/src/main/java/org/molgenis/web/exception/ErrorMessagesResponseGenerator.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionHandlerFacade.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionHandlerFacadeImpl.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionHandlerUtils.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionResponseGenerator.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionResponseGeneratorRegistrar.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionResponseGeneratorRegistry.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionResponseGeneratorRegistryImpl.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionResponseType.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionUtils.java
  molgenis-web/src/main/java/org/molgenis/web/exception/FallbackExceptionHandler.java
  molgenis-web/src/main/java/org/molgenis/web/exception/GlobalControllerExceptionHandler.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ModelAndViewExceptionResponseGenerator.java
  molgenis-web/src/main/java/org/molgenis/web/exception/Problem.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ProblemExceptionResponseGenerator.java
  molgenis-web/src/main/java/org/molgenis/web/exception/SpringExceptionHandler.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionHandlerFacadeImplTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionHandlerUtilsTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionResponseGeneratorRegistrarTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionResponseGeneratorRegistryImplTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionUtilsTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/FallbackExceptionHandlerTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/GlobalControllerExceptionHandlerTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ProblemExceptionResponseGeneratorTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/SpringExceptionHandlerTest.java
Labels: branch:dataApiV3

#8575 delete IT test data in teardown
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityControllerIT.java
Labels: branch:dataApiV3

#8579 Fix: IT work on hosts other than localhost
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityControllerIT.java
Labels: branch:dataApiV3
