Repository molgenis/molgenis, pull requests merged in 2019-06, with the labels that each got.

#8525 Workaround for issue 8516 (mock already garbage collected)
  molgenis-security-core/src/test/java/org/molgenis/security/core/utils/SecurityUtilsTest.java
Labels: master

#8524 Sonar and swagger improvements for permissions API
  molgenis-api-permissions/src/main/java/org/molgenis/api/permissions/PermissionsController.java
  molgenis-api-permissions/src/main/java/org/molgenis/api/permissions/exceptions/rsql/PermissionQueryParseException.java
  molgenis-api-permissions/src/main/java/org/molgenis/api/permissions/exceptions/rsql/UnknownPermissionQueryParamException.java
  molgenis-api-permissions/src/main/java/org/molgenis/api/permissions/exceptions/rsql/UnsupportedPermissionQueryOperatorException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/exception/AclAlreadyExistsException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/exception/AclClassAlreadyExistsException.java
Labels: master

#8530 Fix #8037 Application can boot with NoSuchBeanDefinitionException
  molgenis-metrics/src/main/java/org/molgenis/metrics/MetricsConfig.java
Labels: 8.1

#8529 Fix #8037 Application can boot with NoSuchBeanDefinitionException
  molgenis-metrics/src/main/java/org/molgenis/metrics/MetricsConfig.java
Labels: 8.0

#8531 Fix #8037 Application can boot with NoSuchBeanDefinitionException
  molgenis-metrics/src/main/java/org/molgenis/metrics/MetricsConfig.java
Labels: 8.1

#8528 Fix #8037 Application can boot with NoSuchBeanDefinitionException
  molgenis-metrics/src/main/java/org/molgenis/metrics/MetricsConfig.java
Labels: 7.4

#8400 7.4 Backport: Let metrics classes register themselves at the registry
  molgenis-metrics/src/main/java/org/molgenis/metrics/MeterBindersConfiguration.java
  molgenis-metrics/src/main/java/org/molgenis/metrics/MetricsConfig.java
  molgenis-security/src/main/java/org/molgenis/security/metrics/SessionMetrics.java
Labels: 7.4

#8533 [CHORE] Rename rancher projects
  Jenkinsfile
Labels: 7.4

#8536 [CHORE] Do not close the staging repo
  pom.xml
Labels: 8.1

#8535 Feature/serve frontend via proxy
  molgenis-app-manager/src/main/resources/templates/view-app-manager.ftl
  molgenis-app/docker-compose.yml
  molgenis-app/nginx.conf
  molgenis-app/redirect-map.conf
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppConfig.java
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-blue.css
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-blue.css.map
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-blue.min.css
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-green.css
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-green.css.map
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-green.min.css
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-red.css
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-red.css.map
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-red.min.css
  molgenis-core-ui/src/main/resources/fonts/fontawesome-webfont.af7ae50.woff2
  molgenis-core-ui/src/main/resources/fonts/fontawesome-webfont.b06871f.ttf
  molgenis-core-ui/src/main/resources/fonts/fontawesome-webfont.fee66e7.woff
  molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl
  molgenis-core/src/main/java/org/molgenis/core/framework/ui/ResourcePathPatterns.java
  molgenis-data-row-edit/src/main/resources/templates/view-data-row-edit.ftl
  molgenis-frontend/package.json
  molgenis-frontend/pom.xml
  molgenis-metadata-manager/src/main/resources/templates/view-metadata-manager.ftl
  molgenis-navigator/src/main/resources/templates/view-navigator.ftl
  molgenis-one-click-importer/src/main/resources/templates/view-one-click-importer.ftl
  molgenis-questionnaires/src/main/resources/templates/view-questionnaire.ftl
  molgenis-scripts/src/main/resources/templates/view-scripts.ftl
  molgenis-searchall/src/main/resources/templates/view-search-all.ftl
  molgenis-security-ui/src/main/resources/templates/view-security-ui.ftl
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-security/src/main/resources/templates/view-2fa-imports.ftl
  molgenis-security/src/main/resources/templates/view-change-password.ftl
  molgenis-security/src/main/resources/templates/view-login.ftl
  molgenis-settings-ui/src/main/resources/templates/view-settings.ftl
Labels: master

#8463 fix(AccountServiceImpl.java): updated activation email
  molgenis-security/src/main/java/org/molgenis/security/account/AccountServiceImpl.java
  molgenis-security/src/test/java/org/molgenis/security/account/AccountServiceImplTest.java
Labels: master

#8546 fix(core-ui): fix FontAwesome resources
  molgenis-core-ui/src/main/resources/fonts/Font_Awesome/FontAwesome.otf
  molgenis-core-ui/src/main/resources/fonts/Font_Awesome/fontawesome-webfont.ttf
  molgenis-core-ui/src/main/resources/fonts/Font_Awesome/fontawesome-webfont.woff
  molgenis-core-ui/src/main/resources/fonts/Font_Awesome/fontawesome-webfont.woff2
  molgenis-core-ui/src/main/resources/fonts/fontawesome-webfont.674f50d.eot
  molgenis-core-ui/src/main/resources/fonts/fontawesome-webfont.af7ae50.woff2
  molgenis-core-ui/src/main/resources/fonts/fontawesome-webfont.b06871f.ttf
  molgenis-core-ui/src/main/resources/fonts/fontawesome-webfont.fee66e7.woff
  molgenis-core-ui/src/main/resources/img/fontawesome-webfont.912ec66.svg
Labels: master

#8551 Fix #8548: Redirect plugin can redirect to URLs that are not present in the menu
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/controller/RedirectController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/controller/RedirectControllerTest.java
Labels: 8.1

#8557 Update travis maven version to 3.6.0
  .travis.yml
Labels: master

#8553 fix(core-ui): only redirect to urls present in the menu
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/controller/RedirectController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/controller/RedirectControllerTest.java
Labels: master

#8559 M6276 Data API v3: Entity mapper
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/BaseEntityRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntitiesRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntitiesResponse.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityCollection.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityController.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityMapper.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityMapperImpl.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityRequest.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/EntityResponse.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/Selection.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/EntityMapperImplTest.java
  molgenis-api-data/src/test/resources/test.html
Labels: branch:dataApiV3

#8556 Fix #8513: When you have an account on a server sign in screen always…
  molgenis-security/src/main/java/org/molgenis/security/AjaxAwareInvalidSessionStrategy.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-security/src/main/java/org/molgenis/security/login/MolgenisLoginController.java
  molgenis-security/src/test/java/org/molgenis/security/AjaxAwareInvalidSessionStrategyTest.java
  molgenis-security/src/test/java/org/molgenis/security/login/MolgenisLoginControllerTest.java
Labels: master
