Repository molgenis/molgenis, pull requests merged in 2019-04, with the labels that each got.

#8319 Fix #8230: Usernames are not checked for spaces
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/UserMetadata.java
Labels: master

#8326 Fix Sonar vulnerabilities and warnings
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ImportWizardController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPage.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-dataexplorer/src/test/java/org/molgenis/dataexplorer/DataExplorerControllerTest.java
  molgenis-validation/pom.xml
  molgenis-validation/src/main/java/org/molgenis/validation/UriValidator.java
  molgenis-validation/src/main/java/org/molgenis/validation/exception/LocalhostNotAllowedException.java
  molgenis-validation/src/main/java/org/molgenis/validation/exception/RelativePathNotAllowedException.java
  molgenis-validation/src/main/resources/l10n/validation_en.properties
  molgenis-validation/src/test/java/org/molgenis/validation/UriValidatorTest.java
  molgenis-validation/src/test/java/org/molgenis/validation/exception/LocalhostNotAllowedExceptionTest.java
  molgenis-validation/src/test/java/org/molgenis/validation/exception/RelativePathNotAllowedExceptionTest.java
Labels: master

#8297 Upgrade data row edit plugin to latest version of ui forms
  molgenis-core-ui/src/main/resources/l10n/ui-form_en.properties
  molgenis-core-ui/src/main/resources/l10n/ui-form_nl.properties
  molgenis-frontend/package.json
Labels: master

#8328 Fix #8327 Downloading extending entities fails due to order issues
  molgenis-data-import/src/main/java/org/molgenis/data/export/EmxExportServiceImpl.java
  molgenis-data-import/src/test/java/org/molgenis/data/export/EmxExportServiceImplTest.java
Labels: master

#8331 Let metrics classes register themselves at the registry
  molgenis-metrics/src/main/java/org/molgenis/metrics/MeterBindersConfiguration.java
  molgenis-metrics/src/main/java/org/molgenis/metrics/MetricsConfig.java
  molgenis-security/src/main/java/org/molgenis/security/metrics/SessionMetrics.java
Labels: 8.0

#8330 Only add login modal for version 1 plugins
  molgenis-core-ui/src/main/resources/templates/molgenis-footer.ftl
Labels: 8.0

#8304 Fix #8251 Token authentication changes session authentication
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-security/src/main/java/org/molgenis/security/TokenAwareSecurityContextRepository.java
  molgenis-security/src/test/java/org/molgenis/security/TokenAwareSecurityContextRepositoryTest.java
Labels: 8.0

#8372 M3774 EMX support for auto date/datetime
  docs/user_documentation/import-data/ref-emx.md
  molgenis-data-import/src/main/java/org/molgenis/data/export/mapper/AttributeMapper.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetadataParser.java
  molgenis-data-import/src/test/java/org/molgenis/data/export/AttributeMapperTest.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/emx/EmxMetadataParserTest.java
  molgenis-data-import/src/test/resources/it_emx_autodate.xlsx
  molgenis-platform-integration-tests/src/test/resources/xls/expectedDownloadResult.xlsx
Labels: master

#8346 Fix #8327 Downloading extending entities fails due to order issues
  molgenis-data-import/src/main/java/org/molgenis/data/export/EmxExportServiceImpl.java
  molgenis-data-import/src/test/java/org/molgenis/data/export/EmxExportServiceImplTest.java
Labels: 8.0

#8329 Fix #8292 Account unreachable when 'Forgot password' mail not sent
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/PasswordResetToken.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/PasswordResetTokenFactory.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/PasswordResetTokenMetadata.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/user/InvalidEmailAddressException.java
  molgenis-data-security/src/main/resources/l10n/data-security_en.properties
  molgenis-data-security/src/main/resources/l10n/data-security_nl.properties
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/PasswordResetTokenFactoryTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/PasswordResetTokenTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/config/SecurityTestConfig.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/user/InvalidEmailAddressExceptionTest.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-security/src/main/java/org/molgenis/security/SecurityL10nConfig.java
  molgenis-security/src/main/java/org/molgenis/security/account/AccountController.java
  molgenis-security/src/main/java/org/molgenis/security/account/AccountService.java
  molgenis-security/src/main/java/org/molgenis/security/account/AccountServiceImpl.java
  molgenis-security/src/main/java/org/molgenis/security/account/ExpiredPasswordResetTokenException.java
  molgenis-security/src/main/java/org/molgenis/security/account/InvalidPasswordResetTokenException.java
  molgenis-security/src/main/java/org/molgenis/security/account/PasswordResetTokenCreationException.java
  molgenis-security/src/main/java/org/molgenis/security/account/PasswordResetTokenRepository.java
  molgenis-security/src/main/java/org/molgenis/security/account/PasswordResetTokenRepositoryImpl.java
  molgenis-security/src/main/java/org/molgenis/security/account/PasswordResetter.java
  molgenis-security/src/main/java/org/molgenis/security/account/PasswordResetterImpl.java
  molgenis-security/src/main/java/org/molgenis/security/account/UnknownPasswordResetTokenException.java
  molgenis-security/src/main/resources/l10n/security_en.properties
  molgenis-security/src/main/resources/l10n/security_nl.properties
  molgenis-security/src/main/resources/templates/view-change-password.ftl
  molgenis-security/src/test/java/org/molgenis/security/account/AccountControllerTest.java
  molgenis-security/src/test/java/org/molgenis/security/account/AccountServiceImplTest.java
  molgenis-security/src/test/java/org/molgenis/security/account/ExpiredPasswordResetTokenExceptionTest.java
  molgenis-security/src/test/java/org/molgenis/security/account/InvalidPasswordResetTokenExceptionTest.java
  molgenis-security/src/test/java/org/molgenis/security/account/PasswordResetTokenCreationExceptionTest.java
  molgenis-security/src/test/java/org/molgenis/security/account/PasswordResetTokenRepositoryImplTest.java
  molgenis-security/src/test/java/org/molgenis/security/account/PasswordResetterImplTest.java
  molgenis-security/src/test/java/org/molgenis/security/account/UnknownPasswordResetTokenExceptionTest.java
Labels: 8.0

#8350 Upgrade spring-boot-starter-parent 2.1.3.RELEASE to 2.1.4.RELEASE
  pom.xml
Labels: 8.0

#8387 Fix #8251 Token authn changes session authentication (fix constructor args order)
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
Labels: 8.0

#8388 Fix #8361 User manager: user activation broken
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisMenuController.java
Labels: 8.0

#8366 Fix #8190: Default logo does not match default style
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/settings/AppDbSettings.java
Labels: 8.0

#8374 M6105 Mapper: Copy algorithms from source when adding new source
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/mapping/model/AttributeMapping.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/mapping/model/EntityMapping.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/AlgorithmService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImpl.java
  molgenis-semantic-mapper/src/main/resources/templates/view-single-mapping-project.ftl
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/MappingServiceControllerTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/mapping/model/AttributeMappingTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/mapping/model/EntityMappingTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplTest.java
Labels: 8.0

#8394 Fix #8389 Mandatory "change password" broken
  molgenis-security/src/main/java/org/molgenis/security/account/PasswordResetterImpl.java
  molgenis-security/src/test/java/org/molgenis/security/account/PasswordResetterImplTest.java
Labels: 8.0

#8391 Fix #8378 Importer ignores tags in the database, causing unjustified UnknownTagExceptions
  docs/user_documentation/finding-data/guide-navigator.md
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetadataParser.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/emx/EmxMetadataParserTest.java
Labels: 8.0

#8403 Fix/8358 Homepage button opens in same tab rather than target _blank
  molgenis-app/src/main/java/org/molgenis/app/WebAppSystemEntityRegistry.java
Labels: 8.0

#8390 Fix #8367 Adding same user to same group in multiple roles is allowed
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMembershipDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMembershipRepositoryDecoratorFactory.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMembershipValidationException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMembershipValidator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMembershipValidatorImpl.java
  molgenis-data-security/src/main/resources/l10n/data-security_en.properties
  molgenis-data-security/src/main/resources/l10n/data-security_nl.properties
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/RoleMembershipDecoratorTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/RoleMembershipValidationExceptionTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/RoleMembershipValidatorImplTest.java
Labels: 8.0

#8405 Fix #8359 Mapping service algorithm edit search broken
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/MappingServiceControllerTest.java
Labels: 8.0

#8411 Fix #8379 Scheduled job timestamp incorrect
  molgenis-jobs/src/main/java/org/molgenis/jobs/model/JobExecutionLogAppender.java
Labels: 8.0

#8410 Fix #8404 Settings can return incorrect cached data
  molgenis-security/src/test/java/org/molgenis/security/settings/AuthenticationSettingsImplTest.java
  molgenis-settings/src/main/java/org/molgenis/settings/DefaultSettingsEntity.java
  molgenis-settings/src/main/java/org/molgenis/settings/mail/MailSettingsImpl.java
  molgenis-settings/src/main/java/org/molgenis/settings/mail/MailSettingsRepositoryDecorator.java
  molgenis-settings/src/main/java/org/molgenis/settings/mail/MailSettingsRepositoryDecoratorFactory.java
  molgenis-settings/src/test/java/org/molgenis/settings/mail/MailSettingsRepositoryDecoratorTest.java
Labels: 8.0

#8424 Favicon now matches style
  molgenis-core-ui/src/main/resources/img/favicon.ico
Labels: 8.0

#8428 Fix #6402 Google analytics broken
  molgenis-core-ui/src/main/resources/templates/molgenis-header-tracking.ftl
Labels: 8.0

#8425 Fix #8402 ScriptJob fails when scheduled, succeeds when started manually
  molgenis-scripts/src/main/java/org/molgenis/script/ScheduledScriptConfig.java
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptJobExecution.java
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptJobExecutionMetadata.java
  molgenis-scripts/src/test/java/org/molgenis/script/ScheduledScriptConfigTest.java
Labels: 8.0

#8435 Fix docs: nillable default in EMX should be true
  docs/user_documentation/import-data/ref-emx.md
Labels: 8.0

#8431 Fix #8430 Logo above menu bar does not work on small screen
  molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl
Labels: 8.0

#8442 Files API update to due to versioning guideline change
  docs/developer_documentation/ref-api-files.md
  molgenis-api-files/src/main/java/org/molgenis/api/files/v1/FilesController.java
Labels: master

#8439 M6598 Remove index manager
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/index/admin/IndexManagerController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/index/admin/IndexManagerService.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/index/admin/IndexManagerServiceImpl.java
  molgenis-core-ui/src/main/resources/js/indexmanager.js
  molgenis-core-ui/src/main/resources/templates/view-indexmanager.ftl
Labels: master

#8445 Fix/8443 context is not a plugin
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/controller/UiContextController.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/controller/UiContextControllerTest.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-security/src/main/java/org/molgenis/security/exception/WebAppSecurityConfigException.java
  molgenis-security/src/main/resources/l10n/security_en.properties
  molgenis-security/src/main/resources/l10n/security_nl.properties
Labels: 8.0.0-SNAPSHOT, work in progress

#8416 fix(data-row-edit): fix 8356
  molgenis-data-row-edit/src/main/resources/l10n/data-row-edit_en.properties
  molgenis-data-row-edit/src/main/resources/l10n/data-row-edit_nl.properties
Labels: 8.0, work in progress

#8454 Fix/8453 Top logo pushes plugin content down
  molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl
Labels: bug

#8460 Bump frontend
  molgenis-frontend/.gitignore
  molgenis-frontend/README.md
  molgenis-frontend/package.json
Labels: 8.0

#8449 Fix #8448 & #8450 Columns not deleted from database when removing a compound attribute
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/EntityTypeValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/meta/EntityTypeValidatorTest.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/EntityType.java
  molgenis-data/src/test/java/org/molgenis/data/meta/model/EntityTypeTest.java
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/AttributeMapper.java
  molgenis-metadata-manager/src/test/java/org/molgenis/metadata/manager/mapper/AttributeMapperTest.java
Labels: 8.0

#8434 Fix #8429 ForwardedHeaderTransformer eats `X-Forwarded-*` headers
  molgenis-api-fair/src/main/java/org/molgenis/api/fair/controller/FairController.java
  molgenis-api-fair/src/test/java/org/molgenis/api/fair/controller/FairControllerTest.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/ForwardedHeaderAPIIT.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppConfig.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppInitializer.java
  molgenis-r/pom.xml
  molgenis-r/src/main/java/org/molgenis/r/MolgenisRController.java
  molgenis-security/src/main/java/org/molgenis/security/account/AccountController.java
  molgenis-security/src/test/java/org/molgenis/security/account/AccountControllerTest.java
Labels: 8.0

#8459 Migration step for adding the new settings plugin to the menu
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/bootstrap/MolgenisUpgradeBootstrapper.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/MolgenisVersionService.java
  molgenis-data-migrate/src/main/java/org/molgenis/data/migrate/version/Step37AddSettingsPluginToMenu.java
Labels: 8.0

#8477 Fix #8474: R script cannot use token to connect to molgenis API
  molgenis-r/pom.xml
  molgenis-r/src/main/java/org/molgenis/r/MolgenisRController.java
  molgenis-r/src/test/java/org/molgenis/r/MolgenisRControllerTest.java
Labels: 8.0
