Repository molgenis/molgenis, pull requests merged in 2019-01, with the labels that each got.

#8096 Add minimal sentry config
  molgenis-app/src/main/resources/sentry.properties
Labels: master

#8099 Pass app version to molgenisFooter object on global window for use in…
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/controller/AppController.java
  molgenis-app-manager/src/main/resources/templates/view-app.ftl
  molgenis-core-ui/src/main/resources/templates/molgenis-footer.ftl
Labels: master, mod:app-manager

#8095 Fix #7917 Metadata manager lookup attribute doesn't work
  molgenis-metadata-manager/src/main/frontend/src/flow.types.js
  molgenis-metadata-manager/src/main/frontend/src/store/actions.js
  molgenis-metadata-manager/src/main/frontend/src/store/mutations.js
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/AttributeMapper.java
Labels: master, mod:metadata-manager

#8108 Version bump 7.5.0-SNAPSHOT to 8.0.0-SNAPSHOT
  molgenis-amazon-bucket/pom.xml
  molgenis-api-tests/pom.xml
  molgenis-app-manager/pom.xml
  molgenis-app/pom.xml
  molgenis-beacon/pom.xml
  molgenis-bootstrap/pom.xml
  molgenis-core-ui/pom.xml
  molgenis-core/pom.xml
  molgenis-data-cache/pom.xml
  molgenis-data-csv/pom.xml
  molgenis-data-elasticsearch/pom.xml
  molgenis-data-excel/pom.xml
  molgenis-data-file/pom.xml
  molgenis-data-i18n/pom.xml
  molgenis-data-icd10/pom.xml
  molgenis-data-import/pom.xml
  molgenis-data-index/pom.xml
  molgenis-data-migrate/pom.xml
  molgenis-data-platform/pom.xml
  molgenis-data-plugin/pom.xml
  molgenis-data-postgresql/pom.xml
  molgenis-data-rest/pom.xml
  molgenis-data-row-edit/pom.xml
  molgenis-data-security/pom.xml
  molgenis-data-validation/pom.xml
  molgenis-data-vcf/pom.xml
  molgenis-data/pom.xml
  molgenis-dataexplorer/pom.xml
  molgenis-fair/pom.xml
  molgenis-file-ingester/pom.xml
  molgenis-genomebrowser/pom.xml
  molgenis-i18n/pom.xml
  molgenis-jobs/pom.xml
  molgenis-js/pom.xml
  molgenis-metadata-manager/pom.xml
  molgenis-metrics/pom.xml
  molgenis-navigator/pom.xml
  molgenis-one-click-importer/pom.xml
  molgenis-ontology-core/pom.xml
  molgenis-ontology/pom.xml
  molgenis-platform-integration-tests/pom.xml
  molgenis-python/pom.xml
  molgenis-questionnaires/pom.xml
  molgenis-r/pom.xml
  molgenis-scripts-core/pom.xml
  molgenis-scripts/pom.xml
  molgenis-searchall/pom.xml
  molgenis-security-core/pom.xml
  molgenis-security-ui/pom.xml
  molgenis-security/pom.xml
  molgenis-semantic-mapper/pom.xml
  molgenis-semantic-search/pom.xml
  molgenis-settings-ui/pom.xml
  molgenis-settings/pom.xml
  molgenis-swagger/pom.xml
  molgenis-test/pom.xml
  molgenis-util/pom.xml
  molgenis-validation/pom.xml
  molgenis-web/pom.xml
  pom.xml
Labels: master

#8111 Move shared test methods to AbstractSystemEntityTest
  .idea/fileTemplates/MolgenisEntityTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/GroupTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/UserTest.java
  molgenis-data/src/test/java/org/molgenis/data/meta/AbstractSystemEntityTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/copy/job/ResourceCopyJobExecutionTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/delete/job/ResourceDeleteJobExecutionTest.java
  molgenis-navigator/src/test/java/org/molgenis/navigator/download/job/ResourceDownloadJobExecutionTest.java
Labels: master

#8117 OpenCPU requirement 2.0 -> 2.1, R requirement 3.5
  docs/quickstart/guide-tomcat.md
Labels: master

#8116 Remove Jetty in favor of Tomcat-via-IDE
  molgenis-app/pom.xml
  pom.xml
Labels: master

#8114 Update PostgreSQL requirement 9.6 -> 11.1
  docs/quickstart/guide-tomcat.md
Labels: master

#8121 M6619 Non-superuser cannot modify superuser
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/UserRepositoryDecoratorFactory.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/UserRepositoryValidationDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/UserSuModificationException.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/UserValidator.java
  molgenis-data-security/src/main/resources/l10n/data-security_en.properties
  molgenis-data-security/src/main/resources/l10n/data-security_nl.properties
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/UserRepositoryValidationDecoratorTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/UserSuModificationExceptionTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/UserValidatorTest.java
Labels: master

#8130 EmxMetadataParser basic unit tests
  molgenis-data-import/src/main/java/org/molgenis/data/importer/EntitiesValidationReportImpl.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxAttribute.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetadataParser.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/IntermediateParseResults.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/emx/EmxMetadataParserTest.java
Labels: master

#8133 Fix #8132 Copy/Delete/Download jobs not row-level secured
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/job/ResourceCopyJobExecutionMetadata.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/delete/job/ResourceDeleteJobExecutionMetadata.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/download/job/ResourceDownloadJobExecutionMetadata.java
Labels: master

#8134 SortaController basic unit tests
  molgenis-ontology/src/main/java/org/molgenis/ontology/sorta/controller/SortaController.java
  molgenis-ontology/src/test/java/org/molgenis/ontology/sorta/controller/SortaControllerTest.java
Labels: master

#8138 Replace systemsgenetics dependency with vcf-io
  molgenis-data-vcf/pom.xml
  pom.xml
Labels: master

#8137 Fix various bugs reported by Sonar
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/index/admin/IndexManagerServiceImpl.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/emx/EmxMetadataParser.java
  molgenis-data-index/src/main/java/org/molgenis/data/index/job/IndexJobService.java
  molgenis-data-index/src/test/java/org/molgenis/data/index/job/IndexJobServiceTest.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/RestController.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/RestControllerV2.java
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/RestControllerTest.java
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/v2/RestControllerV2Test.java
  molgenis-data/src/main/java/org/molgenis/data/DataService.java
  molgenis-data/src/main/java/org/molgenis/data/meta/MetaDataServiceImpl.java
  molgenis-data/src/main/java/org/molgenis/data/meta/PackageRepositoryDecorator.java
  molgenis-data/src/main/java/org/molgenis/data/support/DataServiceImpl.java
  molgenis-data/src/test/java/org/molgenis/data/DataServiceImplTest.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/controller/DataExplorerController.java
  molgenis-dataexplorer/src/test/java/org/molgenis/dataexplorer/DataExplorerControllerTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformIT.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/TagWizardController.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/MappingServiceControllerTest.java
Labels: master

#8136 Feature/5941 c7 themes
  molgenis-core-ui/src/main/frontend/README.md
  molgenis-core-ui/src/main/frontend/package.json
  molgenis-core-ui/src/main/frontend/src/scss/bootstrap-molgenis-blue.scss
  molgenis-core-ui/src/main/frontend/yarn.lock
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/settings/AppDbSettings.java
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-blue.css
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-blue.css.map
  molgenis-core-ui/src/main/resources/css/bootstrap-4/bootstrap-molgenis-blue.min.css
  molgenis-core-ui/src/main/resources/css/bootstrap-molgenis-blue.min.css
  molgenis-core-ui/src/main/resources/fonts/BebasNeue/BebasNeue-Regular.ttf
  molgenis-core-ui/src/main/resources/fonts/BebasNeue/BebasNeue-Regular.woff
  molgenis-core-ui/src/main/resources/fonts/BebasNeue/BebasNeue-Regular.woff2
  molgenis-core-ui/src/main/resources/fonts/Font_Awesome/FontAwesome.otf
  molgenis-core-ui/src/main/resources/fonts/Font_Awesome/fontawesome-webfont.eot
  molgenis-core-ui/src/main/resources/fonts/Font_Awesome/fontawesome-webfont.svg
  molgenis-core-ui/src/main/resources/fonts/Font_Awesome/fontawesome-webfont.ttf
  molgenis-core-ui/src/main/resources/fonts/Font_Awesome/fontawesome-webfont.woff
  molgenis-core-ui/src/main/resources/fonts/Font_Awesome/fontawesome-webfont.woff2
  molgenis-core-ui/src/main/resources/fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
  molgenis-core-ui/src/main/resources/fonts/IBM_Plex_Mono/IBMPlexMono-Regular.woff
  molgenis-core-ui/src/main/resources/fonts/IBM_Plex_Mono/IBMPlexMono-Regular.woff2
  molgenis-core-ui/src/main/resources/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
  molgenis-core-ui/src/main/resources/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.woff
  molgenis-core-ui/src/main/resources/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.woff2
  molgenis-core-ui/src/main/resources/img/Logo_Black_Small.png
  molgenis-core-ui/src/main/resources/img/Logo_Black_Small.svg
  molgenis-core-ui/src/main/resources/img/Logo_Blue_Small.png
  molgenis-core-ui/src/main/resources/img/Logo_Blue_Small.svg
  molgenis-core-ui/src/main/resources/img/Logo_Green_Small.png
  molgenis-core-ui/src/main/resources/img/Logo_Green_Small.svg
  molgenis-core-ui/src/main/resources/img/Logo_White_Small.png
  molgenis-core-ui/src/main/resources/img/Logo_White_Small.svg
  molgenis-core-ui/src/main/resources/img/favicon.ico
  molgenis-core-ui/src/main/resources/img/filter-bw.png
Labels: master

#8147 Fix #8146 Change password form broken
  molgenis-security/src/main/java/org/molgenis/security/account/ChangePasswordForm.java
Labels: master

#8144 Fix various bugs reported by Sonar II
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/RestControllerV2.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/Token.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/NegotiatorController.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/config/NegotiatorEntityConfig.java
  molgenis-genomebrowser/src/main/java/org/molgenis/genomebrowser/GenomeBrowserTrack.java
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/mapper/AttributeMapper.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/service/EntityTypeCopier.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/algorithmgenerator/categorymapper/FrequencyCategoryMapper.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/algorithmgenerator/categorymapper/convertor/AmountConvertor.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/algorithmgenerator/generator/OneToManyCategoryAlgorithmGenerator.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/algorithmgenerator/rules/CategoryMatchQuality.java
Labels: master

#8148 Fix #8018: System packages can be moved outside of system package
  molgenis-data-security/src/main/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecorator.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/meta/PackageRepositorySecurityDecoratorTest.java
Labels: master

#8152 Fix Sonar issue
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/algorithmgenerator/generator/OneToManyCategoryAlgorithmGenerator.java
Labels: master

#8153 Fix #8132 Copy/Delete/Download jobs not row-level secured
  molgenis-navigator/src/main/java/org/molgenis/navigator/copy/job/ResourceCopyJobExecutionMetadata.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/delete/job/ResourceDeleteJobExecutionMetadata.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/download/job/ResourceDownloadJobExecutionMetaData.java
Labels: 7.4

#8076 Fix #8074 Security manager: show group on member add
  molgenis-security-ui/src/main/frontend/src/components/MemberAdd.vue
Labels: master

#8150 fix(header): Add polyfill to all pages.
  docs/developer_documentation/app-development.md
  molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl
Labels: master

#8151 [CHORE] Fix jenkins build
  Jenkinsfile
  pom.xml
Labels: 7.2

#8166 Fix #7850: EMX defaults value section in documentation contains non grammatical sentence + fix typo
  docs/user_documentation/finding-data/guide-search.md
  docs/user_documentation/import-data/ref-emx.md
Labels: master

#8163 [FIX] Add polyfill to all pages
  Jenkinsfile
  docs/developer_documentation/app-development.md
  molgenis-core-ui/package.json
  molgenis-core-ui/src/main/resources/js/bootstrap-4/menu/molgenis-menu.js
  molgenis-core-ui/src/main/resources/js/polyfill.js
  molgenis-core-ui/src/main/resources/js/polyfill.min.js
  molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl
Labels: 7.2

#8162 Fix #8160 Tag wizard entity type dropdown contains untaggable types
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/TagWizardController.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/controller/TagWizardControllerTest.java
Labels: master

#8164 Fix #5258: An error in an entity report causes the previous one to be shown
  molgenis-dataexplorer/src/main/resources/js/dataexplorer-data.js
Labels: master

#8172 Fix #8170 Sign up failure displays wrong error
  molgenis-security/src/main/java/org/molgenis/security/account/AccountServiceImpl.java
  molgenis-security/src/test/java/org/molgenis/security/account/AccountServiceImplTest.java
Labels: master

#8169 Include added ( custom ) css in both versions of header ( react/jquer…
  molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl
Labels: 8.0.0-SNAPSHOT, mod:core-ui

#8106 M6289 Replace spring-io with spring-boot-starter parent pom (5.0 -> 5.1)
  .travis.yml
  Jenkinsfile
  docs/quickstart/guide-tomcat.md
  molgenis-api-tests/pom.xml
  molgenis-app-manager/src/test/java/org/molgenis/app/manager/service/impl/AppManagerServiceImplTest.java
  molgenis-app/pom.xml
  molgenis-core-ui/pom.xml
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppConfig.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/permission/PermissionManagerControllerTest.java
  molgenis-data-excel/src/main/java/org/molgenis/data/excel/ExcelRepositoryCollection.java
  molgenis-data-i18n/src/test/java/org/molgenis/data/i18n/LocalizationServiceTest.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/DataPersisterImplTest.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/ImportRunServiceTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/GroupRepositoryDecoratorTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/GroupServiceTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/permission/RoleMembershipServiceImplTest.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/meta/AttributeValidatorTest.java
  molgenis-data/src/test/java/org/molgenis/data/decorator/DynamicRepositoryDecoratorRegistryImplTest.java
  molgenis-data/src/test/java/org/molgenis/data/meta/MetaDataServiceImplTest.java
  molgenis-fair/src/test/java/org/molgenis/fair/controller/FairControllerTest.java
  molgenis-js/src/main/resources/js/script-evaluator.js
  molgenis-js/src/test/java/org/molgenis/js/JsMagmaScriptEvaluatorTest.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/impl/ExcelServiceImpl.java
  molgenis-ontology-core/src/test/java/org/molgenis/ontology/core/repository/OntologyRepositoryTest.java
  molgenis-ontology-core/src/test/java/org/molgenis/ontology/core/repository/OntologyTermRepositoryTest.java
  molgenis-platform-integration-tests/pom.xml
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/export/EmxExportServiceIT.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/DataServiceClientRegistrationRepository.java
  molgenis-security/src/test/java/org/molgenis/security/account/AccountServiceImplTest.java
  molgenis-security/src/test/java/org/molgenis/security/oidc/OidcUserMapperImplTest.java
  molgenis-security/src/test/java/org/molgenis/security/twofactor/service/RecoveryServiceImplTest.java
  molgenis-security/src/test/java/org/molgenis/security/twofactor/service/TwoFactorAuthenticationServiceImplTest.java
  molgenis-security/src/test/java/org/molgenis/security/user/UserDetailsServiceTest.java
  pom.xml
Labels: master

#8174 Suppress Sonar false positives
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/NameValidator.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/string/NGramDistanceAlgorithm.java
Labels: master

#8118 Fix #8052 Validation of a mapping algorithm that refers to an unknown attribute succeeds
  docs/quickstart/guide-tomcat.md
  molgenis-js/src/main/java/org/molgenis/js/magma/JsMagmaScriptEvaluator.java
  molgenis-js/src/main/resources/js/script-evaluator.js
  molgenis-js/src/test/java/org/molgenis/js/JsMagmaScriptEvaluatorTest.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/AlgorithmException.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImpl.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/service/impl/AlgorithmServiceImplTest.java
Labels: master

#8183 Fix #7935 Default value reference entity type incorrect: improved message
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/AttributeValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/meta/AttributeValidatorTest.java
Labels: master

#8184 Fix import
  molgenis-data-excel/src/main/java/org/molgenis/data/excel/xlsx/XlsxWriter.java
Labels: master

#8175 Fix Sonar code smells VIII
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/converter/RDFMediaType.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/admin/usermanager/UserManagerServiceImplTest.java
  molgenis-core/src/main/java/org/molgenis/core/util/SchemaLoader.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/FileMetaRepositoryDecorator.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/FileStore.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/util/FileExtensionUtils.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportJob.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlQueryGenerator.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/service/RestService.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/QueryValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/PackageRepositoryValidationDecorator.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/utils/VcfUtils.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/NegotiatorController.java
  molgenis-dataexplorer/src/test/java/org/molgenis/dataexplorer/negotiator/NegotiatorControllerTest.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobConfig.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutorTokenServiceImpl.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/scheduler/AutowiringSpringBeanJobFactory.java
  molgenis-jobs/src/test/java/org/molgenis/jobs/JobExecutorTokenServiceImplTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/config/SecurityCoreITConfig.java
  molgenis-security/src/main/java/org/molgenis/security/MolgenisWebAppSecurityConfig.java
  molgenis-security/src/main/java/org/molgenis/security/group/GroupRestController.java
  molgenis-security/src/main/java/org/molgenis/security/oidc/MappedOidcUserService.java
  molgenis-security/src/main/java/org/molgenis/security/twofactor/auth/RecoveryAuthenticationProviderImpl.java
  molgenis-security/src/main/java/org/molgenis/security/user/UserDetailsServiceImpl.java
  molgenis-security/src/test/java/org/molgenis/security/oidc/MappedOidcUserServiceTest.java
  molgenis-security/src/test/java/org/molgenis/security/user/UserDetailsServiceImplTest.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/service/impl/SemanticSearchServiceImpl.java
Labels: master

#8181 Fix Sonar code smells IX
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/log/LogManagerController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/user/UserAccountController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/MolgenisStyleException.java
  molgenis-data-cache/src/main/java/org/molgenis/data/cache/l2/L2Cache.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/AggregateResponseParser.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/client/ClientFacade.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/processor/MissingValueProcessor.java
  molgenis-data-index/src/main/java/org/molgenis/data/index/IndexActionRegisterServiceImpl.java
  molgenis-data-index/src/test/java/org/molgenis/data/index/IndexActionRegisterServiceTest.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/identifier/EntityTypeRegistryImpl.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/transaction/PostgreSqlTransactionManager.java
  molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/identifier/EntityTypeRegistryImplTest.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/SortV1.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/service/RestService.java
  molgenis-data-rest/src/main/java/org/molgenis/data/rest/v2/EntityAggregatesResponse.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/aggregation/AggregateAnonymizer.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/aggregation/AggregateAnonymizerImpl.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/aggregation/AnonymizedAggregateResult.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/aggregation/AggregateAnonymizerImplTest.java
  molgenis-data-vcf/src/main/java/org/molgenis/data/vcf/format/VcfToEntity.java
  molgenis-data/src/main/java/org/molgenis/data/MolgenisInvalidFormatException.java
  molgenis-data/src/main/java/org/molgenis/data/semantic/SemanticTag.java
  molgenis-data/src/main/java/org/molgenis/data/transaction/TransactionConstants.java
  molgenis-data/src/main/java/org/molgenis/data/transaction/TransactionManager.java
  molgenis-data/src/main/java/org/molgenis/data/util/UniqueId.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/ProgressImpl.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/exceptions/UnknownFileTypeException.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/CsvService.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/OneClickImporterNamingService.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/impl/CsvServiceImpl.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/impl/OneClickImporterNamingServiceImpl.java
  molgenis-security/src/main/java/org/molgenis/security/account/AccountController.java
  molgenis-security/src/main/java/org/molgenis/security/account/RegisterRequest.java
  molgenis-security/src/main/java/org/molgenis/security/account/UsernameAlreadyExistsException.java
  molgenis-security/src/main/java/org/molgenis/security/user/UserAccountConstants.java
  molgenis-security/src/main/java/org/molgenis/security/user/UserAccountService.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/algorithmgenerator/categorymapper/FrequencyCategoryMapper.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/semantic/SearchResult.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/service/TagService.java
  molgenis-semantic-search/src/main/java/org/molgenis/semanticsearch/service/impl/OntologyTagServiceImpl.java
Labels: master

#8195 Fix Sonar code smells XI
  molgenis-data-rest/src/test/java/org/molgenis/data/rest/RestControllerTest.java
  molgenis-data/src/main/java/org/molgenis/data/AbstractSystemEntityFactory.java
  molgenis-data/src/main/java/org/molgenis/data/AttributeValueConversionException.java
  molgenis-data/src/main/java/org/molgenis/data/DataConversionException.java
  molgenis-data/src/main/java/org/molgenis/data/DataConverter.java
  molgenis-data/src/main/java/org/molgenis/data/EntityConstructionException.java
  molgenis-data/src/main/java/org/molgenis/data/EntityStream.java
  molgenis-data/src/test/java/org/molgenis/data/AbstractMolgenisSpringTest.java
  molgenis-data/src/test/java/org/molgenis/data/DataConverterTest.java
  molgenis-data/src/test/java/org/molgenis/data/support/MapOfStringsExpressionEvaluatorTest.java
  molgenis-data/src/test/java/org/molgenis/data/support/StringExpressionEvaluatorTest.java
Labels: master

#8198 Fix #2898 Script without results extension 400 error
  molgenis-js/src/main/java/org/molgenis/js/JsScriptRunner.java
  molgenis-js/src/main/java/org/molgenis/js/magma/JsMagmaScriptRunner.java
  molgenis-js/src/test/java/org/molgenis/js/JsScriptRunnerTest.java
  molgenis-js/src/test/java/org/molgenis/js/magma/JsMagmaScriptRunnerTest.java
  molgenis-python/src/main/java/org/molgenis/python/PythonScriptRunner.java
  molgenis-python/src/test/java/org/molgenis/python/PythonScriptRunnerTest.java
  molgenis-r/src/main/java/org/molgenis/r/RScriptRunner.java
  molgenis-r/src/test/java/org/molgenis/r/RScriptRunnerTest.java
  molgenis-scripts-core/src/main/java/org/molgenis/script/core/ScriptRunner.java
  molgenis-scripts-core/src/main/java/org/molgenis/script/core/ScriptUtils.java
  molgenis-scripts-core/src/test/java/org/molgenis/script/core/ScriptUtilsTest.java
  molgenis-scripts/src/main/java/org/molgenis/script/SavedScriptRunner.java
  molgenis-scripts/src/test/java/org/molgenis/script/SavedScriptRunnerTest.java
Labels: master

#8200 Cleanup "before" code for VcfUtilsTest
  molgenis-data-vcf/src/test/java/org/molgenis/data/vcf/utils/test/VcfUtilsTest.java
Labels: master
