Repository molgenis/molgenis, pull requests merged in 2019-05, with the labels that each got.

#8476 Fix #8473: Can import emx that causes conversion errors when indexed
  docs/user_documentation/import-data/ref-emx.md
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/AttributeValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/meta/AttributeValidatorTest.java
  molgenis-data/src/main/java/org/molgenis/data/support/TemplateExpressionEvaluator.java
  molgenis-data/src/main/java/org/molgenis/data/support/TemplateExpressionSyntaxException.java
Labels: 8.0

#8479 Fix #8347: Footer is rendered on top of plugin
  molgenis-core-ui/src/main/resources/css/bootstrap-4/footer/sticky-footer.css
  molgenis-core-ui/src/main/resources/templates/molgenis-header.ftl
Labels: 8.0.0-SNAPSHOT, mod:core-ui

#8483 Bump frontend with new version of frontend packages
  molgenis-frontend/package.json
Labels: 8.0.0-SNAPSHOT

#8485 Identities API update due to versioning guideline change
  molgenis-api-identities/src/main/java/org/molgenis/api/identities/GroupRestController.java
  molgenis-api-identities/src/test/java/org/molgenis/api/identities/GroupRestControllerTest.java
Labels: 8.0

#8427 Fix #8262: 'mvn test' on parent project fails
  molgenis-api-tests/pom.xml
  molgenis-platform-integration-tests/pom.xml
Labels: master

#8488 Fix #8419 Recaptcha settings should have nullable expressions
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/settings/AppDbSettings.java
Labels: master

#8500 Fix expression documentation
  docs/user_documentation/import-data/ref-emx.md
Labels: master

#8503 Fix #8502: Spring security beans are not using the molgenis roleHierarchy
  molgenis-data-security/src/main/java/org/molgenis/data/security/DataserviceRoleHierarchy.java
  molgenis-security/src/main/java/org/springframework/security/acls/jdbc/AclConfig.java
Labels: master

#8507 Update book.json: add 8.1 entry
  book.json
Labels: master

#8512 Fix #8511: Index manager is still present in default menu
  molgenis-app/src/main/resources/molgenis_ui.json
Labels: 8.1

#8509 Upgrade spring-boot-starter-parent 2.1.3.RELEASE to 2.1.5.RELEASE
  pom.xml
Labels: master

#8514 Deprecate REST v2 localization endpoints
  molgenis-api-data/src/main/java/org/molgenis/api/data/v2/RestControllerV2.java
Labels: master

#8515 Merge branch '8.1' of https://github.com/molgenis/molgenis
  molgenis-app/src/main/resources/molgenis_ui.json
Labels: master

#8506 move api/v2/version endpoint to OPTIONS /api
  molgenis-api-data/src/main/java/org/molgenis/api/data/v2/RestControllerV2.java
  molgenis-api/pom.xml
  molgenis-api/src/main/java/org/molgenis/api/ApiController.java
  molgenis-api/src/main/java/org/molgenis/api/AppVersionResponse.java
  molgenis-api/src/main/java/org/molgenis/api/OptionsResponse.java
  molgenis-api/src/main/java/org/molgenis/api/RootApiController.java
  molgenis-api/src/test/java/org/molgenis/api/ApiControllerTest.java
  molgenis-api/src/test/java/org/molgenis/api/RootApiControllerTest.java
  molgenis-swagger/src/main/resources/templates/view-swagger-ui.ftl
Labels: master

#8522 Version bumps: data-row-edit: 2.0.0 => 2.0.1 , settings: 1.0.2 => 1.0.3
  molgenis-frontend/package.json
Labels: master, mod:data-row-edit, mod:settings

#8523 Fix #8521 Import error message unknown attribute
  molgenis-data-import/src/main/resources/templates/ImportResultsWizardPage.ftl
Labels: master
