Repository molgenis/molgenis, pull requests merged in 2019-09, with the labels that each got.

#8645 Feat/alter stand alone ftl back button
  molgenis-dataexplorer/src/main/resources/templates/view-standalone-report.ftl
Labels: master

#8644 Remove Codecov in favor of SonarCloud
  .travis.yml
  Jenkinsfile
  README.md
Labels: master

#8639 UniqueId unit tests
  molgenis-data/src/main/java/org/molgenis/data/util/UniqueId.java
  molgenis-data/src/test/java/org/molgenis/data/util/UniqueIdTest.java
Labels: master

#8640 Problem type 'input-invalid'
  molgenis-web/pom.xml
  molgenis-web/src/main/java/org/molgenis/web/exception/ExceptionUtils.java
  molgenis-web/src/main/java/org/molgenis/web/exception/Problem.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ProblemExceptionResponseGenerator.java
  molgenis-web/src/main/resources/l10n/web_en.properties
  molgenis-web/src/main/resources/l10n/web_nl.properties
  molgenis-web/src/test/java/org/molgenis/web/exception/ExceptionUtilsTest.java
  molgenis-web/src/test/java/org/molgenis/web/exception/ProblemExceptionResponseGeneratorTest.java
Labels: master

#8649 Query parser improved exception message in case of tokenizer error
  molgenis-api/src/main/java/org/molgenis/api/convert/QueryParseException.java
Labels: master

#8654 Fix/query parse exception test
  molgenis-api/src/test/java/org/molgenis/api/convert/QueryParseExceptionTest.java
Labels: master

#8653 Upgrade spring-boot-starter-parent 2.1.7.RELEASE to 2.1.8.RELEASE
  pom.xml
Labels: master

#8658 Fix #8618: i18n strings take 8-16 seconds to load (in the Data Explorer)
  molgenis-api-data/src/main/java/org/molgenis/api/data/v2/RestControllerV2.java
Labels: master

#8662 Suppress squid:S1872 'Classes should not be compared by name'
  molgenis-api/src/main/java/org/molgenis/api/convert/QueryParseException.java
Labels: master

#8642 fix(chart): bumped to 1.5.2 to serve proxy server
  Jenkinsfile
Labels: master

#8648 Coded entity validation
  molgenis-api-data/src/main/java/org/molgenis/api/data/v3/DataServiceV3Impl.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v3/DataServiceV3ImplTest.java
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/data/v3/retrieveResourceCollectionInvalidInput.json
  molgenis-api/src/main/java/org/molgenis/api/convert/QueryConverter.java
  molgenis-api/src/main/java/org/molgenis/api/convert/UnknownQueryOperatorException.java
  molgenis-api/src/main/resources/l10n/api_en.properties
  molgenis-api/src/main/resources/l10n/api_nl.properties
  molgenis-api/src/test/java/org/molgenis/api/convert/QueryConverterTest.java
  molgenis-api/src/test/java/org/molgenis/api/convert/UnknownQueryOperatorExceptionTest.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/EntityErrors.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/EntityValidator.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/RepositoryConstraintViolationException.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/EntityValidatorTest.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/RepositoryConstraintViolationExceptionTest.java
  molgenis-validation/src/main/resources/l10n/validation_en.properties
  molgenis-validation/src/main/resources/l10n/validation_nl.properties
  molgenis-web/src/main/java/org/molgenis/web/exception/GlobalControllerExceptionHandler.java
  molgenis-web/src/main/java/org/molgenis/web/exception/ProblemExceptionResponseGenerator.java
Labels: master

#8672 chore(docker-compose): Remove elastic container name
  molgenis-app/dev-env/docker-compose.yml
  molgenis-platform-integration-tests/integ-test-env/docker-compose.yml
Labels: master

#8669 Fix squid:S3415 Assertion args should be passed in the correct order
  molgenis-data-security/src/test/java/org/molgenis/data/security/permission/PermissionSetUtilsTest.java
  molgenis-data/src/test/java/org/molgenis/data/FetchTest.java
  molgenis-one-click-importer/src/test/java/org/molgenis/oneclickimporter/service/OneClickImporterServiceTest.java
  molgenis-ontology/src/test/java/org/molgenis/ontology/sorta/controller/SortaControllerTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/DynamicDecoratorIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/OneToManyIT.java
  molgenis-security-core/src/test/java/org/molgenis/security/core/SidUtilsTest.java
  molgenis-security/src/test/java/org/molgenis/security/twofactor/service/TwoFactorAuthenticationServiceImplTest.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/algorithmgenerator/rules/impl/MissingCategoryRuleTest.java
  molgenis-swagger/src/test/java/org/molgenis/swagger/controller/SwaggerControllerTest.java
  molgenis-util/src/test/java/org/molgenis/util/ListEscapeUtilsTest.java
  molgenis-util/src/test/java/org/molgenis/util/mail/JavaMailSenderFactoryTest.java
  molgenis-util/src/test/java/org/molgenis/util/stream/MapCollectorsTest.java
Labels: master

#8677 Re-enable copy service integration test
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/CopyServiceIT.java
Labels: master

#8682 Re-enable copy service integration test
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/CopyServiceIT.java
Labels: master

#8683 chore(Jenkinsfile): add reminder to manually
  Jenkinsfile
Labels: master

#8678 Re-enable multi-threaded unit test execution
  Jenkinsfile
Labels: master

#8689 Fix string expression test
  molgenis-data/src/test/java/org/molgenis/data/support/StringExpressionEvaluatorTest.java
Labels: master, work in progress

#8688 Fix one-to-many tests
  molgenis-data/src/main/java/org/molgenis/data/DataService.java
  molgenis-data/src/test/java/org/molgenis/data/OneToManyTestHarness.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/OneToManyIT.java
Labels: master

#8679 Fix test template
  .idea/fileTemplates/MolgenisEntityFactoryTest.java
Labels: master

#8647 Fix Sonar issues #1
  molgenis-api-data/src/main/java/org/molgenis/api/data/v1/RestController.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v2/RestControllerV2.java
  molgenis-api-fair/src/main/java/org/molgenis/api/fair/controller/FairController.java
  molgenis-api-metrics/src/main/java/org/molgenis/api/metrics/MetricsController.java
  molgenis-app-manager/src/main/java/org/molgenis/app/manager/controller/AppController.java
  molgenis-app/src/main/java/org/molgenis/app/controller/BackgroundController.java
  molgenis-app/src/main/java/org/molgenis/app/controller/ContactController.java
  molgenis-app/src/main/java/org/molgenis/app/controller/HomeController.java
  molgenis-app/src/main/java/org/molgenis/app/controller/NewsController.java
  molgenis-app/src/main/java/org/molgenis/app/controller/ReferencesController.java
  molgenis-beacon/src/main/java/org/molgenis/beacon/controller/BeaconController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisMenuController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/log/LogManagerController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/permission/PermissionManagerController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/user/UserAccountController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/usermanager/UserManagerController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPage.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/file/FileDownloadController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/jobs/JobsController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/menumanager/MenuManagerController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/StyleSheetRepositoryDecoratorFactory.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/thememanager/ThemeManagerController.java
  molgenis-data-csv/src/main/java/org/molgenis/data/csv/CsvRepository.java
  molgenis-data-csv/src/test/java/org/molgenis/data/csv/CsvRepositoryTest.java
  molgenis-data-excel/src/main/java/org/molgenis/data/excel/ExcelRepository.java
  molgenis-data-excel/src/main/java/org/molgenis/data/excel/ExcelRepositoryCollection.java
  molgenis-data-excel/src/test/java/org/molgenis/data/excel/ExcelRepositoryCollectionTest.java
  molgenis-data-excel/src/test/java/org/molgenis/data/excel/ExcelRepositorySourceTest.java
  molgenis-data-excel/src/test/java/org/molgenis/data/excel/ExcelRepositoryTest.java
  molgenis-data-file/src/main/java/org/molgenis/data/file/model/FileMeta.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlExceptionTranslator.java
  molgenis-data-postgresql/src/main/java/org/molgenis/data/postgresql/PostgreSqlQueryGenerator.java
  molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/PostgreSqlExceptionTranslatorTest.java
  molgenis-data-postgresql/src/test/java/org/molgenis/data/postgresql/PostgreSqlQueryGeneratorTest.java
  molgenis-data-row-edit/src/main/java/org/molgenis/datarowedit/controller/DataRowEditController.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/User.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/EntityAttributesValidator.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/NegotiatorController.java
  molgenis-genomebrowser/src/main/java/org/molgenis/genomebrowser/service/GenomeBrowserService.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/schedule/JobScheduler.java
  molgenis-metadata-manager/src/main/java/org/molgenis/metadata/manager/controller/MetadataManagerController.java
  molgenis-navigator/src/main/java/org/molgenis/navigator/NavigatorController.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/controller/OneClickImporterController.java
  molgenis-one-click-importer/src/main/java/org/molgenis/oneclickimporter/service/impl/AttributeTypeServiceImpl.java
  molgenis-ontology/src/main/java/org/molgenis/ontology/sorta/controller/SortaController.java
  molgenis-r/src/main/java/org/molgenis/r/RScriptExecutor.java
  molgenis-scripts/src/main/java/org/molgenis/script/SavedScriptRunner.java
  molgenis-scripts/src/main/java/org/molgenis/script/ScriptPluginController.java
  molgenis-searchall/src/main/java/org/molgenis/searchall/controller/SearchAllPluginController.java
  molgenis-security-ui/src/main/java/org/molgenis/securityui/controller/SecurityUiController.java
  molgenis-security/src/main/java/org/molgenis/security/account/AccountController.java
  molgenis-security/src/main/java/org/molgenis/security/login/MolgenisLoginController.java
  molgenis-security/src/main/java/org/molgenis/security/user/UserDetailsServiceImpl.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/MappingServiceController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/controller/TagWizardController.java
  molgenis-semantic-mapper/src/main/java/org/molgenis/semanticmapper/utils/UnitHelper.java
  molgenis-semantic-mapper/src/test/java/org/molgenis/semanticmapper/utils/UnitHelperTest.java
  molgenis-settings-ui/src/main/java/org/molgenis/settings/controller/SettingsController.java
  molgenis-swagger/src/main/java/org/molgenis/swagger/controller/SwaggerController.java
Labels: master

#8694 Feature/m6763 metadata api
  molgenis-api-metadata/src/main/java/org/molgenis/api/metadata/v3/MetadataApiController.java
Labels: feature/metadata-api

#8696 [CHORE] manually close release on sonatype
  Jenkinsfile
  pom.xml
Labels: 8.2.0-SNAPSHOT
