Repository molgenis/molgenis, pull requests merged in 2020-04, with the labels that each got.

#8958 Fix #6902: Deleting a manual match in SORTA throws an error
  molgenis-ontology/src/main/resources/js/ontology-service-result.js
Labels: 8.3

#8961 Merge changes from 8.3 to master
  docs/guide-integration-tests.md
  molgenis-ontology/src/main/resources/js/ontology-service-result.js
Labels: branch:master

#8952 Feat/expose selected theme
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppConfig.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/controller/UiContextController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/controller/UiContextResponse.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/BootstrapThemePopulator.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/MolgenisStyleException.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/StyleController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/StyleService.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/StyleServiceImpl.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/ThemeFingerprintRegistry.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/exception/CreateThemeException.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/exception/DuplicateThemeIdException.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/style/exception/GetThemeException.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/thememanager/ThemeManagerController.java
  molgenis-core-ui/src/main/resources/l10n/core-ui_en.properties
  molgenis-core-ui/src/main/resources/l10n/core-ui_nl.properties
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/controller/UiContextControllerTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/style/BootstrapThemePopulatorTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/style/StyleServiceTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/style/ThemeFingerprintRegistryTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/style/exception/CreateThemeExceptionTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/style/exception/DuplicateThemeIdExceptionTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/style/exception/GetThemeExceptionTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/config/ViewTestConfig.java
Labels: branch:master

#8954 Updated docs to correct Java version.
  docs/guide-using-an-ide.md
Labels: 8.1

#8964 FEAT: Filter biobanks in negotiator
  molgenis-app/dev-env/intellij-tomcat-env
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/NegotiatorController.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/NegotiatorRequest.java
  molgenis-dataexplorer/src/test/java/org/molgenis/dataexplorer/negotiator/NegotiatorControllerTest.java
Labels: 8.3

#8967 Merge 8.3 -> master
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/NegotiatorController.java
  molgenis-dataexplorer/src/main/java/org/molgenis/dataexplorer/negotiator/NegotiatorRequest.java
  molgenis-dataexplorer/src/test/java/org/molgenis/dataexplorer/negotiator/NegotiatorControllerTest.java
Labels: branch:master, work in progress
