Repository molgenis/molgenis, pull requests merged in 2020-02, with the labels that each got.

#8878 Add API tests for identities api + fix #8877
  molgenis-api-identities/src/main/java/org/molgenis/api/identities/IdentitiesApiController.java
  molgenis-api-identities/src/test/java/org/molgenis/api/identities/IdentitiesApiControllerTest.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/identities/IdentitiesApiControllerIT.java
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/identities/V3Role2Response.json
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/identities/V3Role3Response.json
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/identities/V3RoleResponse.json
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/identities/members1Response.json
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/identities/members2Response.json
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/identities/members3Response.json
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/identities/roleResponse.json
Labels: branch:master, work in progress

#8872 Elasticsearch query mapper fixes
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/BaseQueryClauseGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/BaseQueryClauseRangeGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseEqualsGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseFuzzyMatchGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseFuzzyMatchNgramGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseGreaterEqualGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseGreaterGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseInGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseLessEqualGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseLessGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseLikeGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseRangeGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryClauseSearchGenerator.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryGenerator.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/BaseQueryClauseGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/BaseQueryClauseRangeGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryBuilderAssertions.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseEqualsGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseFuzzyMatchGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseFuzzyMatchNgramGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseGreaterEqualGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseGreaterGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseInGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseLessEqualGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseLessGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseLikeGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseRangeGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseSearchGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryGeneratorIT.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryGeneratorReferencesIT.java
  molgenis-data/src/main/java/org/molgenis/data/QueryUtils.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/EntityType.java
  molgenis-data/src/test/java/org/molgenis/data/QueryUtilsTest.java
  molgenis-data/src/test/java/org/molgenis/data/meta/model/EntityTypeTest.java
Labels: branch:master

#8887 Fix #8861: Permission API fails silently when trying to POST a permis…
  molgenis-data-security/src/main/java/org/molgenis/data/security/permission/PermissionServiceImpl.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/permission/PermissionServiceImplTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/CopyServiceIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/DataServiceIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/OneToManyIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformIT.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/utils/AbstractMolgenisIntegrationTests.java
Labels: 8.3.0-SNAPSHOT

#8885 Fix #8884 Executor services not shutdown on JVM shutdown
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/MolgenisWebAppInitializer.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ValidationResultWizardPage.java
  molgenis-data-index/src/main/java/org/molgenis/data/index/job/IndexJobSchedulerImpl.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionConfig.java
  molgenis-jobs/src/main/java/org/molgenis/jobs/JobExecutionUpdaterImpl.java
  molgenis-util/src/main/java/org/molgenis/util/ExecutorServiceUtils.java
Labels: 8.3.0-SNAPSHOT

#8891 fix: add new security keys to i18n module
  molgenis-security-ui/src/main/resources/l10n/security-ui_en.properties
  molgenis-security-ui/src/main/resources/l10n/security-ui_nl.properties
Labels: 8.3.0-SNAPSHOT

#8890 Fix #8888: Permissions API /permissions/ endpoint broken when a resou…
  molgenis-data-security/src/main/java/org/molgenis/data/security/permission/EntityHelper.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/permission/EntityHelperTest.java
  molgenis-security/src/main/java/org/molgenis/security/acl/AclConfig.java
  molgenis-security/src/main/java/org/molgenis/security/acl/ObjectIdentityServiceImpl.java
  molgenis-security/src/test/java/org/molgenis/security/acl/ObjectIdentityServiceImplTest.java
Labels: 8.3.0-SNAPSHOT

#8882 Fix #2763 Session cannot be restored after import
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPage.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/PackageWizardPage.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/UploadWizardPage.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/data/importer/wizard/ValidationResultWizardPage.java
Labels: 8.3.0-SNAPSHOT

#8892 Fix #8883 Import jobs reported running after restart
  Jenkinsfile
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/MolgenisBootstrapper.java
  molgenis-bootstrap/src/test/java/org/molgenis/bootstrap/MolgenisBootstrapperTest.java
  molgenis-data-import/src/main/java/org/molgenis/data/importer/ImportBootstrapper.java
  molgenis-data-import/src/test/java/org/molgenis/data/importer/ImportBootstrapperTest.java
Labels: 8.3.0-SNAPSHOT

#8898 Fix unstable UriUtilsTest
  molgenis-api-data/src/main/java/org/molgenis/api/data/v2/AttributeResponseV2.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v2/EntityCollectionResponseV2.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v2/EntityTypeResponseV2.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v2/RestControllerV2.java
  molgenis-api-data/src/main/java/org/molgenis/api/data/v2/UriUtils.java
  molgenis-api-data/src/test/java/org/molgenis/api/data/v2/UriUtilsTest.java
Labels: 8.3.0-SNAPSHOT

#8897 Fix #8896 Permission API checks uppercased roles
  molgenis-data-security/src/main/java/org/molgenis/data/security/permission/UserRoleTools.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/permission/UserRoleToolsTest.java
Labels: 8.3.0-SNAPSHOT

#8894 Refactor bootstrapper: fix memory leak
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/Bootstrapper.java
  molgenis-bootstrap/src/main/java/org/molgenis/bootstrap/BootstrapperListener.java
  molgenis-bootstrap/src/test/java/org/molgenis/bootstrap/BootstrapperListenerTest.java
  molgenis-bootstrap/src/test/java/org/molgenis/bootstrap/BootstrapperTest.java
Labels: 8.3.0-SNAPSHOT

#8899 Revert "fix: add new keys to i18n module"
  molgenis-security-ui/src/main/resources/l10n/security-ui_en.properties
  molgenis-security-ui/src/main/resources/l10n/security-ui_nl.properties
Labels: 8.3.0-SNAPSHOT

#8900 Build performance improvements
  .ci/jobs/api-tests.sh
  .ci/jobs/integration-tests.sh
  .travis.yml
  Jenkinsfile
  pom.xml
Labels: branch:master

#8905 Fix #8904, #8906 and #8908: identifier restrictions
  molgenis-data-import/src/main/resources/templates/OptionsWizardPage.ftl
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/GroupMetadata.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMetadata.java
  molgenis-data-validation/src/main/java/org/molgenis/data/validation/meta/NameValidator.java
  molgenis-data-validation/src/test/java/org/molgenis/data/validation/meta/NameValidatorTest.java
  molgenis-data/src/main/java/org/molgenis/data/meta/SystemEntityType.java
  molgenis-data/src/main/java/org/molgenis/data/meta/model/PackageMetadata.java
  molgenis-dataexplorer/src/main/resources/js/dataexplorer.js
  molgenis-js/src/test/java/org/molgenis/js/JsMagmaScriptEvaluatorTest.java
  molgenis-semantic-mapper/src/main/resources/templates/view-single-mapping-project.ftl
Labels: 8.3.0-SNAPSHOT

#8910 Fix #8909 and #8911: Migration fixes
  molgenis-data-migrate/src/main/resources/step39-createRootPackageGroups.sql
Labels: 8.3.0-SNAPSHOT

#8912 Add API test for EMX with complex identifier (numbers, dashes, underscores)
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/importpublicdata/ImportPublicDataIT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/permissions/PermissionAPIIT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v1/RestControllerV1APIIT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v2/RestControllerV2APIIT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/rest/v2/RestControllerV2IT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/upload/ImportIT.java
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/utils/RestTestUtils.java
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/upload/123-test-groep_ID-Test-RefData.json
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/upload/123-test-groep_ID-TestMeta.json
  molgenis-api-tests/src/test/resources/org/molgenis/api/tests/upload/123-test-group.xlsx
Labels: 8.3.0-SNAPSHOT

#8914 fix(security): don't expand unknown roles
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/CachedRoleHierarchyImpl.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/CachedRoleHierarchyImplTest.java
Labels: 8.3.0-SNAPSHOT

#8915 doc(emx): document identifier restrictions
  docs/guide-emx.md
Labels: 8.3.0-SNAPSHOT

#8921 Fix #8919 Metadata v3 specification errors
  docs/data/metadata-api-v3.yaml
Labels: branch:master

#8922 chore: point out 8.3 stable frontend image
  molgenis-app/dev-env/docker-stack.bash
  molgenis-app/dev-env/docker-stack.bat
Labels: 8.3.0-SNAPSHOT

#8923 Fix IdentitiesApiControllerIT running in development environment
  molgenis-api-tests/src/test/java/org/molgenis/api/tests/identities/IdentitiesApiControllerIT.java
Labels: branch:master

#8925 Various unit tests
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/BaseQueryClauseGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryClauseSearchGeneratorTest.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryGeneratorTest.java
Labels: branch:master

#8928 Various unit tests
  molgenis-data-security/src/main/java/org/molgenis/data/security/permission/PermissionSetUtils.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/permission/PermissionSetUtilsTest.java
  molgenis-data/src/test/java/org/molgenis/data/EntityManagerImplTest.java
  molgenis-data/src/test/java/org/molgenis/data/RepositoryCollectionRegistryTest.java
Labels: branch:master

#8929 Fix metadata api v3 yaml: add i18n option
  docs/data/metadata-api-v3.yaml
Labels: branch:master

#8927 Fix #8926: Duplicate basePath /api in swagger documentation
  molgenis-api-identities/pom.xml
  molgenis-api-metrics/pom.xml
Labels: branch:master

#8939 Fix Travis due to image update
  .ci/jobs/api-tests.sh
  .ci/jobs/integration-tests.sh
  .ci/services/install-postgres-11.sh
  .travis.yml
Labels: branch:master

#8941 Fix Travis due to image update
  .ci/jobs/api-tests.sh
  .ci/jobs/integration-tests.sh
  .ci/services/install-postgres-11.sh
  .travis.yml
Labels: 8.3

#8938 Various unit tests
  molgenis-api-data/src/test/java/org/molgenis/api/data/QueryMapperTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/OptionsWizardPageTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/UploadWizardPageTest.java
  molgenis-core-ui/src/test/java/org/molgenis/core/ui/data/importer/wizard/ValidationResultWizardPageTest.java
  molgenis-data-elasticsearch/src/main/java/org/molgenis/data/elasticsearch/generator/QueryGenerator.java
  molgenis-data-elasticsearch/src/test/java/org/molgenis/data/elasticsearch/generator/QueryGeneratorTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/permission/UserRoleToolsTest.java
  molgenis-util/src/test/java/org/molgenis/util/ExecutorServiceUtilsTest.java
Labels: branch:master

#8935 [DOC] Fix warnings and lose the need to host on legacy gitbook
  book.json
  docs/guide-api-data.md
  docs/guide-api-files.md
  docs/guide-api-metadata.md
  docs/guide-api-permissions.md
  docs/guide-app-manager.md
  docs/guide-authentication.md
  docs/guide-beacon.md
  docs/guide-creating-themes.md
  docs/guide-customize.md
  docs/guide-data-import.md
  docs/guide-data-metadata.md
  docs/guide-development-apps.md
  docs/guide-development-deploy-backend-services.md
  docs/guide-development.md
  docs/guide-dynamic-decorators.md
  docs/guide-emx.md
  docs/guide-explore.md
  docs/guide-fair.md
  docs/guide-groups-roles.md
  docs/guide-integration-tests.md
  docs/guide-l10n.md
  docs/guide-navigator.md
  docs/guide-permissions.md
  docs/guide-python.md
  docs/guide-questionnaire.md
  docs/guide-r.md
  docs/guide-scripts.md
  docs/guide-search.md
  docs/guide-settings.md
  docs/guide-swagger.md
  docs/guide-try-out-molgenis.md
  docs/guide-users.md
  docs/guide-using-an-ide-for-backend.md
  docs/not_in_menu/guide-SORTA.md
Labels: 8.3

#8913 Fix #4080 Update active session authentication roles
  molgenis-data-security/src/main/java/org/molgenis/data/security/SessionSecurityContextUpdater.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/SessionSecurityContextUpdaterImpl.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMembershipDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleMembershipRepositoryDecoratorFactory.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/SessionSecurityContextUpdaterImplTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/RoleMembershipDecoratorTest.java
  molgenis-platform-integration-tests/src/test/java/org/molgenis/integrationtest/platform/PlatformITConfig.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/AuthenticationAuthoritiesUpdater.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/PrincipalSecurityContextRegistry.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/SecurityContextRegistry.java
  molgenis-security-core/src/main/java/org/molgenis/security/core/SecurityContextUpdateAction.java
  molgenis-security/src/main/java/org/molgenis/security/permission/AuthenticationAuthoritiesUpdaterImpl.java
  molgenis-security/src/main/java/org/molgenis/security/permission/PrincipalSecurityContextRegistryImpl.java
  molgenis-security/src/main/java/org/molgenis/security/permission/SecurityContextRegistryImpl.java
  molgenis-security/src/test/java/org/molgenis/security/permission/PrincipalSecurityContextRegistryImplTest.java
Labels: branch:master

#8937 Fix #8936 Mapping service attribute search broken when no ontologies
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/repository/OntologyTermRepository.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/service/impl/OntologyServiceImpl.java
  molgenis-ontology-core/src/test/java/org/molgenis/ontology/core/repository/OntologyTermRepositoryTest.java
  molgenis-ontology-core/src/test/java/org/molgenis/ontology/core/service/impl/OntologyServiceImplTest.java
Labels: branch:master

#8924 docs: add deployment docs
  docs/guide-deploy-migration.md
  docs/guide-deploy-molgenis.md
  docs/guide-deploy-rpm.md
Labels: branch:master

#8940 Fix #8932 Letting a role include itself will break the application
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/CachedRoleHierarchyImpl.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/auth/RoleRepositoryDecorator.java
  molgenis-data-security/src/main/java/org/molgenis/data/security/exception/CircularRoleHierarchyException.java
  molgenis-data-security/src/main/resources/l10n/data-security_en.properties
  molgenis-data-security/src/main/resources/l10n/data-security_nl.properties
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/CachedRoleHierarchyImplTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/auth/RoleRepositoryDecoratorTest.java
  molgenis-data-security/src/test/java/org/molgenis/data/security/exception/CircularRoleHierarchyExceptionTest.java
Labels: 8.3

#8942 Fix Sonar warnings
  molgenis-api-data/src/main/java/org/molgenis/api/data/v1/RestController.java
  molgenis-core-ui/src/main/java/org/molgenis/core/ui/admin/usermanager/UserManagerController.java
  molgenis-questionnaires/src/main/java/org/molgenis/questionnaires/controller/QuestionnaireController.java
Labels: branch:master

#8945 Fix #8936 Mapping service attribute search broken when no ontologies (8.3)
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/repository/OntologyTermRepository.java
  molgenis-ontology-core/src/main/java/org/molgenis/ontology/core/service/impl/OntologyServiceImpl.java
  molgenis-ontology-core/src/test/java/org/molgenis/ontology/core/repository/OntologyTermRepositoryTest.java
  molgenis-ontology-core/src/test/java/org/molgenis/ontology/core/service/impl/OntologyServiceImplTest.java
Labels: 8.3
